%% sum_sessions_timescale_compare.m
% Summarize DLAG latent timescale distributions across sessions.
% Area-label revision: 2026-08-24
%
% This script reads timescale results generated by plot_timescale_compare.m.
% It keeps individual latent timescale values and summarizes them across
% sessions, neural groups, latent categories, and conditions.
%
% For all-condition models, the script reads one timescale result from each
% session.
%
% For condition-specific models, the script reads the sum-all-conditions
% timescale result from each session and pools the two stimulus-direction
% panels before cross-session summarization.
%
% Output files are saved under root_dir.

clc;
clear;
close all

%% ========================== USER SETTINGS ==============================

root_dir = 'I:\np_data';

data_content = 'raw_count';
% options:
% raw_count, raw_fr, z_within_trial, z_within_condition,
% z_across_conditions, demean_count_within_trial,
% demean_fr_within_trial, demean_pooledsd_within_condition

model_mode = 'all_condition_model';
% options:
% all_condition_model
% condition_specific_models

plot_session_mode = 'separate_sessions';
% options:
% pool_sessions
% separate_sessions

timescale_source = 'model-timescale';
% options:
% model-timescale
% posterior-timescale

use_dsl_filter = false;

dsl_field = 'logical';
% condition_specific_models:
% rawlogical, logical
%
% all_condition_model:
% rawlogical, logical, logical_bystimdir, logical_bystimnamedir,
% logical_bycondition

runIdx = 1;



make_plots = true;
fig_visible = 'on';
% options:
% on, off

save_mat = true;
save_fig = false;
save_png = true;
close_after_save = true;

use_log_y = false;
point_size = 28;
point_alpha = 0.70;
point_jitter_width = 0.12;

% Display/file labels only. Their order must follow the group order already
% present in the saved timescale results. These names do not select data and
% are not compared with any stored group or area name.
% Repeated area names are allowed because output tags also contain G01, G02,
% and so on; for example: {'V1', 'V2', 'V1'}.
group_names = {'V1', 'MT'};

group_colors = [0.0000 0.4470 0.7410; ...
                0.8500 0.3250 0.0980];

condition_colors = lines(8);

print_full_error_report = false;

%% ======================= VALIDATE SETTINGS =============================

validateUserSettingsLocal(model_mode, timescale_source, use_dsl_filter, ...
    dsl_field, plot_session_mode, fig_visible);

group_names = normalizeGroupNamesLocal(group_names);
[group_display_names, group_file_tags, group_mapping_tag] = ...
    buildGroupLabelsLocal(group_names);

timescale_tag = makeFileTagLocal(timescale_source);
selection_tag = makeSelectionTagLocal(use_dsl_filter, dsl_field);
model_tag = makeFileTagLocal(model_mode);

plot_mode_tag = makePlotModeTagLocal(plot_session_mode);

out_core = sprintf('%s_sum_timescale_%s_%s_%s_%s', ...
    data_content, model_tag, timescale_tag, selection_tag, plot_mode_tag);
out_base = sprintf('%s_%s', out_core, group_mapping_tag);

fprintf('Root dir          : %s\n', root_dir);
fprintf('Data content      : %s\n', data_content);
fprintf('Model mode        : %s\n', model_mode);
fprintf('Timescale source  : %s\n', timescale_source);
fprintf('DSL filter        : %d\n', use_dsl_filter);
fprintf('DSL field         : %s\n', dsl_field);
fprintf('Plot session mode : %s\n', plot_session_mode);
fprintf('Group labels      : %s\n', strjoin(group_display_names, ' | '));
fprintf('Output base       : %s\n', out_base);

%% ======================= FIND SESSION FOLDERS ==========================

session_dirs = findCatgtSessionDirsLocal(root_dir);

if isempty(session_dirs)
    error('No catgt_* folders found under one level below root_dir: %s', root_dir);
end

fprintf('Found %d candidate catgt_* session folders.\n', numel(session_dirs));

%% ======================= READ ALL SESSIONS =============================

records = {};
skipped = struct('session_dir', {}, 'reason', {});
ref = struct();

for si = 1:numel(session_dirs)

    session_dir = session_dirs{si};
    fprintf('[%d/%d] Reading %s\n', si, numel(session_dirs), session_dir);

    try
        [rec, ref] = readOneSessionLocal(session_dir, data_content, ...
            model_mode, runIdx, timescale_tag, selection_tag, ref);

        records{end+1} = rec; %#ok<SAGROW>

    catch ME
        skipped(end+1).session_dir = session_dir; %#ok<SAGROW>
        skipped(end).reason = ME.message;

        warning('Skipping session: %s\nReason: %s', session_dir, ME.message);

        if print_full_error_report
            fprintf('\nFull error report for skipped session:\n');
            fprintf('%s\n', getReport(ME, 'extended', 'hyperlinks', 'off'));
        end
    end
end

if isempty(records)
    fprintf('\nSkipped sessions:\n');
    for k = 1:numel(skipped)
        fprintf('  %s\n  %s\n', skipped(k).session_dir, skipped(k).reason);
    end
    error('No valid sessions were loaded.');
end

fprintf('Loaded %d valid sessions.\n', numel(records));
fprintf('Skipped %d sessions.\n', numel(skipped));

numGroups = ref.value_size(1);
validateGroupNameCountLocal(group_names, numGroups, ...
    'the loaded timescale results');

%% ======================= BUILD SUMMARY =================================

MultiSessionTimescale = buildMultiSessionTimescaleLocal(records, skipped, ref, ...
    root_dir, data_content, model_mode, timescale_source, ...
    use_dsl_filter, dsl_field, runIdx, plot_session_mode, out_base, ...
    group_names, group_display_names, group_file_tags, group_mapping_tag);

if save_mat
    mat_file = fullfile(root_dir, [out_base, '.mat']);
    save(mat_file, 'MultiSessionTimescale', '-v7.3');
    fprintf('Saved mat: %s\n', mat_file);
end

%% ======================= PLOT ==========================================

if make_plots

    fig_handle = plotMultiSessionTimescaleLocal(MultiSessionTimescale, ...
        fig_visible, use_log_y, point_size, point_alpha, ...
        point_jitter_width, group_display_names, group_colors, condition_colors);

    if save_fig
        savefig(fig_handle, fullfile(root_dir, [out_base, '.fig']));
    end

    if save_png
        exportgraphics(fig_handle, fullfile(root_dir, [out_base, '.png']), ...
            'Resolution', 400);
    end

    if save_fig || save_png
        fprintf('Saved figures to: %s\n', root_dir);
    end

    if close_after_save
        close(fig_handle);
    end
end

fprintf('Done.\n');

%% ========================================================================
%% Local functions
%% ========================================================================

function validateUserSettingsLocal(model_mode, timescale_source, use_dsl_filter, ...
    dsl_field, plot_session_mode, fig_visible)

    valid_model = {'all_condition_model', 'condition_specific_models'};
    valid_timescale = {'model-timescale', 'posterior-timescale'};
    valid_plot_mode = {'pool_sessions', 'separate_sessions'};
    valid_visible = {'on', 'off'};

    assertStringOptionLocal(model_mode, valid_model, 'model_mode');
    assertStringOptionLocal(timescale_source, valid_timescale, 'timescale_source');
    assertStringOptionLocal(plot_session_mode, valid_plot_mode, 'plot_session_mode');
    assertStringOptionLocal(fig_visible, valid_visible, 'fig_visible');

    if use_dsl_filter
        if strcmp(model_mode, 'condition_specific_models')
            valid_dsl = {'rawlogical', 'logical'};
        else
            valid_dsl = { ...
                'rawlogical', ...
                'logical', ...
                'logical_bystimdir', ...
                'logical_bystimnamedir', ...
                'logical_bycondition'};
        end

        assertStringOptionLocal(dsl_field, valid_dsl, 'dsl_field');
    end
end

function assertStringOptionLocal(value, validOptions, varName)

    if ~ischar(value) && ~isstring(value)
        error('%s must be a char or string.', varName);
    end

    value = char(value);

    if ~any(strcmp(value, validOptions))
        error('%s = ''%s'' is invalid. Valid options are: %s', ...
            varName, value, strjoin(validOptions, ', '));
    end
end

function session_dirs = findCatgtSessionDirsLocal(root_dir)

    listing = dir(fullfile(root_dir, '*', 'catgt_*'));
    listing = listing([listing.isdir]);

    session_dirs = cell(1, numel(listing));

    for k = 1:numel(listing)
        session_dirs{k} = fullfile(listing(k).folder, listing(k).name);
    end

    session_dirs = sort(session_dirs);
end

function [rec, ref] = readOneSessionLocal(session_dir, data_content, ...
    model_mode, runIdx, timescale_tag, selection_tag, ref)

    mat_file = getMatFileForSessionLocal(session_dir, data_content, ...
        model_mode, runIdx, timescale_tag, selection_tag);

    if ~exist(mat_file, 'file')
        error('Required mat file not found: %s', mat_file);
    end

    switch char(model_mode)

        case 'all_condition_model'

            S = load(mat_file, 'TimescaleStats');

            if ~isfield(S, 'TimescaleStats') || isempty(S.TimescaleStats)
                error('TimescaleStats not found or empty in %s.', mat_file);
            end

            [values, category_labels] = extractAllConditionTimescaleLocal( ...
                S.TimescaleStats);

            condition_labels = {};
            source_name = 'TimescaleStats';

        case 'condition_specific_models'

            S = load(mat_file, 'SummaryTimescale');

            if ~isfield(S, 'SummaryTimescale') || isempty(S.SummaryTimescale)
                error('SummaryTimescale not found or empty in %s.', mat_file);
            end

            [values, category_labels, condition_labels] = ...
                extractConditionSpecificTimescaleLocal(S.SummaryTimescale);

            source_name = 'SummaryTimescale';

        otherwise
            error('Unknown model_mode: %s', model_mode);
    end

    ref = updateAndCheckReferenceLocal(ref, values, category_labels, ...
        condition_labels, session_dir, model_mode);

    rec = struct();
    rec.session_dir = session_dir;
    rec.session_name = getSessionNameLocal(session_dir);
    rec.mat_file = mat_file;
    rec.source_name = source_name;
    rec.values = values;
end

function mat_file = getMatFileForSessionLocal(session_dir, data_content, ...
    model_mode, runIdx, timescale_tag, selection_tag)

    switch char(model_mode)

        case 'condition_specific_models'

            mat_file = fullfile(session_dir, ...
                sprintf('%s_sum_all_conditions_timescale_and_latent_category_stats_%s_%s.mat', ...
                data_content, timescale_tag, selection_tag));

        case 'all_condition_model'

            mat_file = fullfile(session_dir, sprintf('FA_Dlag_%s', data_content), ...
                'mat_results', sprintf('run%03d', runIdx), ...
                sprintf('timescale_and_latent_category_stats_%s_%s.mat', ...
                timescale_tag, selection_tag));

        otherwise

            error('Unknown model_mode: %s', model_mode);
    end
end

function [values, category_labels] = extractAllConditionTimescaleLocal(TimescaleStats)

    if ~isfield(TimescaleStats, 'labels') || isempty(TimescaleStats.labels)
        error('TimescaleStats.labels is missing or empty.');
    end

    if ~isfield(TimescaleStats, 'group') || isempty(TimescaleStats.group)
        error('TimescaleStats.group is missing or empty.');
    end

    category_labels = toCellstrLocal(TimescaleStats.labels);
    numGroups = numel(TimescaleStats.group);
    numCat = numel(category_labels);

    values = cell(numGroups, numCat);

    for g = 1:numGroups
        if ~isfield(TimescaleStats.group(g), 'values')
            error('TimescaleStats.group(%d).values is missing.', g);
        end

        if numel(TimescaleStats.group(g).values) ~= numCat
            error('TimescaleStats.group(%d).values has wrong category count.', g);
        end

        for c = 1:numCat
            values{g, c} = reshape(TimescaleStats.group(g).values{c}, 1, []);
        end
    end
end

function [values, category_labels, condition_labels] = ...
    extractConditionSpecificTimescaleLocal(SummaryTimescale)

    if ~isfield(SummaryTimescale, 'labels') || isempty(SummaryTimescale.labels)
        error('SummaryTimescale.labels is missing or empty.');
    end

    if ~isfield(SummaryTimescale, 'group') || isempty(SummaryTimescale.group)
        error('SummaryTimescale.group is missing or empty.');
    end

    category_labels = toCellstrLocal(SummaryTimescale.labels);
    condition_labels = getConditionLabelsFromSummaryTimescaleLocal(SummaryTimescale);

    numGroups = numel(SummaryTimescale.group);
    numCond = numel(condition_labels);
    numCat = numel(category_labels);

    values = cell(numGroups, numCond, numCat);

    for g = 1:numGroups

        if ~isfield(SummaryTimescale.group(g), 'stim_dir')
            error('SummaryTimescale.group(%d).stim_dir is missing.', g);
        end

        numStimDir = numel(SummaryTimescale.group(g).stim_dir);

        for d = 1:numStimDir

            if ~isfield(SummaryTimescale.group(g).stim_dir(d), 'values')
                error('SummaryTimescale.group(%d).stim_dir(%d).values is missing.', g, d);
            end

            V = SummaryTimescale.group(g).stim_dir(d).values;

            if size(V, 1) ~= numCond || size(V, 2) ~= numCat
                error('SummaryTimescale.group(%d).stim_dir(%d).values has wrong size.', g, d);
            end

            for p = 1:numCond
                for c = 1:numCat
                    values{g, p, c} = [values{g, p, c}, reshape(V{p, c}, 1, [])];
                end
            end
        end
    end
end

function condition_labels = getConditionLabelsFromSummaryTimescaleLocal(SummaryTimescale)

    if isfield(SummaryTimescale, 'meta') && ...
            isfield(SummaryTimescale.meta, 'panelConditionShortLabels')
        condition_labels = toCellstrLocal(SummaryTimescale.meta.panelConditionShortLabels);
    else
        condition_labels = defaultConditionShortLabelsLocal();
    end
end

function labels = defaultConditionShortLabelsLocal()

    labels = {'G-S-L', 'G-S-H', 'G-L-L', 'G-L-H', ...
              'P-S-L', 'P-S-H', 'P-L-L', 'P-L-H'};
end

function ref = updateAndCheckReferenceLocal(ref, values, category_labels, ...
    condition_labels, session_dir, model_mode)

    if isempty(fieldnames(ref))
        ref.value_size = size(values);
        ref.category_labels = category_labels;
        ref.condition_labels = condition_labels;
        ref.model_mode = model_mode;
        return;
    end

    if ~isequal(size(values), ref.value_size)
        error('Value size mismatch in %s. Got [%s], expected [%s].', ...
            session_dir, num2str(size(values)), num2str(ref.value_size));
    end

    if ~isequal(toCellstrLocal(category_labels), toCellstrLocal(ref.category_labels))
        error('Category labels mismatch in %s.', session_dir);
    end

    if ~isempty(ref.condition_labels) || ~isempty(condition_labels)
        if ~isequal(toCellstrLocal(condition_labels), toCellstrLocal(ref.condition_labels))
            error('Condition labels mismatch in %s.', session_dir);
        end
    end
end

function MultiSessionTimescale = buildMultiSessionTimescaleLocal(records, skipped, ...
    ref, root_dir, data_content, model_mode, timescale_source, ...
    use_dsl_filter, dsl_field, runIdx, plot_session_mode, out_base, ...
    group_names, group_display_names, group_file_tags, group_mapping_tag)

    numSessions = numel(records);

    MultiSessionTimescale = struct();
    MultiSessionTimescale.meta.root_dir = root_dir;
    MultiSessionTimescale.meta.data_content = data_content;
    MultiSessionTimescale.meta.model_mode = model_mode;
    MultiSessionTimescale.meta.timescale_source = timescale_source;
    MultiSessionTimescale.meta.use_dsl_filter = use_dsl_filter;
    MultiSessionTimescale.meta.dsl_field = dsl_field;
    MultiSessionTimescale.meta.runIdx = runIdx;
    MultiSessionTimescale.meta.plot_session_mode = plot_session_mode;
    MultiSessionTimescale.meta.output_base = out_base;
    MultiSessionTimescale.meta.group_names = group_names;
    MultiSessionTimescale.meta.group_display_names = group_display_names;
    MultiSessionTimescale.meta.group_file_tags = group_file_tags;
    MultiSessionTimescale.meta.group_mapping_tag = group_mapping_tag;
    MultiSessionTimescale.meta.group_label_source = ...
        'manual group_names parameter; display/file labels only';
    MultiSessionTimescale.meta.created_by = 'sum_sessions_timescale_compare.m';
    MultiSessionTimescale.meta.created_on = datestr(now);
    MultiSessionTimescale.meta.num_sessions = numSessions;

    MultiSessionTimescale.labels.categories = ref.category_labels;
    MultiSessionTimescale.labels.conditions = ref.condition_labels;
    MultiSessionTimescale.labels.sessions = makeSessionShortLabelsLocal(numSessions);
    MultiSessionTimescale.labels.groups = group_display_names;

    included = records;

    for s = 1:numel(included)
        if isfield(included{s}, 'values')
            included{s} = rmfield(included{s}, 'values');
        end
    end

    MultiSessionTimescale.sessions.included = included;
    MultiSessionTimescale.sessions.skipped = skipped;

    switch char(model_mode)

        case 'all_condition_model'

            numGroups = ref.value_size(1);
            numCat = ref.value_size(2);

            values = cell(numSessions, numGroups, numCat);

            for s = 1:numSessions
                for g = 1:numGroups
                    for c = 1:numCat
                        values{s, g, c} = records{s}.values{g, c};
                    end
                end
            end

            MultiSessionTimescale.values = values;
            MultiSessionTimescale.dimension_names = {'session', 'group', 'category'};

        case 'condition_specific_models'

            numGroups = ref.value_size(1);
            numCond = ref.value_size(2);
            numCat = ref.value_size(3);

            values = cell(numSessions, numGroups, numCond, numCat);

            for s = 1:numSessions
                for g = 1:numGroups
                    for p = 1:numCond
                        for c = 1:numCat
                            values{s, g, p, c} = records{s}.values{g, p, c};
                        end
                    end
                end
            end

            MultiSessionTimescale.values = values;
            MultiSessionTimescale.dimension_names = {'session', 'group', 'condition', 'category'};

        otherwise
            error('Unknown model_mode: %s', model_mode);
    end
end

function fig_handle = plotMultiSessionTimescaleLocal(M, fig_visible, ...
    use_log_y, point_size, point_alpha, point_jitter_width, ...
    group_labels, group_colors, condition_colors)

    switch char(M.meta.model_mode)

        case 'all_condition_model'

            switch char(M.meta.plot_session_mode)
                case 'pool_sessions'
                    fig_handle = plotAllConditionPoolSessionsLocal(M, fig_visible, ...
                        use_log_y, point_size, point_alpha, point_jitter_width, ...
                        group_labels, group_colors);

                case 'separate_sessions'
                    fig_handle = plotAllConditionSeparateSessionsLocal(M, fig_visible, ...
                        use_log_y, point_size, point_alpha, point_jitter_width, ...
                        group_labels, group_colors);

                otherwise
                    error('Unknown plot_session_mode: %s', M.meta.plot_session_mode);
            end

        case 'condition_specific_models'

            switch char(M.meta.plot_session_mode)
                case 'pool_sessions'
                    fig_handle = plotConditionSpecificPoolSessionsLocal(M, fig_visible, ...
                        use_log_y, point_size, point_alpha, point_jitter_width, ...
                        group_labels, condition_colors);

                case 'separate_sessions'
                    fig_handle = plotConditionSpecificSeparateSessionsLocal(M, fig_visible, ...
                        use_log_y, point_size, point_alpha, point_jitter_width, ...
                        group_labels, condition_colors);

                otherwise
                    error('Unknown plot_session_mode: %s', M.meta.plot_session_mode);
            end

        otherwise
            error('Unknown model_mode: %s', M.meta.model_mode);
    end
end

function fig_handle = plotAllConditionPoolSessionsLocal(M, fig_visible, ...
    use_log_y, point_size, point_alpha, jitter_width, ...
    group_labels, group_colors)

    values = M.values;
    numSessions = size(values, 1);
    numGroups = size(values, 2);
    numCat = size(values, 3);

    category_labels = M.labels.categories;
    group_labels = ensureGroupLabelsLocal(group_labels, numGroups);
    group_colors = ensureColorRowsLocal(group_colors, numGroups);

    groupSpacing = 0.55;
    categoryGap = 1.20;

    xPositions = nan(numGroups, numCat);

    for c = 1:numCat
        baseX = (c - 1) * (numGroups * groupSpacing + categoryGap);
        xPositions(:, c) = baseX + (1:numGroups) * groupSpacing;
    end

    fig_handle = figure('Visible', fig_visible, 'Color', 'w', ...
        'Position', [80 80 1350 760]);
    ax = axes(fig_handle);
    hold(ax, 'on');

    allVals = [];

    for c = 1:numCat
        for g = 1:numGroups

            vals = [];

            for s = 1:numSessions
                vals = [vals, reshape(values{s, g, c}, 1, [])]; %#ok<AGROW>
            end

            vals = cleanTimescaleValuesLocal(vals, use_log_y);
            allVals = [allVals, vals]; %#ok<AGROW>

            plotPointCloudLocal(ax, xPositions(g, c), vals, ...
                group_colors(g, :), point_size, point_alpha, jitter_width);
        end
    end

    applyTimescaleAxisLocal(ax, allVals, use_log_y);
    drawVerticalGuidesLocal(ax, xPositions(:), xPositions, true);

    categoryCenters = mean(xPositions, 1);

    set(ax, 'XTick', [], 'TickDir', 'out');

    addNestedLabelsLocal(ax, xPositions, group_labels, categoryCenters, ...
        category_labels, use_log_y);

    xlim(ax, [min(xPositions(:)) - 0.45, max(xPositions(:)) + 0.45]);

    ax.XGrid = 'on';
    ax.YGrid = 'on';

    ylabel(ax, 'Timescale (ms)');
    title(ax, makeFigureTitleLocal(M), 'Interpreter', 'none', 'FontWeight', 'bold');
    box(ax, 'off');

    addGroupLegendLocal(ax, group_labels, group_colors, point_size);

    hold(ax, 'off');
end

function fig_handle = plotAllConditionSeparateSessionsLocal(M, fig_visible, ...
    use_log_y, point_size, point_alpha, jitter_width, ...
    group_labels, group_colors)

    values = M.values;
    numSessions = size(values, 1);
    numGroups = size(values, 2);
    numCat = size(values, 3);

    category_labels = M.labels.categories;
    session_labels = M.labels.sessions;
    group_labels = ensureGroupLabelsLocal(group_labels, numGroups);
    group_colors = ensureColorRowsLocal(group_colors, numGroups);

    sessionSpacing = 0.70;
    groupGap = 0.95;
    categoryGap = 1.55;

    xPositions = nan(numSessions, numGroups, numCat);
    xCursor = 0;

    for c = 1:numCat
        for g = 1:numGroups
            for s = 1:numSessions
                xCursor = xCursor + sessionSpacing;
                xPositions(s, g, c) = xCursor;
            end

            if g < numGroups
                xCursor = xCursor + groupGap;
            end
        end

        if c < numCat
            xCursor = xCursor + categoryGap;
        end
    end

    figWidth = max(1400, 300 + 26 * numel(xPositions));
    fig_handle = figure('Visible', fig_visible, 'Color', 'w', ...
        'Position', [60 80 figWidth 780]);
    ax = axes(fig_handle);
    hold(ax, 'on');

    allVals = [];

    for c = 1:numCat
        for g = 1:numGroups
            for s = 1:numSessions

                vals = cleanTimescaleValuesLocal(values{s, g, c}, use_log_y);
                allVals = [allVals, vals]; %#ok<AGROW>

                plotPointCloudLocal(ax, xPositions(s, g, c), vals, ...
                    group_colors(g, :), point_size, point_alpha, jitter_width);
            end
        end
    end

    applyTimescaleAxisLocal(ax, allVals, use_log_y);
    drawVerticalGuidesLocal(ax, xPositions(:), xPositions, true);

    xt = reshape(xPositions, [], 1);
    xtLabs = makeRepeatedSessionLabelsLocal(session_labels, numGroups, numCat);

    set(ax, 'XTick', xt, 'XTickLabel', xtLabs, 'TickDir', 'out');

    if numSessions > 6
        xtickangle(ax, 45);
    end

    groupCenters = getGroupCentersFromXPositionsLocal(xPositions);
    categoryCenters = mean(groupCenters, 1);

    addNestedLabelsLocal(ax, groupCenters, group_labels, categoryCenters, ...
        category_labels, use_log_y);

    xlim(ax, [min(xPositions(:)) - 0.45, max(xPositions(:)) + 0.45]);

    ax.XGrid = 'on';
    ax.YGrid = 'on';

    ylabel(ax, 'Timescale (ms)');
    title(ax, makeFigureTitleLocal(M), 'Interpreter', 'none', 'FontWeight', 'bold');
    box(ax, 'off');

    addGroupLegendLocal(ax, group_labels, group_colors, point_size);

    hold(ax, 'off');
end

function fig_handle = plotConditionSpecificPoolSessionsLocal(M, fig_visible, ...
    use_log_y, point_size, point_alpha, jitter_width, ...
    group_labels, condition_colors)

    values = M.values;
    numSessions = size(values, 1);
    numGroups = size(values, 2);
    numCond = size(values, 3);
    numCat = size(values, 4);

    category_labels = M.labels.categories;
    condition_labels = M.labels.conditions;

    if isempty(condition_labels)
        condition_labels = defaultConditionShortLabelsLocal();
    end

    group_labels = ensureGroupLabelsLocal(group_labels, numGroups);
    condition_colors = ensureColorRowsLocal(condition_colors, numCond);

    condSpacing = 0.42;
    groupGap = 0.85;
    categoryGap = 1.45;

    xPositions = nan(numCond, numGroups, numCat);
    xCursor = 0;

    for c = 1:numCat
        for g = 1:numGroups
            for p = 1:numCond
                xCursor = xCursor + condSpacing;
                xPositions(p, g, c) = xCursor;
            end

            if g < numGroups
                xCursor = xCursor + groupGap;
            end
        end

        if c < numCat
            xCursor = xCursor + categoryGap;
        end
    end

    fig_handle = figure('Visible', fig_visible, 'Color', 'w', ...
        'Position', [40 80 1800 780]);
    ax = axes(fig_handle);
    hold(ax, 'on');

    allVals = [];

    for c = 1:numCat
        for g = 1:numGroups
            for p = 1:numCond

                vals = [];

                for s = 1:numSessions
                    vals = [vals, reshape(values{s, g, p, c}, 1, [])]; %#ok<AGROW>
                end

                vals = cleanTimescaleValuesLocal(vals, use_log_y);
                allVals = [allVals, vals]; %#ok<AGROW>

                plotPointCloudLocal(ax, xPositions(p, g, c), vals, ...
                    condition_colors(p, :), point_size, point_alpha, jitter_width);
            end
        end
    end

    applyTimescaleAxisLocal(ax, allVals, use_log_y);
    drawVerticalGuidesLocal(ax, xPositions(:), xPositions, true);

    set(ax, 'XTick', [], 'TickDir', 'out');

    groupCenters = getGroupCentersFromXPositionsLocal(xPositions);
    categoryCenters = mean(groupCenters, 1);

    addNestedLabelsLocal(ax, groupCenters, group_labels, categoryCenters, ...
        category_labels, use_log_y);

    xlim(ax, [min(xPositions(:)) - 0.45, max(xPositions(:)) + 0.45]);

    ax.XGrid = 'on';
    ax.YGrid = 'on';

    ylabel(ax, 'Timescale (ms)');
    title(ax, makeFigureTitleLocal(M), 'Interpreter', 'none', 'FontWeight', 'bold');
    box(ax, 'off');

    addConditionLegendLocal(ax, condition_labels, condition_colors, point_size);

    hold(ax, 'off');
end

function fig_handle = plotConditionSpecificSeparateSessionsLocal(M, fig_visible, ...
    use_log_y, point_size, point_alpha, jitter_width, ...
    group_labels, condition_colors)

    values = M.values;
    numSessions = size(values, 1);
    numGroups = size(values, 2);
    numCond = size(values, 3);
    numCat = size(values, 4);

    category_labels = M.labels.categories;
    condition_labels = M.labels.conditions;
    session_labels = M.labels.sessions;

    if isempty(condition_labels)
        condition_labels = defaultConditionShortLabelsLocal();
    end

    group_labels = ensureGroupLabelsLocal(group_labels, numGroups);
    condition_colors = ensureColorRowsLocal(condition_colors, numCond);

    condSpacing = 0.34;
    sessionGap = 0.42;
    groupGap = 0.95;
    categoryGap = 1.55;

    xPositions = nan(numCond, numSessions, numGroups, numCat);
    xCursor = 0;

    for c = 1:numCat
        for g = 1:numGroups
            for s = 1:numSessions
                for p = 1:numCond
                    xCursor = xCursor + condSpacing;
                    xPositions(p, s, g, c) = xCursor;
                end

                if s < numSessions
                    xCursor = xCursor + sessionGap;
                end
            end

            if g < numGroups
                xCursor = xCursor + groupGap;
            end
        end

        if c < numCat
            xCursor = xCursor + categoryGap;
        end
    end

    figWidth = max(1700, 240 + 18 * numel(xPositions));
    fig_handle = figure('Visible', fig_visible, 'Color', 'w', ...
        'Position', [40 80 figWidth 820]);
    ax = axes(fig_handle);
    hold(ax, 'on');

    allVals = [];

    for c = 1:numCat
        for g = 1:numGroups
            for s = 1:numSessions
                for p = 1:numCond

                    vals = cleanTimescaleValuesLocal(values{s, g, p, c}, use_log_y);
                    allVals = [allVals, vals]; %#ok<AGROW>

                    plotPointCloudLocal(ax, xPositions(p, s, g, c), vals, ...
                        condition_colors(p, :), point_size, point_alpha, jitter_width);
                end
            end
        end
    end

    applyTimescaleAxisLocal(ax, allVals, use_log_y);
    drawVerticalGuidesLocal(ax, xPositions(:), xPositions, true);

    sessionCenters = getSessionCentersFromConditionSeparateXLocal(xPositions);

    xt = reshape(sessionCenters, [], 1);
    xtLabs = makeRepeatedSessionLabelsLocal(session_labels, numGroups, numCat);

    set(ax, 'XTick', xt, 'XTickLabel', xtLabs, 'TickDir', 'out');

    if numSessions > 6
        xtickangle(ax, 45);
    end

    groupCenters = getGroupCentersFromXPositionsLocal(xPositions);
    categoryCenters = mean(groupCenters, 1);

    addNestedLabelsLocal(ax, groupCenters, group_labels, categoryCenters, ...
        category_labels, use_log_y);

    xlim(ax, [min(xPositions(:)) - 0.45, max(xPositions(:)) + 0.45]);

    ax.XGrid = 'on';
    ax.YGrid = 'on';

    ylabel(ax, 'Timescale (ms)');
    title(ax, makeFigureTitleLocal(M), 'Interpreter', 'none', 'FontWeight', 'bold');
    box(ax, 'off');

    addConditionLegendLocal(ax, condition_labels, condition_colors, point_size);

    hold(ax, 'off');
end

function plotPointCloudLocal(ax, x0, vals, colorVal, point_size, ...
    point_alpha, jitter_width)

    vals = reshape(vals, 1, []);
    vals = vals(isfinite(vals));

    if isempty(vals)
        return;
    end

    x = x0 + jitter_width * (rand(size(vals)) - 0.5);

    sc = scatter(ax, x, vals, point_size, colorVal, 'o', ...
        'filled', 'MarkerEdgeColor', 'none');

    try
        sc.MarkerFaceAlpha = point_alpha;
    catch
    end
end

function vals = cleanTimescaleValuesLocal(vals, use_log_y)

    vals = reshape(vals, 1, []);
    vals = vals(isfinite(vals));

    if use_log_y
        vals = vals(vals > 0);
    end
end

function applyTimescaleAxisLocal(ax, values, use_log_y)

    values = values(isfinite(values));

    if use_log_y
        values = values(values > 0);

        if isempty(values)
            set(ax, 'YScale', 'linear');
            ylim(ax, [0, 1]);
            return;
        end

        set(ax, 'YScale', 'log');

        minVal = min(values);
        maxVal = max(values);

        if minVal == maxVal
            minVal = minVal / 2;
            maxVal = maxVal * 2;
        else
            minVal = minVal / 1.4;
            maxVal = maxVal * 1.4;
        end

        minVal = max(minVal, realmin);
        ylim(ax, [minVal, maxVal]);

    else
        if isempty(values)
            ylim(ax, [0, 1]);
            return;
        end

        minVal = min(values);
        maxVal = max(values);

        if minVal == maxVal
            padding = max(abs(maxVal) * 0.2, 1);
            ylim(ax, [minVal - padding, maxVal + padding]);
        else
            padding = 0.08 * (maxVal - minVal);
            ylim(ax, [minVal - padding, maxVal + padding]);
        end
    end
end

function drawVerticalGuidesLocal(ax, smallPositions, xPositions, drawCategorySeparators)

    yl = ylim(ax);

    smallPositions = unique(reshape(smallPositions, 1, []));
    smallPositions = smallPositions(isfinite(smallPositions));

    for k = 1:numel(smallPositions)
        xline(ax, smallPositions(k), ':', ...
            'Color', [0.82 0.82 0.82], ...
            'LineWidth', 0.7);
    end

    if drawCategorySeparators
        numDims = ndims(xPositions);
        numCat = size(xPositions, numDims);

        for c = 1:(numCat - 1)
            currVals = getSliceAlongLastDimLocal(xPositions, c);
            nextVals = getSliceAlongLastDimLocal(xPositions, c + 1);

            sepX = (max(currVals(:)) + min(nextVals(:))) / 2;

            xline(ax, sepX, '-', ...
                'Color', [0.55 0.55 0.55], ...
                'LineWidth', 0.9);
        end
    end

    ylim(ax, yl);
end

function sliceVals = getSliceAlongLastDimLocal(xPositions, idxLast)

    subs = repmat({':'}, 1, ndims(xPositions));
    subs{end} = idxLast;
    sliceVals = xPositions(subs{:});
end

function groupCenters = getGroupCentersFromXPositionsLocal(xPositions)

    numDims = ndims(xPositions);

    if numDims < 2
        error('xPositions must have at least 2 dimensions.');
    end

    groupDim = numDims - 1;
    catDim = numDims;

    numGroups = size(xPositions, groupDim);
    numCat = size(xPositions, catDim);

    groupCenters = nan(numGroups, numCat);

    for g = 1:numGroups
        for c = 1:numCat
            subs = repmat({':'}, 1, numDims);
            subs{groupDim} = g;
            subs{catDim} = c;

            vals = xPositions(subs{:});
            vals = vals(:);
            vals = vals(isfinite(vals));

            if isempty(vals)
                groupCenters(g, c) = NaN;
            else
                groupCenters(g, c) = mean(vals);
            end
        end
    end
end

function sessionCenters = getSessionCentersFromConditionSeparateXLocal(xPositions)

    % xPositions dimensions:
    % condition x session x group x category

    if ndims(xPositions) ~= 4
        error('xPositions must be condition x session x group x category.');
    end

    numSessions = size(xPositions, 2);
    numGroups = size(xPositions, 3);
    numCat = size(xPositions, 4);

    sessionCenters = nan(numSessions, numGroups, numCat);

    for s = 1:numSessions
        for g = 1:numGroups
            for c = 1:numCat
                vals = xPositions(:, s, g, c);
                vals = vals(:);
                vals = vals(isfinite(vals));

                if isempty(vals)
                    sessionCenters(s, g, c) = NaN;
                else
                    sessionCenters(s, g, c) = mean(vals);
                end
            end
        end
    end
end

function addNestedLabelsLocal(ax, groupCenters, groupLabels, ...
    categoryCenters, categoryLabels, use_log_y)

    reserveBottomSpaceLocal(ax, 0.08);

    yl = ylim(ax);

    if use_log_y
        logRange = log10(yl(2)) - log10(yl(1));
        yGroup = 10 .^ (log10(yl(1)) - 0.080 * logRange);
        yCat = 10 .^ (log10(yl(1)) - 0.160 * logRange);
    else
        yGroup = yl(1) - 0.080 * (yl(2) - yl(1));
        yCat = yl(1) - 0.160 * (yl(2) - yl(1));
    end

    for c = 1:size(groupCenters, 2)
        for g = 1:size(groupCenters, 1)
            if g <= numel(groupLabels)
                text(ax, groupCenters(g, c), yGroup, groupLabels{g}, ...
                    'HorizontalAlignment', 'center', ...
                    'VerticalAlignment', 'top', ...
                    'Interpreter', 'none', ...
                    'FontWeight', 'normal', ...
                    'Clipping', 'off');
            end
        end
    end

    for c = 1:numel(categoryLabels)
        text(ax, categoryCenters(c), yCat, categoryLabels{c}, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'top', ...
            'Interpreter', 'none', ...
            'FontWeight', 'bold', ...
            'Clipping', 'off');
    end
end

function reserveBottomSpaceLocal(ax, frac)

    pos = ax.Position;

    if pos(4) > frac + 0.2
        ax.Position = [pos(1), pos(2) + frac, pos(3), pos(4) - frac];
    end
end

function addGroupLegendLocal(ax, group_labels, group_colors, point_size)

    numGroups = numel(group_labels);
    group_colors = ensureColorRowsLocal(group_colors, numGroups);
    h = gobjects(1, numGroups);

    for g = 1:numGroups
        h(g) = scatter(ax, nan, nan, point_size, group_colors(g, :), ...
            'o', 'filled', 'MarkerEdgeColor', 'none');
    end

    lgd = legend(ax, h, group_labels, ...
        'Location', 'southoutside', ...
        'Orientation', 'horizontal', ...
        'Interpreter', 'none');

    lgd.Box = 'off';
end

function addConditionLegendLocal(ax, condition_labels, condition_colors, point_size)

    numCond = numel(condition_labels);
    condition_colors = ensureColorRowsLocal(condition_colors, numCond);

    hCond = gobjects(1, numCond);

    for p = 1:numCond
        hCond(p) = scatter(ax, nan, nan, point_size, condition_colors(p, :), ...
            'o', 'filled', 'MarkerEdgeColor', 'none');
    end

    lgd = legend(ax, hCond, condition_labels, ...
        'Location', 'southoutside', ...
        'Orientation', 'horizontal', ...
        'Interpreter', 'none');

    lgd.Box = 'off';
    lgd.NumColumns = min(8, numCond);
end

function titleStr = makeFigureTitleLocal(M)

    titleStr = sprintf('%s | %s | %s | %s | %s', ...
        M.meta.data_content, ...
        M.meta.model_mode, ...
        M.meta.timescale_source, ...
        makeSelectionTitleLocal(M.meta.use_dsl_filter, M.meta.dsl_field), ...
        M.meta.plot_session_mode);
end

function s = makeSelectionTitleLocal(use_dsl_filter, dsl_field)

    if use_dsl_filter
        s = char(dsl_field);
    else
        s = 'all';
    end
end

function labels = makeSessionShortLabelsLocal(numSessions)

    labels = cell(1, numSessions);

    for s = 1:numSessions
        labels{s} = sprintf('S%d', s);
    end
end

function repeatedLabels = makeRepeatedSessionLabelsLocal(sessionLabels, numGroups, numCat)

    sessionLabels = sessionLabels(:);
    repeatedLabels = cell(numel(sessionLabels) * numGroups * numCat, 1);
    idx = 0;

    for c = 1:numCat
        for g = 1:numGroups
            for s = 1:numel(sessionLabels)
                idx = idx + 1;
                repeatedLabels{idx} = sessionLabels{s};
            end
        end
    end
end

function name = getSessionNameLocal(session_dir)

    [parent_dir, catgt_name] = fileparts(session_dir);
    [~, parent_name] = fileparts(parent_dir);

    name = sprintf('%s/%s', parent_name, catgt_name);
end

function tag = makeFileTagLocal(label)

    label = char(string(label));
    tag = lower(label);
    tag = regexprep(tag, '[^a-z0-9]+', '_');
    tag = regexprep(tag, '^_+|_+$', '');
end

function selection_tag = makeSelectionTagLocal(use_dsl_filter, dsl_field)

    if ~use_dsl_filter
        selection_tag = 'all';
    else
        selection_tag = makeFileTagLocal(dsl_field);
    end
end

function group_names = normalizeGroupNamesLocal(group_names)

    if isstring(group_names)
        group_names = cellstr(group_names(:)');
    elseif ischar(group_names)
        if size(group_names, 1) == 1
            group_names = {group_names};
        else
            group_names = reshape(cellstr(group_names), 1, []);
        end
    elseif iscell(group_names)
        group_names = reshape(group_names, 1, []);
    else
        error('group_names must be text or a cell array of text.');
    end

    if isempty(group_names)
        error('group_names cannot be empty.');
    end

    for g = 1:numel(group_names)
        value = group_names{g};

        if ~(ischar(value) || (isstring(value) && isscalar(value)))
            error('group_names{%d} must contain text.', g);
        end

        value = strtrim(char(string(value)));

        if isempty(value)
            error('group_names{%d} cannot be empty.', g);
        end

        group_names{g} = value;
    end
end

function [group_display_names, group_file_tags, group_mapping_tag] = ...
        buildGroupLabelsLocal(group_names)

    nGroups = numel(group_names);
    group_display_names = cell(1, nGroups);
    group_file_tags = cell(1, nGroups);

    for g = 1:nGroups
        group_display_names{g} = sprintf( ...
            'Group %d: %s', g, group_names{g});
        group_file_tags{g} = sprintf( ...
            'G%02d_%s', g, makeSafeGroupNameTagLocal(group_names{g}));
    end

    group_mapping_tag = strjoin(group_file_tags, '_');
end

function tag = makeSafeGroupNameTagLocal(group_name)

    tag = strtrim(char(string(group_name)));
    tag = regexprep(tag, '[^A-Za-z0-9_-]+', '_');
    tag = regexprep(tag, '_+', '_');
    tag = regexprep(tag, '^_+|_+$', '');

    if isempty(tag)
        tag = 'area';
    end
end

function validateGroupNameCountLocal(group_names, numGroups, context_text)

    if numel(group_names) ~= numGroups
        error(['group_names has %d entries, but %s contains %d groups. ' ...
               'The order of group_names must follow the saved group order.'], ...
              numel(group_names), context_text, numGroups);
    end
end

function labels = ensureGroupLabelsLocal(group_labels, numGroups)

    if numel(group_labels) ~= numGroups
        error(['The manual group-label list has %d entries, but the plotted ' ...
               'result contains %d groups.'], numel(group_labels), numGroups);
    end

    labels = reshape(group_labels, 1, []);
end

function colors = ensureColorRowsLocal(colors, nRows)

    if ~isempty(colors) && (size(colors, 2) ~= 3 || ...
            any(~isfinite(colors(:))) || any(colors(:) < 0) || ...
            any(colors(:) > 1))
        error('group_colors must be a finite N-by-3 RGB matrix in [0, 1].');
    end

    fallback = lines(nRows);
    nProvided = min(size(colors, 1), nRows);

    if nProvided > 0
        fallback(1:nProvided, :) = colors(1:nProvided, :);
    end

    colors = fallback;
end

function labels = toCellstrLocal(x)

    if iscell(x)
        labels = cell(size(x));
        for k = 1:numel(x)
            labels{k} = char(string(x{k}));
        end
        labels = reshape(labels, size(x));
    elseif isstring(x)
        labels = cellstr(x);
    elseif ischar(x)
        labels = cellstr(x);
    else
        error('Input cannot be converted to cellstr.');
    end
end


function tag = makePlotModeTagLocal(plot_session_mode)

    switch char(plot_session_mode)
        case 'pool_sessions'
            tag = 'pool_s';

        case 'separate_sessions'
            tag = 'separ_s';

        otherwise
            tag = makeFileTagLocal(plot_session_mode);
    end
end
