%% calculate_pooled_conditions_R2.m
% Compute pooled-across-conditions reconstruction R2 from condition-specific
% DLAG bestmodel*.mat files.
%
% Run this script after data_reconstruction.m.
%
% This script does not reconstruct data again.
% It loads each condition-specific bestmodel*.mat, reads seqEst.y and the
% selected reconstruction fields generated by data_reconstruction.m, then
% computes pooled-across-conditions R2 by concatenating data across
% conditions in the R2 calculation.
%
% Important:
%   The pooled R2 is recomputed from y and yRecon fields.
%   It is NOT computed by averaging condition-wise R2 values.
%
% This version is adapted for the latest data_reconstruction.m directional
% fields, but intentionally excludes:
%
%   1) d / no-d diagnostic fields:
%       d
%       yRecon_use_across_no_d
%       yRecon_use_within_no_d
%       yRecon_use_all_no_d
%
%   2) sampled-noise fields:
%       *_with_R
%
%   3) residual-preserving fields:
%       *_keep_resid
%
% This version includes only:
%
%   base reconstruction fields:
%       yRecon_use_across
%       yRecon_use_within
%       yRecon_use_all
%       yRecon_across_excl_within
%       yRecon_within_excl_across
%
%   directional FF/FB fields:
%       yRecon_use_feedback
%       yRecon_feedback_excl_within_ff_ambiguous
%       yRecon_feedback_excl_within
%       yRecon_feedback_excl_ff_ambiguous
%
%       yRecon_use_feedforward
%       yRecon_feedforward_excl_within_fb_ambiguous
%       yRecon_feedforward_excl_within
%       yRecon_feedforward_excl_fb_ambiguous
%
% Output:
%   <data_content>_sum_all_conditions_reconstruction_R2.mat
%
% Saved variable:
%   recon_R2
%
% recon_R2 has the same structure style as reconstruction_R2.mat:
%   recon_R2.<field>.global_all
%   recon_R2.<field>.global_by_group
%   recon_R2.<field>.neuron_by_group
%
% R2 definition:
%   R2 = 1 - RSS / TSS
%
% For pooled conditions:
%   TSS is computed around the pooled per-neuron mean across all selected
%   conditions. This is equivalent to concatenating all condition-specific
%   trials/time bins first and then computing one R2.
%
% Negative R2 values are allowed and are not clipped.

clc;
clear;

%% ------------------------------------------------------------------------
% User parameters
% -------------------------------------------------------------------------

data_content = 'raw_count';
% options usually include:
% raw_count, raw_fr, z_within_trial, z_within_condition,
% z_across_conditions, demean_count_within_trial, demean_fr_within_trial,
% demean_pooledsd_within_condition

data_condition = [1:16];
% Must be non-empty. This script pools condition-specific models.

runIdx = 1;

% Display/file labels only. Their order must follow the DLAG model-group
% order. These names do not affect R2 calculation and are not compared
% with any stored group or area names.
group_names = {'V1', 'MT'};

output_file_name = sprintf('%s_sum_all_conditions_reconstruction_R2.mat', data_content);

%% ------------------------------------------------------------------------
% Setup
% -------------------------------------------------------------------------

if isempty(data_condition)
    error('data_condition must be non-empty for pooled condition R2.');
end

condition_list = data_condition(:)';
numConditions = numel(condition_list);

group_names = normalizeGroupNamesLocal(group_names);
[group_display_names, group_file_tags] = ...
    buildGroupLabelsLocal(group_names);

scriptDir = fileparts(mfilename('fullpath'));
if isempty(scriptDir)
    scriptDir = pwd;
end

outFile = fullfile(scriptDir, output_file_name);

r2_specs = getReconstructionR2SpecsLocal();

fprintf('\n============================================================\n');
fprintf('Calculating pooled-across-conditions reconstruction R2\n');
fprintf('data_content: %s\n', data_content);
fprintf('runIdx: %d\n', runIdx);
fprintf('Number of conditions: %d\n', numConditions);
fprintf('Number of reconstruction fields: %d\n', size(r2_specs, 1));
fprintf('Output file: %s\n', outFile);

fprintf('\nFields included in pooled R2:\n');
for s = 1:size(r2_specs, 1)
    fprintf('  %2d. %-45s -> %s\n', s, r2_specs{s, 1}, r2_specs{s, 2});
end

%% ------------------------------------------------------------------------
% Locate and validate all condition-specific bestmodel files
% -------------------------------------------------------------------------

bestFiles = cell(1, numConditions);

yDims_ref = [];
yDim_ref = [];

for cond_i = 1:numConditions

    this_condition = condition_list(cond_i);

    baseDir = ['./FA_Dlag_', data_content, '_condition', num2str(this_condition)];
    tempfname = sprintf('%s/mat_results/run%03d', baseDir, runIdx);

    bestFiles{cond_i} = findOneFileLocal(tempfname, 'bestmodel*', true);

    fprintf('\nCondition %d best model:\n  %s\n', this_condition, bestFiles{cond_i});

    S = load(bestFiles{cond_i}, 'bestModel', 'res', 'seqEst');

    requiredVars = {'bestModel', 'res', 'seqEst'};
    for v = 1:numel(requiredVars)
        if ~isfield(S, requiredVars{v})
            error('File %s is missing variable %s.', ...
                bestFiles{cond_i}, requiredVars{v});
        end
    end

    if ~isfield(S.res, 'estParams')
        error('File %s is missing res.estParams.', bestFiles{cond_i});
    end

    params = normalizeParamDimsLocal(S.res.estParams, S.bestModel);

    yDims = params.yDims;
    yDim = sum(yDims);

    if isempty(yDims_ref)
        yDims_ref = yDims;
        yDim_ref = yDim;
    else
        if ~isequal(yDims_ref, yDims)
            error('Condition %d has yDims different from the first condition.', ...
                this_condition);
        end
    end

    checkSeqEstFieldsLocal(S.seqEst, r2_specs, yDim);
end

numGroups = numel(yDims_ref);
validateGroupNameCountLocal(group_names, numGroups);

fprintf('\nModel groups used for pooled R2:\n');
for g = 1:numGroups
    fprintf('  %s | neurons %d\n', ...
        group_display_names{g}, yDims_ref(g));
end

%% ------------------------------------------------------------------------
% First pass: compute pooled per-neuron mean for each reconstruction field
%
% The mean is computed using all condition-specific data concatenated
% conceptually across time/trials.
%
% It is field-specific only because valid samples are defined by:
%   isfinite(Ytrue) & isfinite(Ypred)
%
% In normal cases, all included reconstruction fields should share the same
% valid mask.
% -------------------------------------------------------------------------

fprintf('\nFirst pass: computing pooled means...\n');

numSpecs = size(r2_specs, 1);

sumY = cell(numSpecs, 1);
countY = cell(numSpecs, 1);

for s = 1:numSpecs
    sumY{s} = zeros(yDim_ref, 1);
    countY{s} = zeros(yDim_ref, 1);
end

for cond_i = 1:numConditions

    this_condition = condition_list(cond_i);

    fprintf('  Reading condition %d for means...\n', this_condition);

    S = load(bestFiles{cond_i}, 'seqEst');
    seqEst = S.seqEst;

    Ytrue = [seqEst.y];

    if size(Ytrue, 1) ~= yDim_ref
        error('Condition %d Ytrue has %d rows, expected %d.', ...
            this_condition, size(Ytrue, 1), yDim_ref);
    end

    for s = 1:numSpecs

        fieldName = r2_specs{s, 2};

        Ypred = [seqEst.(fieldName)];

        if ~isequal(size(Ytrue), size(Ypred))
            error('Condition %d field %s has size mismatch with y.', ...
                this_condition, fieldName);
        end

        valid = isfinite(Ytrue) & isfinite(Ypred);

        Ytmp = Ytrue;
        Ytmp(~valid) = 0;

        sumY{s} = sumY{s} + sum(Ytmp, 2);
        countY{s} = countY{s} + sum(valid, 2);
    end
end

muY = cell(numSpecs, 1);

for s = 1:numSpecs
    mu = sumY{s} ./ countY{s};
    mu(countY{s} == 0) = NaN;
    muY{s} = mu;
end

%% ------------------------------------------------------------------------
% Second pass: accumulate RSS and TSS for each reconstruction field
% -------------------------------------------------------------------------

fprintf('\nSecond pass: accumulating RSS and TSS...\n');

RSS = cell(numSpecs, 1);
TSS = cell(numSpecs, 1);

for s = 1:numSpecs
    RSS{s} = zeros(yDim_ref, 1);
    TSS{s} = zeros(yDim_ref, 1);
end

for cond_i = 1:numConditions

    this_condition = condition_list(cond_i);

    fprintf('  Reading condition %d for RSS/TSS...\n', this_condition);

    S = load(bestFiles{cond_i}, 'seqEst');
    seqEst = S.seqEst;

    Ytrue = [seqEst.y];

    if size(Ytrue, 1) ~= yDim_ref
        error('Condition %d Ytrue has %d rows, expected %d.', ...
            this_condition, size(Ytrue, 1), yDim_ref);
    end

    for s = 1:numSpecs

        fieldName = r2_specs{s, 2};

        Ypred = [seqEst.(fieldName)];

        if ~isequal(size(Ytrue), size(Ypred))
            error('Condition %d field %s has size mismatch with y.', ...
                this_condition, fieldName);
        end

        valid = isfinite(Ytrue) & isfinite(Ypred);

        D = Ytrue - repmat(muY{s}, 1, size(Ytrue, 2));
        E = Ytrue - Ypred;

        D(~valid) = 0;
        E(~valid) = 0;

        RSS{s} = RSS{s} + sum(E.^2, 2);
        TSS{s} = TSS{s} + sum(D.^2, 2);
    end
end

%% ------------------------------------------------------------------------
% Build recon_R2
% -------------------------------------------------------------------------

fprintf('\nBuilding pooled R2 structure...\n');

recon_R2_pooled_conditions = struct();

for s = 1:numSpecs

    r2Name = r2_specs{s, 1};

    rss = RSS{s};
    tss = TSS{s};

    recon_R2_pooled_conditions.(r2Name).global_all = ...
        computeGlobalFromSumsLocal(rss, tss);

    recon_R2_pooled_conditions.(r2Name).global_by_group = nan(1, numGroups);
    recon_R2_pooled_conditions.(r2Name).neuron_by_group = cell(1, numGroups);

    neuronR2 = computeNeuronFromSumsLocal(rss, tss);

    for groupIdx = 1:numGroups

        rows = getGroupRowsLocal(yDims_ref, groupIdx);

        recon_R2_pooled_conditions.(r2Name).global_by_group(groupIdx) = ...
            computeGlobalFromSumsLocal(rss(rows), tss(rows));

        recon_R2_pooled_conditions.(r2Name).neuron_by_group{groupIdx} = ...
            neuronR2(rows);
    end
end

% Save as recon_R2 so plotting code can reuse the same variable name.
recon_R2 = recon_R2_pooled_conditions;
recon_R2.meta = struct();
recon_R2.meta.group_names = group_names;
recon_R2.meta.group_display_names = group_display_names;
recon_R2.meta.group_file_tags = group_file_tags;
recon_R2.meta.yDims = yDims_ref;
recon_R2.meta.data_content = data_content;
recon_R2.meta.data_condition = condition_list;
recon_R2.meta.runIdx = runIdx;
recon_R2.meta.pooling = 'concatenate selected conditions before R2 calculation';

%% ------------------------------------------------------------------------
% Save
% -------------------------------------------------------------------------

fprintf('\nSaving pooled R2 to:\n  %s\n', outFile);

save(outFile, 'recon_R2', '-v7.3');

fprintf('Done.\n');

%% ========================================================================
% Local functions
% ========================================================================

function r2_specs = getReconstructionR2SpecsLocal()
% Reconstruction fields to include in pooled R2.
%
% This version includes:
%   5 original base reconstruction fields
%   8 FF/FB directional reconstruction fields
%
% This version intentionally excludes:
%   4 d / no-d diagnostic fields
%   5 *_with_R fields
%   5 *_keep_resid fields

r2_specs = {
    % -------------------------------------------------------------
    % Original base fields
    % -------------------------------------------------------------
    'use_across', ...
        'yRecon_use_across';

    'use_within', ...
        'yRecon_use_within';

    'use_all', ...
        'yRecon_use_all';

    'across_excl_within', ...
        'yRecon_across_excl_within';

    'within_excl_across', ...
        'yRecon_within_excl_across';

    % -------------------------------------------------------------
    % Feedback directional fields
    % -------------------------------------------------------------
    'use_feedback', ...
        'yRecon_use_feedback';

    'feedback_excl_within_ff_ambiguous', ...
        'yRecon_feedback_excl_within_ff_ambiguous';

    'feedback_excl_within', ...
        'yRecon_feedback_excl_within';

    'feedback_excl_ff_ambiguous', ...
        'yRecon_feedback_excl_ff_ambiguous';

    % -------------------------------------------------------------
    % Feedforward directional fields
    % -------------------------------------------------------------
    'use_feedforward', ...
        'yRecon_use_feedforward';

    'feedforward_excl_within_fb_ambiguous', ...
        'yRecon_feedforward_excl_within_fb_ambiguous';

    'feedforward_excl_within', ...
        'yRecon_feedforward_excl_within';

    'feedforward_excl_fb_ambiguous', ...
        'yRecon_feedforward_excl_fb_ambiguous'
};
end

function checkSeqEstFieldsLocal(seqEst, r2_specs, yDim)
% Check that seqEst contains y and all requested reconstruction fields.
%
% This function is strict by design. If a requested field is missing in any
% condition, the pooled R2 would no longer be comparable across conditions,
% so the script stops with an error.

if isempty(seqEst)
    error('seqEst is empty.');
end

if ~isfield(seqEst, 'y')
    error('seqEst is missing field y.');
end

for n = 1:numel(seqEst)

    if isempty(seqEst(n).y)
        error('seqEst(%d).y is empty.', n);
    end

    if size(seqEst(n).y, 1) ~= yDim
        error('seqEst(%d).y has %d rows, expected %d.', ...
            n, size(seqEst(n).y, 1), yDim);
    end
end

for s = 1:size(r2_specs, 1)

    fieldName = r2_specs{s, 2};

    if ~isfield(seqEst, fieldName)
        error('seqEst is missing reconstruction field %s.', fieldName);
    end

    for n = 1:numel(seqEst)

        if isempty(seqEst(n).(fieldName))
            error('seqEst(%d).%s is empty.', n, fieldName);
        end

        if ~isequal(size(seqEst(n).(fieldName)), size(seqEst(n).y))
            error('seqEst(%d).%s size does not match seqEst(%d).y.', ...
                n, fieldName, n);
        end
    end
end
end

function R2 = computeGlobalFromSumsLocal(rss, tss)
% Compute global R2 from accumulated per-neuron RSS and TSS.
%
% Negative R2 is allowed.

rssTotal = sum(rss(:));
tssTotal = sum(tss(:));

if tssTotal > 0 && isfinite(tssTotal)
    R2 = 1 - rssTotal / tssTotal;
else
    R2 = NaN;
end
end

function R2 = computeNeuronFromSumsLocal(rss, tss)
% Compute neuron-wise R2 from accumulated per-neuron RSS and TSS.
%
% Negative R2 is allowed.

R2 = nan(numel(rss), 1);

valid = tss > 0 & isfinite(tss) & isfinite(rss);

R2(valid) = 1 - rss(valid) ./ tss(valid);
end

function params = normalizeParamDimsLocal(params, bestModel)
% Normalize params.yDims, params.xDim_across, and params.xDim_within.
%
% Only yDims is essential for pooled R2, but keeping this helper similar to
% data_reconstruction.m makes the code robust to saved parameter format.

if ~isfield(params, 'yDims')
    error('params must contain yDims.');
end

params.yDims = reshape(params.yDims, 1, []);

numGroups = numel(params.yDims);

if ~isfield(params, 'xDim_across') || isempty(params.xDim_across)
    if ~isempty(bestModel) && isfield(bestModel, 'xDim_across')
        params.xDim_across = bestModel.xDim_across;
    else
        params.xDim_across = 0;
    end
end

if ~isfield(params, 'xDim_within') || isempty(params.xDim_within)
    if ~isempty(bestModel) && isfield(bestModel, 'xDim_within')
        params.xDim_within = bestModel.xDim_within;
    else
        params.xDim_within = zeros(1, numGroups);
    end
end

params.xDim_across = double(params.xDim_across);

params.xDim_within = reshape(params.xDim_within, 1, []);

if isscalar(params.xDim_within) && numGroups > 1
    params.xDim_within = repmat(params.xDim_within, 1, numGroups);
end

if numel(params.xDim_within) ~= numGroups
    error('xDim_within must have one entry per group.');
end

params.xDim_within = double(params.xDim_within);
end

function rows = getGroupRowsLocal(yDims, groupIdx)
% Row indices for one observed group.

startIdx = sum(yDims(1:groupIdx-1)) + 1;
rows = startIdx:(startIdx + yDims(groupIdx) - 1);
end

function fname = findOneFileLocal(parentDir, pattern, mustExist)
% Return the newest file matching pattern in parentDir.

if ~exist(parentDir, 'dir')
    error('Directory not found: %s', parentDir);
end

files = dir(fullfile(parentDir, pattern));

if isempty(files)
    if mustExist
        error('No %s file found in %s.', pattern, parentDir);
    else
        fname = '';
        return;
    end
end

[~, idx] = sort([files.datenum], 'descend');
files = files(idx);

fname = fullfile(parentDir, files(1).name);
end

function group_names = normalizeGroupNamesLocal(group_names)

if isstring(group_names)
    group_names = cellstr(group_names(:)');
elseif ischar(group_names)
    if size(group_names, 1) == 1
        group_names = {group_names};
    else
        group_names = reshape(cellstr(group_names), 1, []);
    end
elseif iscell(group_names)
    group_names = reshape(group_names, 1, []);
else
    error('group_names must be text or a cell array of text.');
end

if isempty(group_names)
    error('group_names cannot be empty.');
end

for g = 1:numel(group_names)
    value = group_names{g};

    if ~(ischar(value) || (isstring(value) && isscalar(value)))
        error('group_names{%d} must contain text.', g);
    end

    value = strtrim(char(string(value)));

    if isempty(value)
        error('group_names{%d} cannot be empty.', g);
    end

    group_names{g} = value;
end
end

function validateGroupNameCountLocal(group_names, numGroups)

if numel(group_names) ~= numGroups
    error([ ...
        'group_names has %d entries, but the current DLAG model contains ', ...
        '%d groups. The order of group_names must follow the model-group ', ...
        'order.'], numel(group_names), numGroups);
end
end

function [groupDisplayNames, groupFileTags] = ...
        buildGroupLabelsLocal(group_names)

nGroups = numel(group_names);
groupDisplayNames = cell(1, nGroups);
groupFileTags = cell(1, nGroups);

for g = 1:nGroups
    groupDisplayNames{g} = sprintf('Group %d: %s', g, group_names{g});
    groupFileTags{g} = sprintf( ...
        'G%02d_%s', g, makeSafeGroupNameTagLocal(group_names{g}));
end
end

function tag = makeSafeGroupNameTagLocal(groupName)

tag = strtrim(char(string(groupName)));
tag = regexprep(tag, '[^A-Za-z0-9_-]+', '_');
tag = regexprep(tag, '_+', '_');
tag = regexprep(tag, '^_+|_+$', '');

if isempty(tag)
    tag = 'area';
end
end
