%% =========================================================================
% contrast_effect_comparation.m
%
% Purpose:
% Compare contrast effect metrics across different analysis fields.
%
% This script is a downstream analysis of plot_contrast_effect.m.
% It does not recompute contrast effect from seqEst.
% Instead, it loads saved contrast_effect_result files generated by
% plot_contrast_effect.m.
%
% For each metric:
% - make one summary figure
% - each panel is one baseline_field x comparation_field comparison
% - x-axis: baseline field contrast effect metric
% - y-axis: compared field contrast effect metric
% - all groups are plotted in the same panel with different colors
%
% Summary output:
% - For each specific comparison panel, save one comparison_summary mat.
% - One comparison_summary contains all groups.
% - For each group, save:
%       1. Linear regression using all valid points:
%             regression_all
%
%       2. Linear regression using only central / non-broken points:
%             regression_central
%
%          The central regression uses points satisfying:
%             abs(base metric) <= break_start
%             abs(compared metric) <= break_start
%
%          If broken-axis display is not used for that panel, central points
%          are all valid points, so regression_central equals regression_all.
%
%       3. Delta analysis based on baseline index sign:
%             delta = compared - baseline
%          Units are split by baseline metric:
%             baseline >= 0
%             baseline < 0
%
% Time-window mode:
% - analysis_window and sliding_step are in seconds.
% - This script does not generate time windows from raw data.
% - It only uses these two parameters to find files generated by
%   plot_contrast_effect.m.
%
% File matching:
% - If time-window files exist:
%       *_contrast_effect_<field>_G01_V1_G02_MT_wn0_2_st0_2_w01.mat
%       *_contrast_effect_<field>_G01_V1_G02_MT_wn0_2_st0_2_w02.mat
%   then this script compares fields within each time window separately.
%
% - If no time-window files exist and the full-trial single-window file
%   exists:
%       *_contrast_effect_<field>_G01_V1_G02_MT.mat
%   then this script loads that file.
%
% - The mapping tag is built only from the manual group_names parameter.
%   The script never reads or compares names stored in the input MAT.
%
% Important:
% - All results are assumed to be generated by the updated
%   plot_contrast_effect.m.
% - Therefore every loaded contrast_effect_result should contain time
%   metadata.
% - Full-trial result is also treated as a valid time window:
%       is_full_trial_single_window = true
%       nWindows = 1
%       time_window_index = 1
%       time_file_suffix = ''
%
% No cross-time-window comparison is performed.
% Each figure compares fields within the same time window only.
%
% Metric names used in this comparison script:
% - dHL:
%       high - low
%       stored in contrast_effect_result as delta_HL
%
% - CMI:
%       (high - low) / (abs(high) + abs(low))
%
% Note:
% plot_contrast_effect.m saves the absolute-difference metric as
% contrast_effect_result.delta_HL.
% This comparison script exposes it as dHL for user parameters, labels,
% and file tags, but internally reads contrast_effect_result.delta_HL.
%
% Path convention:
% - model_mode = 'all_condition_model'
%       read/save in ./FA_Dlag_<data_content>/mat_results/runXXX/
%
% - model_mode = 'condition_specific_models'
%       read/save in this script's folder
%
% Plot style:
% - Group colors follow plot_reconstruction_R2.m / RF_analysis.m style.
% - Each panel has y = x, x = 0, and y = 0 dashed reference lines.
% =========================================================================

clc;
clear;

%% ----------------------- User parameters -----------------------

data_content = 'raw_count';
% options:
% raw_count, raw_fr, z_within_trial, z_within_condition,
% z_across_conditions, demean_count_within_trial,
% demean_fr_within_trial, demean_pooledsd_within_condition

% Options:
% 'all_condition_model'
% 'condition_specific_models'
model_mode = 'all_condition_model';

runIdx = 1;

% Time-window parameters, in seconds.
%
% Must match the values used in plot_contrast_effect.m.
%
% If plot_contrast_effect.m generated multiple windows, this script will load:
%   _wn0_2_st0_2_w01
%   _wn0_2_st0_2_w02
% etc.
%
% If plot_contrast_effect.m generated a full-trial single window, this script
% loads the area-tagged filename without a time suffix. The loaded mat is
% still expected to contain time metadata.
analysis_window = 0.4;
sliding_step    = 0.2;

% Fields to analyze from seqEst.
%
% Example:
% baseline_fields = {'y'};
% baseline_fields = {'yRecon_use_all'};
%
% Original data:
%   y
%
% Base noiseless reconstruction fields after data_reconstruction.m:
%   d
%   yRecon_use_across
%   yRecon_use_within
%   yRecon_use_all
%   yRecon_use_across_no_d
%   yRecon_use_within_no_d
%   yRecon_use_all_no_d
%   yRecon_across_excl_within
%   yRecon_within_excl_across
%
% Feedback / feedforward fields, if generated:
%   yRecon_use_feedback
%   yRecon_feedback_excl_within_ff_ambiguous
%   yRecon_feedback_excl_within
%   yRecon_feedback_excl_ff_ambiguous
%
%   yRecon_use_feedforward
%   yRecon_feedforward_excl_within_fb_ambiguous
%   yRecon_feedforward_excl_within
%   yRecon_feedforward_excl_fb_ambiguous
%
% Reconstruction fields with R noise, if generated:
%   yRecon_use_across_with_R
%   yRecon_use_within_with_R
%   yRecon_use_all_with_R
%   yRecon_across_excl_within_with_R
%   yRecon_within_excl_across_with_R
%
% Reconstruction fields keeping residual, if generated:
%   yRecon_use_across_keep_resid
%   yRecon_use_within_keep_resid
%   yRecon_use_all_keep_resid
%   yRecon_across_excl_within_keep_resid
%   yRecon_within_excl_across_keep_resid
% 
% Also adapted to timescale output, like:
% 'yRecon_use_across_model_ts_v0_v120',...
% 'yRecon_use_across_model_ts_v120_v300',...
% 'yRecon_use_across_model_ts_v300_inf',...
% 'yRecon_use_within_model_ts_v0_v120',...
% 'yRecon_use_within_model_ts_v120_v300',...
% 'yRecon_use_within_model_ts_v300_inf'

% Baseline fields used on x-axis.
baseline_fields = {'yRecon_use_all'};

% Compared fields used on y-axis.
comparation_fields = { ...
'yRecon_use_across',...
'yRecon_use_within',...
'yRecon_use_feedforward',...
'yRecon_use_feedback'};


% Metrics to compare.
%
% Available from plot_contrast_effect.m:
% dHL
%   high - low, stored in result as delta_HL
%
% CMI
%   (high - low) / (abs(high) + abs(low))
%
% Examples:
% metrics = {'CMI'};
% metrics = {'dHL'};
% metrics = {'dHL', 'CMI'};
metrics = {'CMI'};

% Manual display/file labels for the model groups, in groupd order.
% These names do not select neurons and are not read from or compared with
% any name field in contrast_effect_result. Repeated area names are allowed.
group_names = {'V1', 'MT'};

% Save options.
save_fig = true;
save_png = true;
save_matlab_fig = false;
close_after_save = true;

% Summary save option.
save_comparison_summary = true;

% Save each panel summary into a subfolder under io_dir.
% This keeps summary mats separate from effect mats and figures.
save_summary_in_subfolder = true;
comparison_summary_folder_name = 'contrast_effect_comparison_summary';

% Save raw per-unit values inside summary.
% Recommended true for later debugging and flexible cross-session summary.
save_unit_values_in_summary = true;

% Plot regression lines on scatter panels.
plot_regression_line = true;

% Which regression to draw on the figure.
% Options:
% 'all'     : draw regression_all only
% 'central' : draw regression_central only
% 'both'    : draw both; all = solid, central = dotted
%
% Both regression_all and regression_central are always saved in summary,
% independent of this display option.
regression_mode_for_plot = 'central';

regression_line_width = 1.5;

% Figure options.
figure_visible = 'on';
png_dpi = 300;

% Scatter style, matched to plot_reconstruction_R2.m style.
marker_size = 30;
use_marker_alpha = true;
marker_alpha = 0.65;

% Group colors, in the same order as group_names/groupd.
group_colors_base = [ ...
    0.0000, 0.4470, 0.7410; ...
    0.8500, 0.3250, 0.0980];

% Reference line style.
reference_line_width = 1.0;
zero_line_width = 1.0;
reference_line_style = 'k--';

% Panel layout.
max_panel_cols = 4;
fig_base_width_per_col = 470;
fig_base_height_per_row = 420;
fig_min_width = 900;
fig_min_height = 600;

% Broken-axis display for comparison scatter.
% This does not delete or hide data points.
% It transforms display coordinates so that the central region is linear
% and extreme tails are compressed into short display regions.
%
% false: full linear axis.
% true : use broken-axis display if extreme values stretch the full range.
use_broken_axis_display = true;

% Percentile of abs(metric values) used to start the broken-axis tail.
% 98 means the central 98% by absolute value remains linear.
break_start_prctile = 93.0;

% Trigger based on raw_abs_max / break_start.
% 1 always applies broken-axis display when use_broken_axis_display is true
% and raw_abs_max is larger than break_start.
% Larger values only use broken-axis display when extremes are severe.
broken_axis_trigger_ratio = 1;

% Fraction of the central linear half-axis used to display each compressed
% tail. Larger values make the extreme tails occupy more visible space.
tail_display_frac = 0.08;

% Visual gap between the central linear region and each compressed tail.
break_gap_frac = 0.03;

% Minimum display slope in compressed tail.
% 1.0 means tail is not compressed.
% 0.5 means tail distances are shown at half linear scale.
% 0.2 means tail distances are shown at 20% linear scale.
% Increase this if tail points look collapsed into vertical/horizontal lines.
min_tail_display_slope = 0.001;

% Keep x/y limits identical and symmetric around zero.
% For signed contrast metrics, true is often useful.
% To exactly follow your current size_effect_comparation style, use false.
force_symmetric_broken_axis = false;

% Add a suffix to output figure names when broken-axis display is actually
% used. This prevents broken-axis figures from overwriting full-range figures.
add_broken_axis_suffix_to_output = true;
broken_axis_file_suffix = '_brokenaxis';

% Draw small slash marks at the broken parts of the x and y axes.
draw_broken_axis_marks = true;
break_mark_line_width = 1.2;

%% ----------------------- Main setup -----------------------

scriptDir = fileparts(mfilename('fullpath'));
if isempty(scriptDir)
    scriptDir = pwd;
end

baseline_fields = normalize_field_list_local(baseline_fields, 'baseline_fields');
comparation_fields = normalize_field_list_local(comparation_fields, 'comparation_fields');
metrics = normalize_metric_list_local(metrics);
regression_mode_for_plot = validate_regression_mode_local(regression_mode_for_plot);

group_names_this = normalize_manual_group_names_local(group_names);
[group_display_names, group_file_tags, group_mapping_file_tag] = ...
    build_group_labels_local(group_names_this);

safe_data_content = sanitize_filename_local(data_content);

time_parameter_file_tag = build_time_parameter_file_tag_local( ...
    analysis_window, sliding_step);

io_dir = resolve_contrast_effect_io_dir_local(data_content, model_mode, runIdx, scriptDir);

if ~exist(io_dir, 'dir')
    error('Input/output folder does not exist:\n  %s', io_dir);
end

if save_summary_in_subfolder
    summary_dir = fullfile(io_dir, comparison_summary_folder_name);
else
    summary_dir = io_dir;
end

if save_comparison_summary && ~exist(summary_dir, 'dir')
    mkdir(summary_dir);
end

fprintf('Data content: %s\n', data_content);
fprintf('Model mode: %s\n', model_mode);
fprintf('analysis_window = %.12g s\n', analysis_window);
fprintf('sliding_step    = %.12g s\n', sliding_step);
fprintf('Time parameter file tag: %s\n', time_parameter_file_tag);
fprintf('Group-area mapping file tag: %s\n', group_mapping_file_tag);
fprintf('Input/output folder:\n  %s\n', io_dir);

fprintf('Manual group-area labels:\n');
disp(group_display_names(:));

if save_comparison_summary
    fprintf('Comparison summary folder:\n  %s\n', summary_dir);
end

fprintf('\nBaseline fields:\n');
disp(baseline_fields(:));

fprintf('Compared fields:\n');
disp(comparation_fields(:));

fprintf('Metrics:\n');
disp(metrics(:));

fprintf('Regression mode for plot: %s\n', regression_mode_for_plot);
fprintf('Both regression_all and regression_central will be saved in summary.\n');

%% ----------------------- Locate contrast effect result files -----------------------

all_fields = unique([baseline_fields, comparation_fields], 'stable');

field_files = struct();

for f = 1:numel(all_fields)
    field_name = all_fields{f};
    key = field_to_key_local(field_name);

    field_files.(key) = locate_contrast_effect_files_for_field_local( ...
        io_dir, safe_data_content, model_mode, field_name, ...
        group_mapping_file_tag, time_parameter_file_tag);

    fprintf('\nLocated contrast effect files for field %s:\n', field_name);
    for w = 1:numel(field_files.(key))
        fprintf('  window %d: %s\n', w, field_files.(key)(w).file);
    end
end

reference_field = all_fields{1};
reference_key = field_to_key_local(reference_field);
reference_file_entries = field_files.(reference_key);
nWindows = numel(reference_file_entries);

if nWindows < 1
    error('No contrast effect result files found for reference field %s.', reference_field);
end

for f = 2:numel(all_fields)
    this_field = all_fields{f};
    this_key = field_to_key_local(this_field);
    this_entries = field_files.(this_key);

    if numel(this_entries) ~= nWindows
        error(['Number of time-window files differs between %s and %s. ', ...
            '%s has %d files, %s has %d files.'], ...
            reference_field, this_field, reference_field, nWindows, ...
            this_field, numel(this_entries));
    end

    for w = 1:nWindows
        if ~strcmp(reference_file_entries(w).window_suffix, ...
                this_entries(w).window_suffix)
            error(['Window suffix mismatch at window %d between %s and %s. ', ...
                'Expected %s, got %s.'], ...
                w, reference_field, this_field, ...
                reference_file_entries(w).window_suffix, ...
                this_entries(w).window_suffix);
        end
    end
end

fprintf('\nNumber of windows/files to compare: %d\n', nWindows);

%% ----------------------- Build abbreviated output filename prefix -----------------------

base_fields_tag = join_short_field_names_for_filename_local(baseline_fields);
compared_fields_tag = join_short_field_names_for_filename_local(comparation_fields);
mode_file_tag = model_mode_to_file_tag_local(model_mode);

output_prefix = sprintf('%s_contrast_b-%s_c-%s', ...
    safe_data_content, base_fields_tag, compared_fields_tag);

%% ----------------------- Process each time window separately -----------------------

for windowIdx = 1:nWindows

    fprintf('\n============================================================\n');
    fprintf('Processing comparison window %d/%d\n', windowIdx, nWindows);
    fprintf('============================================================\n');

    %% ----------------------- Load all required results for this window -----------------------

    result_map = struct();

    for f = 1:numel(all_fields)
        field_name = all_fields{f};
        key = field_to_key_local(field_name);
        file_entry = field_files.(key)(windowIdx);

        fprintf('\nLoading contrast effect result for field %s:\n  %s\n', ...
            field_name, file_entry.file);

        result_map.(key) = load_contrast_effect_result_local( ...
            file_entry.file, field_name, ...
            analysis_window, sliding_step, file_entry.window_suffix);
    end

    %% ----------------------- Validate shared metadata across all fields -----------------------

    reference_result = result_map.(field_to_key_local(reference_field));

    nUnits = reference_result.nUnits;
    groupd = reference_result.groupd(:)';
    validate_groupd_local(groupd, nUnits);
    nGroups = numel(groupd);

    if numel(group_names_this) ~= nGroups
        error(['group_names contains %d labels, but loaded groupd contains ', ...
            '%d model groups.'], numel(group_names_this), nGroups);
    end

    group_colors = resolve_group_colors_local(group_colors_base, nGroups);

    for f = 2:numel(all_fields)
        this_field = all_fields{f};
        this_result = result_map.(field_to_key_local(this_field));

        validate_compatible_results_local( ...
            reference_result, this_result, ...
            reference_field, this_field, ...
            data_content, model_mode);
    end

    group_row_ranges = build_group_row_ranges_local(groupd);

    window_suffix = reference_file_entries(windowIdx).window_suffix;
    window_label = get_window_label_from_result_local( ...
        reference_result, windowIdx, nWindows, window_suffix);

    fprintf('\nWindow label: %s\n', window_label);
    fprintf('Window suffix: %s\n', window_suffix);

    %% ----------------------- Plot one figure per metric -----------------------

    nBase = numel(baseline_fields);
    nComp = numel(comparation_fields);
    nPanels = nBase * nComp;

    [nRows, nCols] = choose_panel_layout_local(nPanels, max_panel_cols);

    figWidth = max(fig_min_width, fig_base_width_per_col * nCols);
    figHeight = max(fig_min_height, fig_base_height_per_row * nRows);

    for m = 1:numel(metrics)
        metric_name = metrics{m};
        result_metric_field = metric_name_to_result_field_local(metric_name);
        metric_file_tag = metric_to_file_tag_local(metric_name);
        any_broken_axis_this_metric = false;

        fprintf('\n------------------------------------------------------------\n');
        fprintf('Plotting metric %d/%d: %s\n', m, numel(metrics), metric_name);
        fprintf('Reading result field: %s\n', result_metric_field);
        fprintf('------------------------------------------------------------\n');

        hfig = figure( ...
            'Color', 'w', ...
            'Visible', figure_visible, ...
            'Name', sprintf('Contrast effect comparation: %s, %s', ...
            metric_name, window_label), ...
            'Position', [100 100 figWidth figHeight]);

        tl = tiledlayout(hfig, nRows, nCols, ...
            'TileSpacing', 'compact', ...
            'Padding', 'compact');

        panel_idx = 0;
        legend_handles = gobjects(nGroups, 1);

        for b = 1:nBase
            baseline_field = baseline_fields{b};
            baseline_key = field_to_key_local(baseline_field);
            baseline_result = result_map.(baseline_key);
            baseline_file_entry = field_files.(baseline_key)(windowIdx);

            for c = 1:nComp
                comparation_field = comparation_fields{c};
                comparation_key = field_to_key_local(comparation_field);
                comparation_result = result_map.(comparation_key);
                comparation_file_entry = field_files.(comparation_key)(windowIdx);

                panel_idx = panel_idx + 1;
                ax = nexttile(tl, panel_idx);
                hold(ax, 'on');

                if ~isfield(baseline_result, result_metric_field)
                    error('Metric result field %s not found in baseline field result %s.', ...
                        result_metric_field, baseline_field);
                end

                if ~isfield(comparation_result, result_metric_field)
                    error('Metric result field %s not found in compared field result %s.', ...
                        result_metric_field, comparation_field);
                end

                x_all = baseline_result.(result_metric_field);
                y_all = comparation_result.(result_metric_field);

                x_all = x_all(:);
                y_all = y_all(:);

                if numel(x_all) ~= nUnits || numel(y_all) ~= nUnits
                    error(['Metric vector length mismatch for %s vs %s, metric %s. ', ...
                        'Expected %d units, got %d and %d.'], ...
                        baseline_field, comparation_field, metric_name, ...
                        nUnits, numel(x_all), numel(y_all));
                end

                valid_all = isfinite(x_all) & isfinite(y_all);
                all_x = x_all(valid_all);
                all_y = y_all(valid_all);

                axis_info = compute_symmetric_broken_axis_info_local( ...
                    all_x, all_y, ...
                    use_broken_axis_display, ...
                    break_start_prctile, ...
                    broken_axis_trigger_ratio, ...
                    tail_display_frac, ...
                    break_gap_frac, ...
                    min_tail_display_slope, ...
                    force_symmetric_broken_axis);

                any_broken_axis_this_metric = ...
                    any_broken_axis_this_metric || axis_info.use_broken_axis;

                % Build and save one panel summary.
                if save_comparison_summary
                    comparison_summary = build_contrast_comparison_summary_local( ...
                        baseline_result, comparation_result, ...
                        baseline_file_entry.file, comparation_file_entry.file, ...
                        data_content, model_mode, runIdx, ...
                        metric_name, result_metric_field, ...
                        baseline_field, comparation_field, ...
                        x_all, y_all, ...
                        groupd, group_names_this, group_row_ranges, ...
                        axis_info, ...
                        save_unit_values_in_summary);

                    summary_base_name = sprintf('%s_contrast_compare_summary_%s_vs_%s_%s_%s_%s%s', ...
                        safe_data_content, ...
                        analysis_field_to_file_tag_local(baseline_field), ...
                        analysis_field_to_file_tag_local(comparation_field), ...
                        metric_file_tag, ...
                        mode_file_tag, ...
                        group_mapping_file_tag, ...
                        window_suffix);

                    summary_file = fullfile(summary_dir, sprintf('%s.mat', summary_base_name));
                    save(summary_file, 'comparison_summary', '-v7.3');

                    fprintf('Saved comparison summary:\n  %s\n', summary_file);
                end

                % Diagonal reference line y = x.
                plot_diagonal_reference_line_local( ...
                    ax, axis_info, reference_line_style, reference_line_width);

                % Zero reference lines x = 0 and y = 0.
                zero_plot = broken_axis_transform_signed_local(0, axis_info);

                plot(ax, [zero_plot zero_plot], ...
                    [axis_info.plot_axis_min axis_info.plot_axis_max], ...
                    reference_line_style, ...
                    'LineWidth', zero_line_width, ...
                    'HandleVisibility', 'off');

                plot(ax, [axis_info.plot_axis_min axis_info.plot_axis_max], ...
                    [zero_plot zero_plot], ...
                    reference_line_style, ...
                    'LineWidth', zero_line_width, ...
                    'HandleVisibility', 'off');

                for g = 1:nGroups
                    rows = group_row_ranges{g};

                    x = x_all(rows);
                    y = y_all(rows);

                    valid = isfinite(x) & isfinite(y);
                    x = x(valid);
                    y = y(valid);

                    if isempty(x)
                        continue;
                    end

                    x_plot = broken_axis_transform_signed_local(x, axis_info);
                    y_plot = broken_axis_transform_signed_local(y, axis_info);

                    thisColor = group_colors(g, :);

                    if use_marker_alpha
                        h = scatter(ax, x_plot, y_plot, marker_size, ...
                            'filled', ...
                            'MarkerFaceColor', thisColor, ...
                            'MarkerEdgeColor', thisColor, ...
                            'MarkerFaceAlpha', marker_alpha, ...
                            'MarkerEdgeAlpha', marker_alpha, ...
                            'DisplayName', group_display_names{g});
                    else
                        h = scatter(ax, x_plot, y_plot, marker_size, ...
                            'filled', ...
                            'MarkerFaceColor', thisColor, ...
                            'MarkerEdgeColor', thisColor, ...
                            'DisplayName', group_display_names{g});
                    end

                    if ~isgraphics(legend_handles(g))
                        legend_handles(g) = h;
                    end

                    if plot_regression_line
                        plot_group_regression_lines_local( ...
                            ax, x, y, axis_info, ...
                            regression_mode_for_plot, ...
                            thisColor, regression_line_width);
                    end
                end

                axis(ax, 'square');
                xlim(ax, [axis_info.plot_axis_min axis_info.plot_axis_max]);
                ylim(ax, [axis_info.plot_axis_min axis_info.plot_axis_max]);

                xticks(ax, axis_info.plot_ticks);
                yticks(ax, axis_info.plot_ticks);
                xticklabels(ax, axis_info.tick_labels);
                yticklabels(ax, axis_info.tick_labels);

                xlabel(ax, sprintf('%s %s', ...
                    baseline_field, metric_label_local(metric_name)), ...
                    'Interpreter', 'none');

                ylabel(ax, sprintf('%s %s', ...
                    comparation_field, metric_label_local(metric_name)), ...
                    'Interpreter', 'none');

                panel_title = sprintf('base: %s\ncompared: %s', ...
                    baseline_field, comparation_field);

                title(ax, panel_title, 'Interpreter', 'none');

                clean_axis_local(ax);

                if axis_info.use_broken_axis && draw_broken_axis_marks
                    draw_axis_break_marks_signed_local(ax, axis_info, ...
                        break_mark_line_width);
                end
            end
        end

        sgtitle(tl, sprintf('%s | %s | %s | %s | neuron-wise contrast effect comparation', ...
            data_content, model_mode, metric_name, window_label), ...
            'Interpreter', 'none');

        valid_legend_mask = isgraphics(legend_handles);
        valid_legend_handles = legend_handles(valid_legend_mask);

        if ~isempty(valid_legend_handles)
            legend_names = group_display_names(valid_legend_mask);

            lgd = legend(valid_legend_handles, legend_names, ...
                'Interpreter', 'none', ...
                'Location', 'eastoutside', ...
                'Box', 'off');

            lgd.Layout.Tile = 'east';
        end

        output_suffix = ['_', group_mapping_file_tag, window_suffix];

        if add_broken_axis_suffix_to_output && any_broken_axis_this_metric
            output_suffix = [output_suffix, broken_axis_file_suffix];
        end

        output_base_name = sprintf('%s_%s_%s%s', ...
            output_prefix, metric_file_tag, mode_file_tag, output_suffix);

        if save_fig
            save_current_figure_local(hfig, io_dir, output_base_name, ...
                save_png, save_matlab_fig, png_dpi);
        end

        if close_after_save
            close(hfig);
        end
    end
end

fprintf('\nDone.\n');

%% =========================================================================
% Local functions
% =========================================================================

function fields = normalize_field_list_local(fields, var_name)
if ischar(fields)
    fields = {fields};
elseif isstring(fields)
    fields = cellstr(fields(:))';
elseif iscell(fields)
    fields = reshape(fields, 1, []);

    for i = 1:numel(fields)
        if isstring(fields{i})
            fields{i} = char(fields{i});
        end

        if ~ischar(fields{i})
            error('%s{%d} must be a char or string.', var_name, i);
        end
    end
else
    error('%s must be a char, string, string array, or cell array.', var_name);
end

if isempty(fields)
    error('%s is empty.', var_name);
end

empty_mask = cellfun(@isempty, fields);

if any(empty_mask)
    error('%s contains empty entries.', var_name);
end

if numel(unique(fields, 'stable')) ~= numel(fields)
    warning('%s contains duplicate entries. Duplicates will be removed.', var_name);
    fields = unique(fields, 'stable');
    fields = reshape(fields, 1, []);
end
end

function metrics = normalize_metric_list_local(metrics)
metrics = normalize_field_list_local(metrics, 'metrics');

valid_metrics = {'dHL', 'CMI', 'CMI2'};

for i = 1:numel(metrics)
    if ~ismember(metrics{i}, valid_metrics)
        error('Unknown metric: %s. Valid metrics are dHL, CMI, and CMI2.', ...
            metrics{i});
    end
end
end

function mode = validate_regression_mode_local(mode)
if isstring(mode)
    mode = char(mode);
end

valid_modes = {'all', 'central', 'both'};

if ~ischar(mode) || ~ismember(mode, valid_modes)
    error('regression_mode_for_plot must be ''all'', ''central'', or ''both''.');
end
end

function io_dir = resolve_contrast_effect_io_dir_local(data_content, model_mode, runIdx, scriptDir)
switch model_mode
    case 'all_condition_model'
        baseDir = ['./FA_Dlag_', data_content];
        io_dir = fullfile(baseDir, 'mat_results', sprintf('run%03d', runIdx));

    case 'condition_specific_models'
        io_dir = scriptDir;

    otherwise
        error(['Unknown model_mode: %s. Expected all_condition_model ', ...
            'or condition_specific_models.'], model_mode);
end
end

function entries = locate_contrast_effect_files_for_field_local( ...
    io_dir, safe_data_content, model_mode, field_name, ...
    group_mapping_file_tag, time_parameter_file_tag)

safe_field = sanitize_filename_local(field_name);

base_name = sprintf('%s_%s_contrast_effect_%s_%s', ...
    safe_data_content, model_mode, safe_field, group_mapping_file_tag);

time_pattern = sprintf('%s%s_w*.mat', base_name, time_parameter_file_tag);
time_files = dir(fullfile(io_dir, time_pattern));

if ~isempty(time_files)
    entries = repmat(struct( ...
        'file', '', ...
        'window_suffix', '', ...
        'window_index', []), 1, numel(time_files));

    for i = 1:numel(time_files)
        fname = time_files(i).name;
        full_file = fullfile(io_dir, fname);

        [~, name_no_ext] = fileparts(fname);
        window_suffix = extract_window_suffix_from_name_local( ...
            name_no_ext, time_parameter_file_tag);

        window_index = extract_window_index_from_suffix_local(window_suffix);

        entries(i).file = full_file;
        entries(i).window_suffix = window_suffix;
        entries(i).window_index = window_index;
    end

    [~, order] = sort([entries.window_index]);
    entries = entries(order);
    return;
end

% Full-trial single-window filename: no time suffix, but the manual
% group-area mapping tag remains in base_name.
full_trial_file = fullfile(io_dir, sprintf('%s.mat', base_name));

if isfile(full_trial_file)
    entries = struct( ...
        'file', full_trial_file, ...
        'window_suffix', '', ...
        'window_index', 1);
    return;
end

error(['Contrast effect result file not found for field %s.\n', ...
    'Tried time-window pattern:\n  %s\n', ...
    'Tried full-trial single-window file:\n  %s'], ...
    field_name, fullfile(io_dir, time_pattern), full_trial_file);
end

function window_suffix = extract_window_suffix_from_name_local(name_no_ext, time_parameter_file_tag)
idx = strfind(name_no_ext, time_parameter_file_tag);

if isempty(idx)
    error('Could not find time parameter tag %s in filename %s.', ...
        time_parameter_file_tag, name_no_ext);
end

idx = idx(end);
window_suffix = name_no_ext(idx:end);
end

function window_index = extract_window_index_from_suffix_local(window_suffix)
tokens = regexp(window_suffix, '_w(\d+)$', 'tokens', 'once');

if isempty(tokens)
    error('Could not extract window index from suffix: %s', window_suffix);
end

window_index = str2double(tokens{1});

if ~isfinite(window_index) || window_index < 1
    error('Invalid window index in suffix: %s', window_suffix);
end
end

function result = load_contrast_effect_result_local( ...
    result_file, expected_field, ...
    analysis_window, sliding_step, expected_window_suffix)

S = load(result_file);

if ~isfield(S, 'contrast_effect_result')
    error('File does not contain contrast_effect_result:\n  %s', result_file);
end

result = S.contrast_effect_result;

% Robust alias support:
% The current plot_contrast_effect.m saves delta_HL.
% If a future version saves dHL directly, keep both readable.
if ~isfield(result, 'delta_HL') && isfield(result, 'dHL')
    result.delta_HL = result.dHL;
end

required_fields = { ...
    'data_content', ...
    'model_mode', ...
    'analysis_field', ...
    'nUnits', ...
    'groupd', ...
    'delta_HL', ...
    'CMI'};

for i = 1:numel(required_fields)
    if ~isfield(result, required_fields{i})
        error('contrast_effect_result in %s is missing field %s.', ...
            result_file, required_fields{i});
    end
end

if ~strcmp(result.analysis_field, expected_field)
    warning(['Loaded result file analysis_field is %s, but expected %s. ', ...
        'Continuing because file name matched expected field.'], ...
        result.analysis_field, expected_field);
end

validate_time_metadata_local( ...
    result, result_file, expected_field, ...
    analysis_window, sliding_step, expected_window_suffix);
end

function validate_time_metadata_local( ...
    result, result_file, expected_field, ...
    analysis_window, sliding_step, expected_window_suffix)

required_time_fields = { ...
    'analysis_window', ...
    'sliding_step', ...
    'nWindows', ...
    'time_window_index', ...
    'bin_start', ...
    'bin_end', ...
    'time_start', ...
    'time_end', ...
    'time_file_suffix', ...
    'is_full_trial_single_window'};

for i = 1:numel(required_time_fields)
    fn = required_time_fields{i};

    if ~isfield(result, fn)
        error(['Loaded contrast_effect_result for field %s does not contain ', ...
            'required time metadata field %s. File:\n  %s'], ...
            expected_field, fn, result_file);
    end
end

tol = 1e-10;

if abs(double(result.analysis_window) - analysis_window) > tol
    error(['analysis_window mismatch for field %s. File has %.12g, ', ...
        'script requested %.12g. File:\n  %s'], ...
        expected_field, double(result.analysis_window), analysis_window, result_file);
end

if abs(double(result.sliding_step) - sliding_step) > tol
    error(['sliding_step mismatch for field %s. File has %.12g, ', ...
        'script requested %.12g. File:\n  %s'], ...
        expected_field, double(result.sliding_step), sliding_step, result_file);
end

file_suffix_in_result = char(result.time_file_suffix);

if ~strcmp(file_suffix_in_result, expected_window_suffix)
    error(['time_file_suffix mismatch for field %s. File has %s, ', ...
        'expected %s. File:\n  %s'], ...
        expected_field, file_suffix_in_result, expected_window_suffix, result_file);
end
end

function validate_compatible_results_local( ...
    reference_result, this_result, reference_field, this_field, ...
    expected_data_content, expected_model_mode)

if ~strcmp(this_result.data_content, expected_data_content)
    error('Field %s data_content is %s, expected %s.', ...
        this_field, this_result.data_content, expected_data_content);
end

if ~strcmp(this_result.model_mode, expected_model_mode)
    error('Field %s model_mode is %s, expected %s.', ...
        this_field, this_result.model_mode, expected_model_mode);
end

if ~strcmp(reference_result.data_content, this_result.data_content)
    error('data_content mismatch between %s and %s.', ...
        reference_field, this_field);
end

if ~strcmp(reference_result.model_mode, this_result.model_mode)
    error('model_mode mismatch between %s and %s.', ...
        reference_field, this_field);
end

if reference_result.nUnits ~= this_result.nUnits
    error('nUnits mismatch between %s and %s: %d vs %d.', ...
        reference_field, this_field, reference_result.nUnits, this_result.nUnits);
end

if ~isequal(reference_result.groupd(:)', this_result.groupd(:)')
    error('groupd mismatch between %s and %s.', ...
        reference_field, this_field);
end

% These fields should match exactly within the same comparison window.
strict_compare_fields = { ...
    'runIdx', ...
    'stim_tag', ...
    'analysis_window', ...
    'sliding_step', ...
    'window_nbin', ...
    'step_nbin', ...
    'nWindows', ...
    'time_window_index', ...
    'bin_start', ...
    'bin_end', ...
    'time_start', ...
    'time_end', ...
    'time_file_suffix', ...
    'is_full_trial_single_window'};

for i = 1:numel(strict_compare_fields)
    fn = strict_compare_fields{i};

    if isfield(reference_result, fn) && isfield(this_result, fn)
        ref_val = reference_result.(fn);
        this_val = this_result.(fn);

        if ischar(ref_val) || isstring(ref_val)
            if ~strcmp(char(ref_val), char(this_val))
                error('%s mismatch between %s and %s.', ...
                    fn, reference_field, this_field);
            end

        elseif isnumeric(ref_val) || islogical(ref_val)
            if ~isequal(ref_val, this_val)
                error('%s mismatch between %s and %s.', ...
                    fn, reference_field, this_field);
            end
        end
    else
        error('%s is missing in one result between %s and %s.', ...
            fn, reference_field, this_field);
    end
end

% These fields are expected to be the same, but minor differences may not
% invalidate plotting.
optional_warning_fields = { ...
    'low_condition_indices', ...
    'high_condition_indices', ...
    'n_low_trials', ...
    'n_high_trials', ...
    'response_per_trial', ...
    'contrast_grouping_rule', ...
    'binsize', ...
    'nbin'};

for i = 1:numel(optional_warning_fields)
    fn = optional_warning_fields{i};

    if isfield(reference_result, fn) && isfield(this_result, fn)
        ref_val = reference_result.(fn);
        this_val = this_result.(fn);

        if ~values_equal_for_warning_local(ref_val, this_val)
            warning('%s differs between %s and %s.', ...
                fn, reference_field, this_field);
        end
    end
end
end

function tf = values_equal_for_warning_local(a, b)
try
    if ischar(a) || isstring(a) || ischar(b) || isstring(b)
        tf = strcmp(char(a), char(b));
    else
        tf = isequaln(a, b);
    end
catch
    tf = false;
end
end

function label = get_window_label_from_result_local(result, windowIdx, nWindows, window_suffix)
if isfield(result, 'time_window_label') && ~isempty(result.time_window_label)
    label = char(result.time_window_label);
    return;
end

if isempty(window_suffix)
    if isfield(result, 'is_full_trial_single_window') && result.is_full_trial_single_window
        label = sprintf('full-trial single window, window %d/%d', windowIdx, nWindows);
    else
        label = sprintf('window %d/%d', windowIdx, nWindows);
    end
else
    label = sprintf('window %d/%d, %s', windowIdx, nWindows, window_suffix);
end
end

function tag = build_time_parameter_file_tag_local(analysis_window, sliding_step)
if ~isnumeric(analysis_window) || ~isscalar(analysis_window) || ...
        ~isfinite(analysis_window) || analysis_window <= 0
    error('analysis_window must be a finite positive scalar in seconds.');
end

if ~isnumeric(sliding_step) || ~isscalar(sliding_step) || ...
        ~isfinite(sliding_step) || sliding_step <= 0
    error('sliding_step must be a finite positive scalar in seconds.');
end

tag = sprintf('_wn%s_st%s', ...
    format_seconds_for_filename_local(analysis_window), ...
    format_seconds_for_filename_local(sliding_step));
end

function s = format_seconds_for_filename_local(x)
s = sprintf('%.12g', x);
s = strrep(s, '.', '_');
s = strrep(s, '-', 'm');
s = regexprep(s, '[^a-zA-Z0-9_]', '_');
s = regexprep(s, '_+', '_');
end

function result_field = metric_name_to_result_field_local(metric_name)
switch metric_name
    case 'dHL'
        result_field = 'delta_HL';

    case 'CMI'
        result_field = 'CMI';

    case 'CMI2'
        result_field = 'CMI2';

    otherwise
        error('Unknown metric name: %s.', metric_name);
end
end

function group_names = normalize_manual_group_names_local(group_names)
if isempty(group_names)
    error(['group_names must be specified manually. It is used only for ', ...
        'display and file naming.']);
end

if ischar(group_names)
    group_names = {group_names};
elseif isstring(group_names)
    group_names = cellstr(group_names(:))';
elseif iscell(group_names)
    group_names = reshape(group_names, 1, []);
else
    error('group_names must be a char, string array, or cell array.');
end

for g = 1:numel(group_names)
    if isstring(group_names{g}) && isscalar(group_names{g})
        group_names{g} = char(group_names{g});
    end

    if ~ischar(group_names{g})
        error('group_names{%d} must be a char or scalar string.', g);
    end

    group_names{g} = strtrim(group_names{g});

    if isempty(group_names{g})
        error('group_names{%d} is empty.', g);
    end
end
end

function [group_display_names, group_file_tags, group_mapping_file_tag] = ...
    build_group_labels_local(group_names)

nGroups = numel(group_names);
group_display_names = cell(1, nGroups);
group_file_tags = cell(1, nGroups);

for g = 1:nGroups
    group_display_names{g} = sprintf('Group %d: %s', g, group_names{g});
    group_file_tags{g} = sprintf('G%02d_%s', ...
        g, sanitize_filename_local(group_names{g}));
end

group_mapping_file_tag = strjoin(group_file_tags, '_');
end

function group_colors = resolve_group_colors_local(group_colors_base, nGroups)
if size(group_colors_base, 1) < nGroups
    warning(['group_colors_base has fewer rows than number of groups. ', ...
        'Extra groups will be plotted in black.']);
end

group_colors = zeros(nGroups, 3);

for g = 1:nGroups
    if g <= size(group_colors_base, 1)
        group_colors(g, :) = group_colors_base(g, :);
    else
        group_colors(g, :) = [0, 0, 0];
    end
end
end

function validate_groupd_local(groupd, nUnits)
if isempty(groupd) || ~isnumeric(groupd) || ...
        any(~isfinite(groupd)) || any(groupd <= 0) || ...
        any(groupd ~= round(groupd))
    error('Loaded groupd must contain finite positive integers.');
end

if ~isnumeric(nUnits) || ~isscalar(nUnits) || ...
        ~isfinite(nUnits) || nUnits < 1 || nUnits ~= round(nUnits)
    error('Loaded nUnits must be a finite positive integer.');
end

if sum(groupd) ~= nUnits
    error('sum(groupd) = %d, but loaded nUnits = %d.', sum(groupd), nUnits);
end
end

function group_row_ranges = build_group_row_ranges_local(groupd)
groupd = groupd(:)';
nGroups = numel(groupd);

group_row_ranges = cell(1, nGroups);

row_start = 1;

for g = 1:nGroups
    row_end = row_start + groupd(g) - 1;
    group_row_ranges{g} = row_start:row_end;
    row_start = row_end + 1;
end
end

function comparison_summary = build_contrast_comparison_summary_local( ...
    baseline_result, comparation_result, ...
    baseline_result_file, comparation_result_file, ...
    data_content, model_mode, runIdx, ...
    metric_name, result_metric_field, ...
    baseline_field, comparation_field, ...
    x_all, y_all, ...
    groupd, group_names_this, group_row_ranges, ...
    axis_info, ...
    save_unit_values)

comparison_summary = struct();

[group_display_names, group_file_tags, group_mapping_file_tag] = ...
    build_group_labels_local(group_names_this);

comparison_summary.effect_type = 'contrast';
comparison_summary.summary_type = 'field_comparison_panel';
comparison_summary.generated_by = 'contrast_effect_comparation.m';

comparison_summary.data_content = data_content;
comparison_summary.model_mode = model_mode;
comparison_summary.runIdx = runIdx;

if isfield(baseline_result, 'stim_tag')
    comparison_summary.stim_tag = baseline_result.stim_tag;
end

comparison_summary.metric_name = metric_name;
comparison_summary.result_metric_field = result_metric_field;
comparison_summary.metric_label = metric_label_local(metric_name);

comparison_summary.baseline_field = baseline_field;
comparison_summary.comparation_field = comparation_field;

comparison_summary.baseline_result_file = baseline_result_file;
comparison_summary.comparation_result_file = comparation_result_file;

comparison_summary.delta_definition = 'comparation_metric - baseline_metric';
comparison_summary.base_sign_split_rule = ...
    'positive_base uses baseline metric >= 0; negative_base uses baseline metric < 0';

comparison_summary.regression_all_rule = ...
    'regression_all uses all units with finite baseline and compared metric values';

comparison_summary.regression_central_rule = ...
    ['regression_central uses finite units with abs(baseline metric) <= break_start ', ...
    'and abs(compared metric) <= break_start when broken-axis display is used; ', ...
    'if broken-axis display is not used, central equals all valid units'];

if isfield(baseline_result, 'contrast_grouping_rule')
    comparison_summary.contrast_grouping_rule = baseline_result.contrast_grouping_rule;
end

if isfield(baseline_result, 'low_condition_indices')
    comparison_summary.low_condition_indices = baseline_result.low_condition_indices;
end

if isfield(baseline_result, 'high_condition_indices')
    comparison_summary.high_condition_indices = baseline_result.high_condition_indices;
end

if isfield(baseline_result, 'n_low_trials')
    comparison_summary.n_low_trials = baseline_result.n_low_trials;
end

if isfield(baseline_result, 'n_high_trials')
    comparison_summary.n_high_trials = baseline_result.n_high_trials;
end

% Time metadata: all results are assumed to be generated by the new program.
comparison_summary.analysis_window = baseline_result.analysis_window;
comparison_summary.sliding_step = baseline_result.sliding_step;
comparison_summary.nWindows = baseline_result.nWindows;
comparison_summary.time_window_index = baseline_result.time_window_index;
comparison_summary.bin_start = baseline_result.bin_start;
comparison_summary.bin_end = baseline_result.bin_end;
comparison_summary.time_start = baseline_result.time_start;
comparison_summary.time_end = baseline_result.time_end;
comparison_summary.time_file_suffix = baseline_result.time_file_suffix;
comparison_summary.is_full_trial_single_window = baseline_result.is_full_trial_single_window;

if isfield(baseline_result, 'binsize')
    comparison_summary.binsize = baseline_result.binsize;
end

if isfield(baseline_result, 'nbin')
    comparison_summary.nbin = baseline_result.nbin;
end

if isfield(baseline_result, 'window_nbin')
    comparison_summary.window_nbin = baseline_result.window_nbin;
end

if isfield(baseline_result, 'step_nbin')
    comparison_summary.step_nbin = baseline_result.step_nbin;
end

comparison_summary.axis_info_for_central_regression = axis_info;
comparison_summary.central_break_start = axis_info.break_start;
comparison_summary.central_uses_broken_axis = axis_info.use_broken_axis;

comparison_summary.nUnits = numel(x_all);
comparison_summary.groupd = groupd;
comparison_summary.group_names = group_names_this;
comparison_summary.group_display_names = group_display_names;
comparison_summary.group_file_tags = group_file_tags;
comparison_summary.group_mapping_file_tag = group_mapping_file_tag;
comparison_summary.group_label_source = 'manual group_names parameter';

valid_all = isfinite(x_all) & isfinite(y_all);
central_all = valid_all & compute_central_mask_local(x_all, y_all, axis_info);

comparison_summary.n_valid_units_all_groups = sum(valid_all);
comparison_summary.n_central_units_all_groups = sum(central_all);

comparison_summary.all_groups_regression_all = compute_linear_regression_local( ...
    x_all(valid_all), y_all(valid_all));

comparison_summary.all_groups_regression_central = compute_linear_regression_local( ...
    x_all(central_all), y_all(central_all));

all_delta = y_all(valid_all) - x_all(valid_all);
comparison_summary.all_groups_delta_stats = compute_delta_stats_local(all_delta);

nGroups = numel(groupd);

for g = 1:nGroups
    rows = group_row_ranges{g};
    rows = rows(:);

    x = x_all(rows);
    y = y_all(rows);

    valid = isfinite(x) & isfinite(y);
    central = valid & compute_central_mask_local(x, y, axis_info);

    x_valid = x(valid);
    y_valid = y(valid);
    unit_indices_valid = rows(valid);

    x_central = x(central);
    y_central = y(central);
    unit_indices_central = rows(central);

    delta_valid = y_valid - x_valid;

    comparison_summary.group(g).group_index = g;
    comparison_summary.group(g).group_name = group_names_this{g};
    comparison_summary.group(g).group_display_name = group_display_names{g};
    comparison_summary.group(g).group_file_tag = group_file_tags{g};
    comparison_summary.group(g).nUnits_total = numel(rows);
    comparison_summary.group(g).nUnits_valid = numel(x_valid);
    comparison_summary.group(g).nUnits_central = numel(x_central);
    comparison_summary.group(g).unit_indices_valid = unit_indices_valid(:)';
    comparison_summary.group(g).unit_indices_central = unit_indices_central(:)';

    comparison_summary.group(g).regression_all = compute_linear_regression_local(x_valid, y_valid);
    comparison_summary.group(g).regression_central = compute_linear_regression_local(x_central, y_central);

    % Backward-friendly alias: regression equals all-point regression.
    comparison_summary.group(g).regression = comparison_summary.group(g).regression_all;

    comparison_summary.group(g).delta_all = compute_delta_split_summary_local( ...
        x_valid, y_valid, unit_indices_valid, true(size(x_valid)));

    positive_mask = x_valid >= 0;
    negative_mask = x_valid < 0;

    comparison_summary.group(g).delta_by_base_sign.positive_base = ...
        compute_delta_split_summary_local(x_valid, y_valid, unit_indices_valid, positive_mask);

    comparison_summary.group(g).delta_by_base_sign.negative_base = ...
        compute_delta_split_summary_local(x_valid, y_valid, unit_indices_valid, negative_mask);

    if save_unit_values
        comparison_summary.group(g).baseline_values = x_valid;
        comparison_summary.group(g).comparation_values = y_valid;
        comparison_summary.group(g).delta_values = delta_valid;

        comparison_summary.group(g).baseline_values_central = x_central;
        comparison_summary.group(g).comparation_values_central = y_central;
        comparison_summary.group(g).central_mask_for_valid_units = ...
            ismember(unit_indices_valid, unit_indices_central);
    end
end
end

function central_mask = compute_central_mask_local(x, y, axis_info)
x = x(:);
y = y(:);

if ~axis_info.use_broken_axis
    central_mask = true(size(x));
    return;
end

central_mask = abs(x) <= axis_info.break_start & ...
    abs(y) <= axis_info.break_start;
end

function reg = compute_linear_regression_local(x, y)
x = x(:);
y = y(:);

valid = isfinite(x) & isfinite(y);
x = x(valid);
y = y(valid);

reg = struct();
reg.model = 'y = slope * x + intercept';
reg.n_valid = numel(x);
reg.is_valid = false;
reg.slope = NaN;
reg.intercept = NaN;
reg.R2 = NaN;
reg.SSE = NaN;
reg.SST = NaN;
reg.y_mean = NaN;
reg.x_min = NaN;
reg.x_max = NaN;
reg.y_min = NaN;
reg.y_max = NaN;

if numel(x) < 2
    reg.reason_invalid = 'fewer than 2 valid points';
    return;
end

if numel(unique(x)) < 2
    reg.reason_invalid = 'x has fewer than 2 unique values';
    return;
end

p = polyfit(x, y, 1);

slope = p(1);
intercept = p(2);

yhat = slope .* x + intercept;

SSE = sum((y - yhat).^2);
SST = sum((y - mean(y)).^2);

if SST > 0
    R2 = 1 - SSE / SST;
else
    R2 = NaN;
end

reg.is_valid = true;
reg.reason_invalid = '';
reg.slope = slope;
reg.intercept = intercept;
reg.R2 = R2;
reg.SSE = SSE;
reg.SST = SST;
reg.y_mean = mean(y);
reg.x_min = min(x);
reg.x_max = max(x);
reg.y_min = min(y);
reg.y_max = max(y);
end

function plot_group_regression_lines_local( ...
    ax, x, y, axis_info, regression_mode_for_plot, thisColor, regression_line_width)

valid = isfinite(x) & isfinite(y);
x = x(valid);
y = y(valid);

if isempty(x)
    return;
end

central_mask = compute_central_mask_local(x, y, axis_info);

switch regression_mode_for_plot
    case 'all'
        plot_one_regression_line_local(ax, x, y, axis_info, ...
            thisColor, '-', regression_line_width);

    case 'central'
        plot_one_regression_line_local(ax, x(central_mask), y(central_mask), axis_info, ...
            thisColor, '-', regression_line_width);

    case 'both'
        plot_one_regression_line_local(ax, x, y, axis_info, ...
            thisColor, '-', regression_line_width);

        plot_one_regression_line_local(ax, x(central_mask), y(central_mask), axis_info, ...
            thisColor, ':', regression_line_width + 0.5);

    otherwise
        error('Unknown regression_mode_for_plot: %s', regression_mode_for_plot);
end
end

function plot_one_regression_line_local(ax, x, y, axis_info, ...
    thisColor, line_style, line_width)

reg = compute_linear_regression_local(x, y);

if ~reg.is_valid
    return;
end

if reg.x_min == reg.x_max
    return;
end

x_line_raw = linspace(reg.x_min, reg.x_max, 100)';
y_line_raw = reg.slope .* x_line_raw + reg.intercept;

x_line_plot = broken_axis_transform_signed_local(x_line_raw, axis_info);
y_line_plot = broken_axis_transform_signed_local(y_line_raw, axis_info);

plot(ax, x_line_plot, y_line_plot, line_style, ...
    'Color', thisColor, ...
    'LineWidth', line_width, ...
    'HandleVisibility', 'off');
end

function split_summary = compute_delta_split_summary_local(x, y, unit_indices, mask)
x = x(:);
y = y(:);
unit_indices = unit_indices(:);
mask = mask(:);

if numel(mask) ~= numel(x)
    error('Mask length does not match x length.');
end

x_sel = x(mask);
y_sel = y(mask);
unit_sel = unit_indices(mask);

delta = y_sel - x_sel;

split_summary = struct();
split_summary.n = numel(delta);
split_summary.unit_indices = unit_sel(:)';
split_summary.stats = compute_delta_stats_local(delta);

if isempty(delta)
    split_summary.baseline_values = [];
    split_summary.comparation_values = [];
    split_summary.delta_values = [];
else
    split_summary.baseline_values = x_sel;
    split_summary.comparation_values = y_sel;
    split_summary.delta_values = delta;
end
end

function stats = compute_delta_stats_local(delta)
delta = delta(:);
delta = delta(isfinite(delta));

stats = struct();
stats.n = numel(delta);
stats.mean = NaN;
stats.median = NaN;
stats.std = NaN;
stats.sem = NaN;
stats.min = NaN;
stats.max = NaN;

if isempty(delta)
    return;
end

stats.mean = mean(delta, 'omitnan');
stats.median = median(delta, 'omitnan');
stats.std = std(delta, 0, 'omitnan');
stats.sem = stats.std ./ sqrt(numel(delta));
stats.min = min(delta);
stats.max = max(delta);
end

function axis_info = compute_symmetric_broken_axis_info_local( ...
    x, y, use_broken_axis_display, break_start_prctile, ...
    broken_axis_trigger_ratio, tail_display_frac, break_gap_frac, ...
    min_tail_display_slope, force_symmetric_broken_axis)
% Compute display transform information for a signed symmetric broken axis.
%
% This does not remove points. It maps raw metric values to plotting
% coordinates. Values within [-break_start, break_start] are shown linearly.
% Extreme positive and negative tails are compressed into short display
% regions.

if nargin < 3 || isempty(use_broken_axis_display)
    use_broken_axis_display = false;
end

if nargin < 4 || isempty(break_start_prctile)
    break_start_prctile = 98.0;
end

if nargin < 5 || isempty(broken_axis_trigger_ratio)
    broken_axis_trigger_ratio = 1;
end

if nargin < 6 || isempty(tail_display_frac)
    tail_display_frac = 0.08;
end

if nargin < 7 || isempty(break_gap_frac)
    break_gap_frac = 0.03;
end

if nargin < 8 || isempty(min_tail_display_slope)
    min_tail_display_slope = 0.25;
end

if nargin < 9 || isempty(force_symmetric_broken_axis)
    force_symmetric_broken_axis = true;
end

if ~(isscalar(min_tail_display_slope) && isfinite(min_tail_display_slope) ...
        && min_tail_display_slope > 0 && min_tail_display_slope <= 1)
    error('min_tail_display_slope must be a finite scalar in (0, 1].');
end

if ~(isscalar(break_start_prctile) && isfinite(break_start_prctile) ...
        && break_start_prctile > 0 && break_start_prctile < 100)
    error('break_start_prctile must be a scalar between 0 and 100.');
end

if ~(isscalar(broken_axis_trigger_ratio) && isfinite(broken_axis_trigger_ratio) ...
        && broken_axis_trigger_ratio >= 1)
    error('broken_axis_trigger_ratio must be a finite scalar >= 1.');
end

vals = [x(:); y(:)];
vals = vals(isfinite(vals));

axis_info = struct();
axis_info.use_broken_axis = false;
axis_info.break_start_prctile = break_start_prctile;
axis_info.broken_axis_trigger_ratio = broken_axis_trigger_ratio;
axis_info.tail_display_frac = tail_display_frac;
axis_info.break_gap_frac = break_gap_frac;
axis_info.min_tail_display_slope = min_tail_display_slope;
axis_info.raw_axis_min = NaN;
axis_info.raw_axis_max = NaN;
axis_info.raw_abs_max = NaN;
axis_info.break_start = NaN;
axis_info.break_end = NaN;
axis_info.tail_display_len = NaN;
axis_info.break_gap = NaN;
axis_info.plot_axis_min = NaN;
axis_info.plot_axis_max = NaN;
axis_info.plot_ticks = [];
axis_info.tick_labels = {};

if isempty(vals)
    axis_info.raw_axis_min = -1;
    axis_info.raw_axis_max = 1;
    axis_info.raw_abs_max = 1;
    axis_info.break_start = 1;
    axis_info.break_end = 1;
    axis_info.tail_display_len = 0;
    axis_info.break_gap = 0;
    axis_info.plot_axis_min = -1;
    axis_info.plot_axis_max = 1;
    [axis_info.plot_ticks, axis_info.tick_labels] = ...
        build_broken_axis_ticks_local(axis_info);
    return;
end

raw_min = min(vals);
raw_max = max(vals);
raw_abs_max = max(abs([raw_min, raw_max]));

if raw_abs_max <= 0 || ~isfinite(raw_abs_max)
    raw_abs_max = 1;
end

if force_symmetric_broken_axis
    raw_axis_min = -raw_abs_max;
    raw_axis_max = raw_abs_max;
else
    raw_axis_min = raw_min;
    raw_axis_max = raw_max;
end

abs_vals = abs(vals);
abs_vals = abs_vals(isfinite(abs_vals));

break_start = percentile_local(abs_vals, break_start_prctile);

if isempty(break_start) || ~isfinite(break_start) || break_start <= 0
    break_start = raw_abs_max;
end

use_broken_axis = use_broken_axis_display ...
    && raw_abs_max > break_start * broken_axis_trigger_ratio;

axis_info.raw_axis_min = raw_axis_min;
axis_info.raw_axis_max = raw_axis_max;
axis_info.raw_abs_max = raw_abs_max;

if ~use_broken_axis
    axis_info.break_start = raw_abs_max;
    axis_info.break_end = raw_abs_max;
    axis_info.tail_display_len = 0;
    axis_info.break_gap = 0;
    axis_info.plot_axis_min = raw_axis_min;
    axis_info.plot_axis_max = raw_axis_max;

    pad = 0.06 * max(eps, axis_info.plot_axis_max - axis_info.plot_axis_min);
    axis_info.plot_axis_min = axis_info.plot_axis_min - pad;
    axis_info.plot_axis_max = axis_info.plot_axis_max + pad;

    [axis_info.plot_ticks, axis_info.tick_labels] = ...
        build_broken_axis_ticks_local(axis_info);

    return;
end

high_abs_vals = abs_vals(abs_vals > break_start);
break_end = min(high_abs_vals);

if isempty(break_end) || ~isfinite(break_end) || break_end <= break_start
    break_end = break_start;
end

raw_tail_span = max(eps, raw_abs_max - break_end);
tail_display_len_from_frac = max(eps, break_start * tail_display_frac);
tail_display_len_from_slope = raw_tail_span * min_tail_display_slope;
tail_display_len = max(tail_display_len_from_frac, tail_display_len_from_slope);
break_gap = max(eps, break_start * break_gap_frac);

axis_info.use_broken_axis = true;
axis_info.break_start = break_start;
axis_info.break_end = break_end;
axis_info.tail_display_len = tail_display_len;
axis_info.break_gap = break_gap;

plot_min = broken_axis_transform_signed_local(raw_axis_min, axis_info);
plot_max = broken_axis_transform_signed_local(raw_axis_max, axis_info);

if force_symmetric_broken_axis
    plot_abs_max = max(abs([plot_min, plot_max]));
    plot_min = -plot_abs_max;
    plot_max = plot_abs_max;
end

pad = 0.06 * max(eps, plot_max - plot_min);

axis_info.plot_axis_min = plot_min - pad;
axis_info.plot_axis_max = plot_max + pad;

[axis_info.plot_ticks, axis_info.tick_labels] = ...
    build_broken_axis_ticks_local(axis_info);
end

function x_plot = broken_axis_transform_signed_local(x_raw, axis_info)
% Signed broken-axis transform.

x_plot = x_raw;

if ~axis_info.use_broken_axis
    return;
end

sgn = sign(x_raw);
ax = abs(x_raw);

break_start = axis_info.break_start;
break_end = axis_info.break_end;
raw_abs_max = axis_info.raw_abs_max;
tail_display_len = axis_info.tail_display_len;
break_gap = axis_info.break_gap;

x_plot_abs = ax;

gap_mask = ax > break_start & ax < break_end;
tail_mask = ax >= break_end;

if break_end > break_start
    x_plot_abs(gap_mask) = break_start ...
        + (ax(gap_mask) - break_start) ./ (break_end - break_start) .* break_gap;
else
    x_plot_abs(gap_mask) = break_start + break_gap;
end

if raw_abs_max > break_end
    x_plot_abs(tail_mask) = break_start + break_gap ...
        + (ax(tail_mask) - break_end) ./ (raw_abs_max - break_end) .* tail_display_len;
else
    x_plot_abs(tail_mask) = break_start + break_gap + tail_display_len;
end

x_plot = sgn .* x_plot_abs;
end

function [plot_ticks, tick_labels] = build_broken_axis_ticks_local(axis_info)
% Build ticks in plot coordinates with labels in raw coordinates.

if axis_info.use_broken_axis
    raw_ticks = choose_prebreak_ticks_signed_local(axis_info.break_start);
    raw_ticks = unique_with_tolerance_local(raw_ticks, 1e-10);
    plot_ticks = broken_axis_transform_signed_local(raw_ticks, axis_info);
    tick_labels = compose_numeric_tick_labels_local(raw_ticks);
else
    raw_ticks = choose_linear_ticks_symmetric_local( ...
        axis_info.raw_axis_min, axis_info.raw_axis_max);
    plot_ticks = raw_ticks;
    tick_labels = compose_numeric_tick_labels_local(raw_ticks);
end
end

function raw_ticks = choose_prebreak_ticks_signed_local(prebreak_abs_max)
if isempty(prebreak_abs_max) || ~isfinite(prebreak_abs_max) || prebreak_abs_max <= 0
    raw_ticks = 0;
    return;
end

target_intervals = 4;
rough_step = (2 * prebreak_abs_max) / target_intervals;
step = choose_nice_numeric_step_local(rough_step);

if step <= 0 || ~isfinite(step)
    raw_ticks = linspace(-prebreak_abs_max, prebreak_abs_max, 5);
    raw_ticks(abs(raw_ticks) < 1e-12) = 0;
    return;
end

max_tick = floor(prebreak_abs_max / step) * step;

if max_tick <= 0
    raw_ticks = [-prebreak_abs_max, 0, prebreak_abs_max];
else
    raw_ticks = -max_tick:step:max_tick;

    if ~any(abs(raw_ticks) < 1e-12)
        raw_ticks = sort([raw_ticks, 0]);
    end
end

raw_ticks(abs(raw_ticks) < 1e-12) = 0;
end

function step = choose_nice_numeric_step_local(rough_step)
if rough_step <= 0 || ~isfinite(rough_step)
    step = 1;
    return;
end

exponent = floor(log10(rough_step));
base = 10 ^ exponent;
candidates = [1 2 2.5 5 10] * base;
candidates = candidates(candidates >= rough_step);

if isempty(candidates)
    step = 10 * base;
else
    step = candidates(1);
end
end

function ticks = choose_linear_ticks_symmetric_local(axis_min, axis_max)
lim = max(abs([axis_min, axis_max]));

if lim <= 0 || ~isfinite(lim)
    lim = 1;
end

ticks = linspace(-lim, lim, 5);
end

function vals_unique = unique_with_tolerance_local(vals, tol)
vals = vals(:)';
vals_unique = [];

for i = 1:numel(vals)
    if isempty(vals_unique) || all(abs(vals(i) - vals_unique) > tol)
        vals_unique(end+1) = vals(i); %#ok<AGROW>
    end
end
end

function labels = compose_numeric_tick_labels_local(vals)
labels = cell(size(vals));

for i = 1:numel(vals)
    v = vals(i);

    if abs(v) < 1e-12
        v = 0;
    end

    if abs(v) >= 1000 || (abs(v) > 0 && abs(v) < 0.001)
        labels{i} = sprintf('%.2g', v);
    elseif abs(v - round(v)) < 1e-10
        labels{i} = sprintf('%d', round(v));
    else
        labels{i} = sprintf('%.3g', v);
    end
end
end

function plot_diagonal_reference_line_local(ax, axis_info, line_style, line_width)
if ~axis_info.use_broken_axis
    raw_ref = linspace(axis_info.raw_axis_min, axis_info.raw_axis_max, 300);
    plot_ref = broken_axis_transform_signed_local(raw_ref, axis_info);

    plot(ax, plot_ref, plot_ref, ...
        line_style, ...
        'LineWidth', line_width, ...
        'HandleVisibility', 'off');

    return;
end

lo = max(axis_info.raw_axis_min, -axis_info.break_start);
hi = min(axis_info.raw_axis_max, axis_info.break_start);

if hi > lo
    raw_ref = linspace(lo, hi, 150);
    plot_ref = broken_axis_transform_signed_local(raw_ref, axis_info);

    plot(ax, plot_ref, plot_ref, ...
        line_style, ...
        'LineWidth', line_width, ...
        'HandleVisibility', 'off');
end

if axis_info.raw_axis_max >= axis_info.break_end
    lo = max(axis_info.break_end, axis_info.raw_axis_min);
    hi = axis_info.raw_axis_max;

    if hi > lo
        raw_ref = linspace(lo, hi, 100);
        plot_ref = broken_axis_transform_signed_local(raw_ref, axis_info);

        plot(ax, plot_ref, plot_ref, ...
            line_style, ...
            'LineWidth', line_width, ...
            'HandleVisibility', 'off');
    end
end

if axis_info.raw_axis_min <= -axis_info.break_end
    lo = axis_info.raw_axis_min;
    hi = min(-axis_info.break_end, axis_info.raw_axis_max);

    if hi > lo
        raw_ref = linspace(lo, hi, 100);
        plot_ref = broken_axis_transform_signed_local(raw_ref, axis_info);

        plot(ax, plot_ref, plot_ref, ...
            line_style, ...
            'LineWidth', line_width, ...
            'HandleVisibility', 'off');
    end
end
end

function draw_axis_break_marks_signed_local(ax, axis_info, line_width)
if ~axis_info.use_broken_axis
    return;
end

if nargin < 3 || isempty(line_width)
    line_width = 1.2;
end

axes(ax); %#ok<LAXES>
hold(ax, 'on');

xLim = ax.XLim;
yLim = ax.YLim;

display_span = max(eps, max([diff(xLim), diff(yLim)]));

slash_dx = display_span * 0.012;
slash_dy = display_span * 0.025;
offset = display_span * 0.018;

x0 = xLim(1);
y0 = yLim(1);

break_center_abs = axis_info.break_start + axis_info.break_gap / 2;

x_centers = [];

if axis_info.raw_axis_max > axis_info.break_start
    x_centers(end+1) = break_center_abs; %#ok<AGROW>
end

if axis_info.raw_axis_min < -axis_info.break_start
    x_centers(end+1) = -break_center_abs; %#ok<AGROW>
end

for i = 1:numel(x_centers)
    xc = x_centers(i);

    plot(ax, ...
        [xc - slash_dx, xc + slash_dx], ...
        [y0 + slash_dy, y0 - slash_dy], ...
        'k-', 'LineWidth', line_width, 'Clipping', 'off', ...
        'HandleVisibility', 'off');

    plot(ax, ...
        [xc - slash_dx + offset, xc + slash_dx + offset], ...
        [y0 + slash_dy, y0 - slash_dy], ...
        'k-', 'LineWidth', line_width, 'Clipping', 'off', ...
        'HandleVisibility', 'off');
end

y_centers = [];

if axis_info.raw_axis_max > axis_info.break_start
    y_centers(end+1) = break_center_abs; %#ok<AGROW>
end

if axis_info.raw_axis_min < -axis_info.break_start
    y_centers(end+1) = -break_center_abs; %#ok<AGROW>
end

for i = 1:numel(y_centers)
    yc = y_centers(i);

    plot(ax, ...
        [x0 + slash_dx, x0 - slash_dx], ...
        [yc - slash_dy, yc + slash_dy], ...
        'k-', 'LineWidth', line_width, 'Clipping', 'off', ...
        'HandleVisibility', 'off');

    plot(ax, ...
        [x0 + slash_dx, x0 - slash_dx], ...
        [yc - slash_dy + offset, yc + slash_dy + offset], ...
        'k-', 'LineWidth', line_width, 'Clipping', 'off', ...
        'HandleVisibility', 'off');
end
end

function q = percentile_local(x, p)
x = x(:);
x = x(isfinite(x));

if isempty(x)
    q = NaN;
    return;
end

x = sort(x);
n = numel(x);

if n == 1
    q = x;
    return;
end

p = max(0, min(100, p));
pos = 1 + (n - 1) * p / 100;

lo = floor(pos);
hi = ceil(pos);

if lo == hi
    q = x(lo);
else
    w = pos - lo;
    q = (1 - w) * x(lo) + w * x(hi);
end
end

function label = metric_label_local(metric_name)
switch metric_name
    case 'dHL'
        label = 'dHL = H - L';

    case 'CMI'
        label = 'CMI';

    otherwise
        label = metric_name;
end
end

function key = field_to_key_local(field_name)
key = sanitize_filename_local(field_name);

if isempty(regexp(key(1), '[A-Za-z]', 'once'))
    key = ['field_', key];
end

key = matlab.lang.makeValidName(key);
end

function clean_axis_local(ax)
grid(ax, 'off');
box(ax, 'off');

set(ax, ...
    'TickDir', 'out', ...
    'LineWidth', 1, ...
    'FontSize', 11);
end

function save_current_figure_local(hfig, fig_out_dir, base_name, ...
    save_png, save_matlab_fig, png_dpi)

if ~exist(fig_out_dir, 'dir')
    mkdir(fig_out_dir);
end

if save_png
    png_file = fullfile(fig_out_dir, sprintf('%s.png', base_name));
    save_png_local(hfig, png_file, png_dpi);
    fprintf('\nSaved PNG figure:\n  %s\n', png_file);
end

if save_matlab_fig
    fig_file = fullfile(fig_out_dir, sprintf('%s.fig', base_name));
    savefig(hfig, fig_file);
    fprintf('Saved MATLAB figure:\n  %s\n', fig_file);
end
end

function save_png_local(fig, pngFile, dpi)
drawnow;

try
    if exist('exportgraphics', 'file') == 2
        exportgraphics(fig, pngFile, ...
            'Resolution', dpi, ...
            'BackgroundColor', 'white');
    else
        set(fig, 'PaperPositionMode', 'auto');
        print(fig, pngFile, '-dpng', sprintf('-r%d', dpi));
    end
catch
    warning('exportgraphics/print failed. Falling back to saveas.');
    saveas(fig, pngFile);
end
end

function name = sanitize_filename_local(name)
if isstring(name)
    name = char(name);
end

name = regexprep(name, '[^a-zA-Z0-9_\-]', '_');
name = regexprep(name, '_+', '_');
name = strtrim(name);

if isempty(name)
    name = 'unnamed';
end
end

function [nRows, nCols] = choose_panel_layout_local(nPanels, max_panel_cols)

if nPanels < 1
    error('nPanels must be >= 1.');
end

if nargin < 2 || isempty(max_panel_cols)
    max_panel_cols = 4;
end

max_panel_cols = max(1, round(max_panel_cols));

% Fill columns first, then add additional rows only when necessary.
nCols = min(nPanels, max_panel_cols);
nRows = ceil(nPanels / nCols);

end

function mode_tag = model_mode_to_file_tag_local(model_mode)
switch model_mode
    case 'all_condition_model'
        mode_tag = 'all';

    case 'condition_specific_models'
        mode_tag = 'csm';

    otherwise
        mode_tag = sanitize_filename_local(model_mode);
        mode_tag = compress_generic_name_local(mode_tag);
end
end

function metric_tag = metric_to_file_tag_local(metric_name)
switch metric_name
    case 'dHL'
        metric_tag = 'dHL';

    case 'CMI'
        metric_tag = 'CMI';

    otherwise
        metric_tag = sanitize_filename_local(metric_name);
        metric_tag = compress_generic_name_local(metric_tag);
end
end

function joined_name = join_short_field_names_for_filename_local(fields)
short_fields = cell(size(fields));

for i = 1:numel(fields)
    short_fields{i} = analysis_field_to_file_tag_local(fields{i});
end

joined_name = strjoin(short_fields, '-');
end

function field_tag = analysis_field_to_file_tag_local(field_name)
switch field_name
    case 'y'
        field_tag = 'y';

    case 'd'
        field_tag = 'd';

    case 'yRecon_use_all'
        field_tag = 'yall';

    case 'yRecon_use_all_no_d'
        field_tag = 'yallND';

    case 'yRecon_use_across'
        field_tag = 'yacr';

    case 'yRecon_use_across_no_d'
        field_tag = 'yacrND';

    case 'yRecon_use_within'
        field_tag = 'ywin';

    case 'yRecon_use_within_no_d'
        field_tag = 'ywinND';

    case 'yRecon_across_excl_within'
        field_tag = 'yacrXwin';

    case 'yRecon_within_excl_across'
        field_tag = 'ywinXacr';

    case 'yRecon_use_feedback'
        field_tag = 'yfb';

    case 'yRecon_feedback_excl_within_ff_ambiguous'
        field_tag = 'yfbXwinFFamb';

    case 'yRecon_feedback_excl_within'
        field_tag = 'yfbXwin';

    case 'yRecon_feedback_excl_ff_ambiguous'
        field_tag = 'yfbXFFamb';

    case 'yRecon_use_feedforward'
        field_tag = 'yff';

    case 'yRecon_feedforward_excl_within_fb_ambiguous'
        field_tag = 'yffXwinFBamb';

    case 'yRecon_feedforward_excl_within'
        field_tag = 'yffXwin';

    case 'yRecon_feedforward_excl_fb_ambiguous'
        field_tag = 'yffXFBamb';

    case 'yRecon_use_all_with_R'
        field_tag = 'yallR';

    case 'yRecon_use_across_with_R'
        field_tag = 'yacrR';

    case 'yRecon_use_within_with_R'
        field_tag = 'ywinR';

    case 'yRecon_across_excl_within_with_R'
        field_tag = 'yacrXwinR';

    case 'yRecon_within_excl_across_with_R'
        field_tag = 'ywinXacrR';

    case 'yRecon_use_all_keep_resid'
        field_tag = 'yallKR';

    case 'yRecon_use_across_keep_resid'
        field_tag = 'yacrKR';

    case 'yRecon_use_within_keep_resid'
        field_tag = 'ywinKR';

    case 'yRecon_across_excl_within_keep_resid'
        field_tag = 'yacrXwinKR';

    case 'yRecon_within_excl_across_keep_resid'
        field_tag = 'ywinXacrKR';

    otherwise
        field_tag = sanitize_filename_local(field_name);
        field_tag = strrep(field_tag, 'yRecon_', 'y');
        field_tag = strrep(field_tag, 'use_', '');
        field_tag = strrep(field_tag, 'across', 'acr');
        field_tag = strrep(field_tag, 'within', 'win');
        field_tag = strrep(field_tag, 'excl', 'X');
        field_tag = strrep(field_tag, 'condition', 'cond');
        field_tag = strrep(field_tag, 'feedback', 'fb');
        field_tag = strrep(field_tag, 'feedforward', 'ff');
        field_tag = strrep(field_tag, 'ambiguous', 'amb');
        field_tag = strrep(field_tag, 'resid', 'res');
        field_tag = compress_generic_name_local(field_tag);
end
end

function short_name = compress_generic_name_local(name)
short_name = name;

replacements = { ...
    'demean', 'dm'; ...
    'count', 'cnt'; ...
    'within', 'win'; ...
    'trial', 'tr'; ...
    'condition', 'cond'; ...
    'conditions', 'conds'; ...
    'across', 'acr'; ...
    'pooled', 'pool'; ...
    'reconstruction', 'recon'; ...
    'specific', 'spec'; ...
    'feedback', 'fb'; ...
    'feedforward', 'ff'; ...
    'ambiguous', 'amb'; ...
    'model', 'mdl'; ...
    'models', 'mdls'};

for i = 1:size(replacements, 1)
    short_name = strrep(short_name, replacements{i, 1}, replacements{i, 2});
end

short_name = regexprep(short_name, '_+', '_');
short_name = regexprep(short_name, '^_|_$', '');
end
