%% plot_timescale_svexp.m
% Fixed 0-400 ms + >400 overflow-axis revision: 2026-08-31
%
% Plot DLAG GP timescale against shared variance explained.
%
% Four panels are generated:
%   1) Across-area latents, group rGroups(1)
%   2) Across-area latents, group rGroups(2)
%   3) Within-area latents, group rGroups(1)
%   4) Within-area latents, group rGroups(2)
%
% Across-area panels:
%   x coordinate : delay from rGroups(1) to rGroups(2)
%   y coordinate : GP timescale
%   marker area  : group-specific shared variance explained
%   black circle : FF or FB latent
%   gray circle  : ambiguous latent
%
% Within-area panels:
%   x coordinate : one categorical position with deterministic horizontal
%                  spreading to reduce marker overlap
%   y coordinate : GP timescale
%   marker area  : group-specific shared variance explained
%   marker color : black
%
% Shared variance explained is read from:
%   varexp.indiv{groupIdx}
%
% The local latent order is assumed to be:
%   [across-area latents, within-area latents]
%
% GP timescales and delays are read from gp_params in bestmodel*.
% Ambiguous latent indexes are read from bootstrapResults*.

clc;
clear;
close all;

%% ---------------- User parameters --------------------------------------

data_content = 'raw_count';
% options:
% raw_count
% raw_fr
% z_within_trial
% z_within_condition
% z_across_conditions
% demean_count_within_trial
% demean_fr_within_trial
% demean_pooledsd_within_condition

data_condition = [];
% []   : all-condition model
% 1:16 : condition-specific models
%
% In condition-specific mode, one four-panel figure is generated and saved
% inside the result directory for each requested condition.

runIdx = 1;

% Display/file labels only. Their order must follow the DLAG model-group
% order. These names do not affect rGroups selection or any delay,
% timescale, shared-variance, or latent-classification calculation, and
% they are not compared with stored group or area names.
group_names = {'V1', 'MT'};

% The first group is treated as the source area and the second group as the
% target area when calculating across-area delay.
rGroups = [1 2];

% MATLAB scatter uses marker AREA in points squared.
%
% marker area =
%     marker_area_scale * shared_variance_explained_fraction
%
% Increase this value to make all circles larger.
marker_area_scale = 1800;

% Visibility floor for very small or zero shared-variance values.
% Set this to 0 for strictly proportional marker areas.
minimum_marker_area = 0;

% Optional upper limit on marker area.
% Use Inf to avoid capping large markers.
maximum_marker_area = Inf;

% Horizontal center and spreading of within-area latent circles.
%
% For example, with center = 1 and spread = 0.55, the latent circles are
% placed between x = 0.45 and x = 1.55.
within_x_center = 1;
within_x_spread = 0.55;

% Manual across-area delay limits.
% Use [] to determine common limits automatically from the data.
delay_xlim = [];
% Example:
% delay_xlim = [-150 150];

% Fixed common timescale display for all four panels.
% Raw timescale values are NOT changed in PlotData or saved MAT files.
% Values > timescale_y_regular_max are plotted at timescale_overflow_y.
timescale_y_min = 0;
timescale_y_regular_max = 400;
timescale_y_tick_step = 50;
timescale_overflow_y = 430;
timescale_y_top_padding = 15;

% Internal y limits used by the plotting functions. Keep this derived from
% the overflow settings above rather than editing it independently.
timescale_ylim = [ ...
    timescale_y_min, ...
    timescale_overflow_y + timescale_y_top_padding];

% Plot appearance

% Horizontal lines used to divide GP timescale ranges.
% Each value specifies a y-axis coordinate.
% Use [] to disable these lines.
timescale_division_lines = [120 300];

% Appearance of the timescale division lines
timescale_division_line_color = [0.70 0.0 0.0];
timescale_division_line_style = '--';
timescale_division_line_width = 1.0;

ff_fb_color = [0 0 0];
ambiguous_color = [0.55 0.55 0.55];

marker_edge_line_width = 0.75;
zero_delay_line_color = [0.55 0.55 0.55];
zero_delay_line_width = 1.5;

font_size = 12;
axes_line_width = 0.8;

legend_marker_area = 65;
legend_location = 'best';

figure_position = [80 120 1680 530];

% Output options
make_plot = true;
save_figures = true;
save_mat = true;

output_base_name = 'timescale_svexp';
export_resolution = 400;

% true  : close each figure after saving
% false : leave generated figures open
close_figure_after_saving = false;

%% ---------------- Setup -------------------------------------------------

if isempty(data_condition)
    use_condition_mode = false;
    condition_list = [];
    numConditions = 1;
    model_mode = 'all_condition_model';
else
    use_condition_mode = true;
    condition_list = data_condition(:)';
    numConditions = numel(condition_list);
    model_mode = 'condition_specific_models';
end

group_names = normalizeGroupNamesLocal(group_names);
[groupDisplayNames, groupFileTags] = ...
    buildGroupLabelsLocal(group_names);

validateUserParametersLocal( ...
    rGroups, ...
    marker_area_scale, ...
    minimum_marker_area, ...
    maximum_marker_area, ...
    within_x_center, ...
    within_x_spread, ...
    delay_xlim, ...
    timescale_ylim);

validateTimescaleOverflowSettingsLocal( ...
    timescale_y_min, ...
    timescale_y_regular_max, ...
    timescale_y_tick_step, ...
    timescale_overflow_y, ...
    timescale_y_top_padding);

%% ---------------- Main loop --------------------------------------------

for cond_i = 1:numConditions

    if use_condition_mode
        this_condition = condition_list(cond_i);

        baseDir = [ ...
            './FA_Dlag_', ...
            data_content, ...
            '_condition', ...
            num2str(this_condition)];

        fprintf('\nCondition %d\n', this_condition);
    else
        this_condition = [];
        baseDir = ['./FA_Dlag_', data_content];
    end

    tempfname = sprintf( ...
        '%s/mat_results/run%03d', ...
        baseDir, ...
        runIdx);

    fprintf('Reading model from %s\n', tempfname);

    if ~exist(tempfname, 'dir')
        error('Result directory does not exist: %s', tempfname);
    end

    %% Load best model

    bestFile = findFirstFileLocal(tempfname, 'bestmodel*');

    Sbest = load( ...
        bestFile, ...
        'bestModel', ...
        'varexp', ...
        'gp_params');

    requiredBestFields = { ...
        'bestModel', ...
        'varexp', ...
        'gp_params'};

    for field_i = 1:numel(requiredBestFields)
        thisField = requiredBestFields{field_i};

        if ~isfield(Sbest, thisField)
            error( ...
                'The bestmodel file is missing variable "%s": %s', ...
                thisField, ...
                bestFile);
        end
    end

    %% Load ambiguous latent indexes

    bootFile = findFirstFileLocal( ...
        tempfname, ...
        'bootstrapResults*');

    Sboot = load( ...
        bootFile, ...
        'ambiguousIdxs');

    if ~isfield(Sboot, 'ambiguousIdxs')
        error( ...
            ['The bootstrapResults file is missing variable ', ...
             '"ambiguousIdxs": %s'], ...
            bootFile);
    end

    %% Collect plotting data

    PlotData = collectTimescaleSvexpLocal( ...
        Sbest.bestModel, ...
        Sbest.varexp, ...
        Sbest.gp_params, ...
        Sboot.ambiguousIdxs, ...
        rGroups, ...
        marker_area_scale, ...
        minimum_marker_area, ...
        maximum_marker_area, ...
        within_x_center, ...
        within_x_spread, ...
        delay_xlim, ...
        timescale_ylim);

    validateGroupNameCountLocal( ...
        group_names, ...
        PlotData.meta.numGroups);

    PlotData.meta.data_content = data_content;
    PlotData.meta.data_condition = this_condition;
    PlotData.meta.use_condition_mode = use_condition_mode;
    PlotData.meta.model_mode = model_mode;
    PlotData.meta.condition_index_in_list = cond_i;
    PlotData.meta.condition_list = condition_list;
    PlotData.meta.runIdx = runIdx;
    PlotData.meta.rGroups = rGroups;
    PlotData.meta.baseDir = baseDir;
    PlotData.meta.tempfname = tempfname;
    PlotData.meta.bestmodel_file = bestFile;
    PlotData.meta.bootstrap_file = bootFile;
    PlotData.meta.group_names = group_names;
    PlotData.meta.group_display_names = groupDisplayNames;
    PlotData.meta.group_file_tags = groupFileTags;
    PlotData.meta.selected_group_names = group_names(rGroups);
    PlotData.meta.selected_group_display_names = ...
        groupDisplayNames(rGroups);
    PlotData.meta.selected_group_file_tags = ...
        groupFileTags(rGroups);
    PlotData.meta.selected_group_pair_file_tag = sprintf( ...
        '%s_to_%s', ...
        groupFileTags{rGroups(1)}, ...
        groupFileTags{rGroups(2)});

    for selected_i = 1:numel(PlotData.selectedGroup)
        groupIdx = PlotData.selectedGroup(selected_i).groupIdx;
        PlotData.selectedGroup(selected_i).name = ...
            groupDisplayNames{groupIdx};
        PlotData.selectedGroup(selected_i).file_tag = ...
            groupFileTags{groupIdx};
    end

    this_output_base_name = sprintf( ...
        '%s_%s', ...
        output_base_name, ...
        PlotData.meta.selected_group_pair_file_tag);

    PlotData.options.marker_area_scale = marker_area_scale;
    PlotData.options.minimum_marker_area = minimum_marker_area;
    PlotData.options.maximum_marker_area = maximum_marker_area;
    PlotData.options.within_x_center = within_x_center;
    PlotData.options.within_x_spread = within_x_spread;
    PlotData.options.delay_xlim_requested = delay_xlim;
    PlotData.options.timescale_ylim_requested = timescale_ylim;
    PlotData.options.timescale_y_min = timescale_y_min;
    PlotData.options.timescale_y_regular_max = timescale_y_regular_max;
    PlotData.options.timescale_y_tick_step = timescale_y_tick_step;
    PlotData.options.timescale_overflow_y = timescale_overflow_y;
    PlotData.options.timescale_y_top_padding = timescale_y_top_padding;
    PlotData.options.ff_fb_color = ff_fb_color;
    PlotData.options.ambiguous_color = ambiguous_color;

    %% Make figure

    figHandle = gobjects(0);

    if make_plot
figHandle = plotTimescaleSvexpLocal( ...
    PlotData, ...
    ff_fb_color, ...
    ambiguous_color, ...
    marker_edge_line_width, ...
    zero_delay_line_color, ...
    zero_delay_line_width, ...
    timescale_division_lines, ...
    timescale_division_line_color, ...
    timescale_division_line_style, ...
    timescale_division_line_width, ...
    timescale_y_min, ...
    timescale_y_regular_max, ...
    timescale_y_tick_step, ...
    timescale_overflow_y, ...
    timescale_y_top_padding, ...
    font_size, ...
    axes_line_width, ...
    legend_marker_area, ...
    legend_location, ...
    figure_position);

        if save_figures
            saveFigureLocal( ...
                figHandle, ...
                tempfname, ...
                this_output_base_name, ...
                export_resolution);
        end

        if close_figure_after_saving && isgraphics(figHandle)
            close(figHandle);
        end
    end

    %% Save extracted plotting data

    if save_mat
        outputMatFile = fullfile( ...
            tempfname, ...
            [this_output_base_name, '_data.mat']);

        save( ...
            outputMatFile, ...
            'PlotData', ...
            'data_content', ...
            'data_condition', ...
            'this_condition', ...
            'condition_list', ...
            'use_condition_mode', ...
            'model_mode', ...
            'runIdx', ...
            'rGroups', ...
            'marker_area_scale', ...
            'minimum_marker_area', ...
            'maximum_marker_area', ...
            'within_x_center', ...
            'within_x_spread', ...
            'delay_xlim', ...
            'timescale_ylim');

        fprintf('Saved data to %s\n', outputMatFile);
    end
end

%% ========================================================================
%% Local functions
%% ========================================================================

function PlotData = collectTimescaleSvexpLocal( ...
    bestModel, ...
    varexp, ...
    gp_params, ...
    ambiguousIdxs, ...
    rGroups, ...
    marker_area_scale, ...
    minimum_marker_area, ...
    maximum_marker_area, ...
    within_x_center, ...
    within_x_spread, ...
    requested_delay_xlim, ...
    requested_timescale_ylim)

    %% Model dimensions

    if ~isstruct(bestModel)
        error('bestModel must be a struct.');
    end

    if ~isfield(bestModel, 'xDim_across')
        error('bestModel is missing xDim_across.');
    end

    if ~isfield(bestModel, 'xDim_within')
        error('bestModel is missing xDim_within.');
    end

    xDim_across = double(bestModel.xDim_across);
    xDim_within = double(bestModel.xDim_within(:)');

    if ~isscalar(xDim_across) || ...
            ~isfinite(xDim_across) || ...
            xDim_across < 0 || ...
            xDim_across ~= round(xDim_across)

        error('bestModel.xDim_across must be a nonnegative integer.');
    end

    if any(~isfinite(xDim_within)) || ...
            any(xDim_within < 0) || ...
            any(xDim_within ~= round(xDim_within))

        error( ...
            'Every value in bestModel.xDim_within must be a nonnegative integer.');
    end

    numGroups = numel(xDim_within);

    if any(rGroups > numGroups)
        error( ...
            ['rGroups contains a group index larger than the number ', ...
             'of groups in bestModel.']);
    end

    %% Delays and timescales

    across_delay = getAcrossDelayLocal( ...
        gp_params, ...
        xDim_across, ...
        rGroups);

    [tau_across, tau_within] = getGpTimescaleLocal( ...
        gp_params, ...
        xDim_across, ...
        xDim_within);

    %% Latent classification

    latentClass = classifyAcrossLatentsLocal( ...
        across_delay, ...
        ambiguousIdxs);

    %% Shared variance explained

    if ~isstruct(varexp) || ~isfield(varexp, 'indiv')
        error('varexp must contain the field varexp.indiv.');
    end

    if ~iscell(varexp.indiv)
        error('varexp.indiv must be a cell array.');
    end

    if numel(varexp.indiv) < numGroups
        error( ...
            ['varexp.indiv contains fewer groups than ', ...
             'bestModel.xDim_within.']);
    end

    selectedGroup = struct([]);

    for selected_i = 1:2

        groupIdx = rGroups(selected_i);
        expectedLocalDim = xDim_across + xDim_within(groupIdx);

        this_varexp = reshape( ...
            double(varexp.indiv{groupIdx}), ...
            1, ...
            []);

        if numel(this_varexp) ~= expectedLocalDim
            error( ...
                ['Group %d: varexp.indiv{%d} has %d entries, ', ...
                 'but %d entries were expected.'], ...
                groupIdx, ...
                groupIdx, ...
                numel(this_varexp), ...
                expectedLocalDim);
        end

        this_varexp = validateSharedVarianceLocal( ...
            this_varexp, ...
            groupIdx);

        across_svexp = this_varexp(1:xDim_across);

        within_start = xDim_across + 1;
        within_stop = xDim_across + xDim_within(groupIdx);

        if xDim_within(groupIdx) > 0
            within_svexp = this_varexp(within_start:within_stop);
        else
            within_svexp = zeros(1, 0);
        end

        selectedGroup(selected_i).groupIdx = groupIdx;

        selectedGroup(selected_i).across.latentIdx = 1:xDim_across;
        selectedGroup(selected_i).across.delay = across_delay;
        selectedGroup(selected_i).across.tau = tau_across;
        selectedGroup(selected_i).across.svexpFraction = across_svexp;
        selectedGroup(selected_i).across.svexpPercent = 100 .* across_svexp;

        selectedGroup(selected_i).across.markerArea = ...
            makeMarkerAreaLocal( ...
                across_svexp, ...
                marker_area_scale, ...
                minimum_marker_area, ...
                maximum_marker_area);

        selectedGroup(selected_i).within.latentIdx = ...
            1:xDim_within(groupIdx);

        selectedGroup(selected_i).within.tau = ...
            tau_within{groupIdx};

        selectedGroup(selected_i).within.svexpFraction = ...
            within_svexp;

        selectedGroup(selected_i).within.svexpPercent = ...
            100 .* within_svexp;

        selectedGroup(selected_i).within.markerArea = ...
            makeMarkerAreaLocal( ...
                within_svexp, ...
                marker_area_scale, ...
                minimum_marker_area, ...
                maximum_marker_area);

        selectedGroup(selected_i).within.x = ...
            makeWithinXPositionsLocal( ...
                xDim_within(groupIdx), ...
                within_x_center, ...
                within_x_spread);
    end

    %% Common axis limits

    common_delay_xlim = makeDelayXLimLocal( ...
        across_delay, ...
        requested_delay_xlim);

    all_timescales = tau_across;

    for selected_i = 1:2
        all_timescales = [ ...
            all_timescales, ...
            selectedGroup(selected_i).within.tau]; %#ok<AGROW>
    end

    common_timescale_ylim = makeTimescaleYLimLocal( ...
        all_timescales, ...
        requested_timescale_ylim);

    within_xlim = makeWithinXLimLocal( ...
        within_x_center, ...
        within_x_spread);

    %% Warn about nonfinite values that cannot be plotted

    invalidAcross = ...
        ~isfinite(across_delay) | ...
        ~isfinite(tau_across);

    if any(invalidAcross)
        warning( ...
            ['%d across-area latent(s) have nonfinite delay or ', ...
             'timescale and cannot be plotted.'], ...
            sum(invalidAcross));
    end

    for selected_i = 1:2
        invalidWithin = ...
            ~isfinite(selectedGroup(selected_i).within.tau);

        if any(invalidWithin)
            warning( ...
                ['Group %d: %d within-area latent(s) have ', ...
                 'nonfinite timescales and cannot be plotted.'], ...
                selectedGroup(selected_i).groupIdx, ...
                sum(invalidWithin));
        end
    end

    %% Output structure

    PlotData = struct();

    PlotData.meta.numGroups = numGroups;
    PlotData.meta.xDim_across = xDim_across;
    PlotData.meta.xDim_within = xDim_within;
    PlotData.meta.timescale_unit = 'ms';
    PlotData.meta.delay_unit = 'ms';

    PlotData.classification = latentClass;

    PlotData.across.latentIdx = 1:xDim_across;
    PlotData.across.delay = across_delay;
    PlotData.across.tau = tau_across;

    PlotData.selectedGroup = selectedGroup;

    PlotData.axisLimits.delay = common_delay_xlim;
    PlotData.axisLimits.timescale = common_timescale_ylim;
    PlotData.axisLimits.withinX = within_xlim;
end

function across_delay = getAcrossDelayLocal( ...
    gp_params, ...
    xDim_across, ...
    rGroups)

    if xDim_across == 0
        across_delay = zeros(1, 0);
        return;
    end

    if ~isstruct(gp_params)
        error('gp_params must be a struct.');
    end

    % Prefer DelayMatrix because this explicitly uses the requested
    % rGroups ordering.
    if isfield(gp_params, 'DelayMatrix') && ...
            ~isempty(gp_params.DelayMatrix)

        DelayMatrix = double(gp_params.DelayMatrix);

        if size(DelayMatrix, 1) < max(rGroups)
            error( ...
                ['gp_params.DelayMatrix does not contain all groups ', ...
                 'requested in rGroups.']);
        end

        if size(DelayMatrix, 2) < xDim_across
            error( ...
                ['gp_params.DelayMatrix has fewer columns than ', ...
                 'bestModel.xDim_across.']);
        end

        across_delay = ...
            DelayMatrix(rGroups(2), 1:xDim_across) - ...
            DelayMatrix(rGroups(1), 1:xDim_across);

    elseif isfield(gp_params, 'delays')

        across_delay = reshape( ...
            double(gp_params.delays), ...
            1, ...
            []);

        if numel(across_delay) < xDim_across
            error( ...
                ['gp_params.delays has fewer entries than ', ...
                 'bestModel.xDim_across.']);
        end

        across_delay = across_delay(1:xDim_across);

    else
        error( ...
            ['gp_params contains neither DelayMatrix nor delays. ', ...
             'Across-area delays cannot be determined.']);
    end
end

function [tau_across, tau_within] = getGpTimescaleLocal( ...
    gp_params, ...
    xDim_across, ...
    xDim_within)

    if ~isstruct(gp_params)
        error('gp_params must be a struct.');
    end

    if ~isfield(gp_params, 'tau_across')
        error('gp_params is missing tau_across.');
    end

    if ~isfield(gp_params, 'tau_within')
        error('gp_params is missing tau_within.');
    end

    tau_across = reshape( ...
        double(gp_params.tau_across), ...
        1, ...
        []);

    if numel(tau_across) < xDim_across
        error( ...
            ['gp_params.tau_across has fewer entries than ', ...
             'bestModel.xDim_across.']);
    end

    tau_across = tau_across(1:xDim_across);

    if ~iscell(gp_params.tau_within)
        error('gp_params.tau_within must be a cell array.');
    end

    if numel(gp_params.tau_within) < numel(xDim_within)
        error( ...
            ['gp_params.tau_within contains fewer groups than ', ...
             'bestModel.xDim_within.']);
    end

    tau_within = cell(1, numel(xDim_within));

    for groupIdx = 1:numel(xDim_within)

        thisTau = reshape( ...
            double(gp_params.tau_within{groupIdx}), ...
            1, ...
            []);

        if numel(thisTau) < xDim_within(groupIdx)
            error( ...
                ['gp_params.tau_within{%d} has fewer entries than ', ...
                 'bestModel.xDim_within(%d).'], ...
                groupIdx, ...
                groupIdx);
        end

        tau_within{groupIdx} = ...
            thisTau(1:xDim_within(groupIdx));
    end
end

function latentClass = classifyAcrossLatentsLocal( ...
    across_delay, ...
    ambiguousIdxs)

    xDim_across = numel(across_delay);
    acrossIdx = 1:xDim_across;

    if islogical(ambiguousIdxs)

        if numel(ambiguousIdxs) == xDim_across
            ambiguousIdxs = find(ambiguousIdxs);
        else
            ambiguousIdxs = find(ambiguousIdxs(:));
        end
    end

    ambiguousIdxs = reshape( ...
        double(ambiguousIdxs), ...
        1, ...
        []);

    validAmbiguousIndex = ...
        isfinite(ambiguousIdxs) & ...
        ambiguousIdxs == round(ambiguousIdxs) & ...
        ambiguousIdxs >= 1 & ...
        ambiguousIdxs <= xDim_across;

    ambiguousIdxs = unique( ...
        ambiguousIdxs(validAmbiguousIndex));

    zeroOrNonfiniteIdx = acrossIdx( ...
        across_delay == 0 | ...
        ~isfinite(across_delay));

    ambiguousAll = unique([ ...
        ambiguousIdxs, ...
        zeroOrNonfiniteIdx]);

    ffIdx = find(across_delay > 0);
    fbIdx = find(across_delay < 0);

    ffIdx = setdiff(ffIdx, ambiguousAll);
    fbIdx = setdiff(fbIdx, ambiguousAll);

    coveredIdx = unique([ ...
        ffIdx, ...
        fbIdx, ...
        ambiguousAll]);

    missingIdx = setdiff(acrossIdx, coveredIdx);

    if ~isempty(missingIdx)
        ambiguousAll = unique([ ...
            ambiguousAll, ...
            missingIdx]);
    end

    isFF = false(1, xDim_across);
    isFB = false(1, xDim_across);
    isAmbiguous = false(1, xDim_across);

    isFF(ffIdx) = true;
    isFB(fbIdx) = true;
    isAmbiguous(ambiguousAll) = true;

    latentClass = struct();

    latentClass.acrossIdx = acrossIdx;
    latentClass.acrossDelay = across_delay;

    latentClass.feedforwardIdx = ffIdx;
    latentClass.feedbackIdx = fbIdx;
    latentClass.ambiguousIdx = ambiguousAll;

    latentClass.isFeedforward = isFF;
    latentClass.isFeedback = isFB;
    latentClass.isAmbiguous = isAmbiguous;
    latentClass.isFForFB = isFF | isFB;
end

function svexp = validateSharedVarianceLocal( ...
    svexp, ...
    groupIdx)

    if any(~isfinite(svexp))
        error( ...
            ['Group %d: varexp.indiv{%d} contains nonfinite ', ...
             'shared variance explained values.'], ...
            groupIdx, ...
            groupIdx);
    end

    negativeTolerance = 1e-12;

    if any(svexp < -negativeTolerance)
        error( ...
            ['Group %d: varexp.indiv{%d} contains negative ', ...
             'shared variance explained values.'], ...
            groupIdx, ...
            groupIdx);
    end

    % Remove very small negative values caused only by numerical precision.
    svexp(svexp < 0) = 0;
end

function markerArea = makeMarkerAreaLocal( ...
    svexp, ...
    marker_area_scale, ...
    minimum_marker_area, ...
    maximum_marker_area)

    markerArea = marker_area_scale .* svexp;

    if minimum_marker_area > 0
        markerArea = max( ...
            markerArea, ...
            minimum_marker_area);
    end

    if isfinite(maximum_marker_area)
        markerArea = min( ...
            markerArea, ...
            maximum_marker_area);
    end
end

function xWithin = makeWithinXPositionsLocal( ...
    numWithin, ...
    xCenter, ...
    xSpread)

    if numWithin == 0
        xWithin = zeros(1, 0);

    elseif numWithin == 1
        xWithin = xCenter;

    else
        xWithin = linspace( ...
            xCenter - xSpread, ...
            xCenter + xSpread, ...
            numWithin);
    end
end

function delayLim = makeDelayXLimLocal( ...
    across_delay, ...
    requested_delay_xlim)

    if ~isempty(requested_delay_xlim)
        delayLim = reshape( ...
            double(requested_delay_xlim), ...
            1, ...
            []);

        if numel(delayLim) ~= 2 || ...
                any(~isfinite(delayLim)) || ...
                delayLim(2) <= delayLim(1)

            error( ...
                'delay_xlim must be [] or a finite increasing two-element vector.');
        end

        return;
    end

    finiteDelay = across_delay(isfinite(across_delay));

    if isempty(finiteDelay)
        delayLim = [-1 1];
        return;
    end

    delayMin = min([finiteDelay, 0]);
    delayMax = max([finiteDelay, 0]);

    delayRange = delayMax - delayMin;

    if delayRange <= 0
        delayPadding = max(1, abs(delayMax) .* 0.1);
    else
        delayPadding = max(1, delayRange .* 0.08);
    end

    delayLim = [ ...
        delayMin - delayPadding, ...
        delayMax + delayPadding];
end

function yLim = makeTimescaleYLimLocal( ...
    all_timescales, ...
    requested_timescale_ylim)

    if ~isempty(requested_timescale_ylim)
        yLim = reshape( ...
            double(requested_timescale_ylim), ...
            1, ...
            []);

        if numel(yLim) ~= 2 || ...
                any(~isfinite(yLim)) || ...
                yLim(2) <= yLim(1)

            error( ...
                ['timescale_ylim must be [] or a finite increasing ', ...
                 'two-element vector.']);
        end

        return;
    end

    finiteTau = all_timescales(isfinite(all_timescales));

    if isempty(finiteTau)
        yLim = [0 1];
        return;
    end

    maximumTau = max(finiteTau);

    if maximumTau <= 0
        yLim = [0 1];
        return;
    end

    upperPadding = max(1, 0.06 .* maximumTau);

    yLim = [ ...
        0, ...
        maximumTau + upperPadding];
end

function xLim = makeWithinXLimLocal( ...
    xCenter, ...
    xSpread)

    visualPadding = max(0.18, 0.2 .* max(xSpread, 0.1));

    if xSpread == 0
        xLim = [ ...
            xCenter - 0.5, ...
            xCenter + 0.5];
    else
        xLim = [ ...
            xCenter - xSpread - visualPadding, ...
            xCenter + xSpread + visualPadding];
    end
end

function tauPlot = transformTimescaleForDisplayLocal( ...
    tau, ...
    regular_max, ...
    overflow_y)

    tauPlot = tau;
    tauPlot(tauPlot > regular_max) = overflow_y;
end

function applyTimescaleOverflowAxisLocal( ...
    ax, ...
    y_min, ...
    regular_max, ...
    tick_step, ...
    overflow_y, ...
    top_padding)

    regularTicks = y_min:tick_step:regular_max;
    yTicks = [regularTicks, overflow_y];

    tickLabels = arrayfun( ...
        @(x) sprintf('%g', x), ...
        regularTicks, ...
        'UniformOutput', false);
    tickLabels{end + 1} = sprintf('>%g', regular_max);

    set( ...
        ax, ...
        'YScale', 'linear', ...
        'YTick', yTicks, ...
        'YTickLabel', tickLabels);

    ylim(ax, [y_min, overflow_y + top_padding]);
end

function figHandle = plotTimescaleSvexpLocal( ...
    PlotData, ...
    ff_fb_color, ...
    ambiguous_color, ...
    marker_edge_line_width, ...
    zero_delay_line_color, ...
    zero_delay_line_width, ...
    timescale_division_lines, ...
    timescale_division_line_color, ...
    timescale_division_line_style, ...
    timescale_division_line_width, ...
    timescale_y_min, ...
    timescale_y_regular_max, ...
    timescale_y_tick_step, ...
    timescale_overflow_y, ...
    timescale_y_top_padding, ...
    font_size, ...
    axes_line_width, ...
    legend_marker_area, ...
    legend_location, ...
    figure_position);

    figHandle = figure( ...
        'Color', 'w', ...
        'Position', figure_position, ...
        'Name', sprintf( ...
            'DLAG timescale and shared variance explained | %s to %s', ...
            PlotData.meta.selected_group_display_names{1}, ...
            PlotData.meta.selected_group_display_names{2}), ...
        'NumberTitle', 'off');

    tiled = tiledlayout( ...
        figHandle, ...
        1, ...
        4, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    axesHandles = gobjects(1, 4);

    group1 = PlotData.selectedGroup(1);
    group2 = PlotData.selectedGroup(2);

    %% Across-area group 1

    axesHandles(1) = nexttile(tiled, 1);

    plotAcrossPanelLocal( ...
        axesHandles(1), ...
        group1.across.delay, ...
        transformTimescaleForDisplayLocal( ...
            group1.across.tau, timescale_y_regular_max, timescale_overflow_y), ...
        group1.across.markerArea, ...
        PlotData.classification.isAmbiguous, ...
        group1.name, ...
        PlotData.meta.selected_group_display_names, ...
        PlotData.axisLimits.delay, ...
        PlotData.axisLimits.timescale, ...
        ff_fb_color, ...
        ambiguous_color, ...
        marker_edge_line_width, ...
        zero_delay_line_color, ...
        zero_delay_line_width, ...
        font_size, ...
        axes_line_width);

    % Category-only legend.
    % These marker sizes do not represent SVEXP values.
    hold(axesHandles(1), 'on');

    hBlack = scatter( ...
        axesHandles(1), ...
        NaN, ...
        NaN, ...
        legend_marker_area, ...
        'o', ...
        'filled', ...
        'MarkerFaceColor', ff_fb_color, ...
        'MarkerEdgeColor', ff_fb_color, ...
        'LineWidth', marker_edge_line_width);

    hGray = scatter( ...
        axesHandles(1), ...
        NaN, ...
        NaN, ...
        legend_marker_area, ...
        'o', ...
        'filled', ...
        'MarkerFaceColor', ambiguous_color, ...
        'MarkerEdgeColor', ambiguous_color, ...
        'LineWidth', marker_edge_line_width);

    legend( ...
        axesHandles(1), ...
        [hBlack, hGray], ...
        {'FF / FB', 'Ambiguous'}, ...
        'Location', legend_location, ...
        'Box', 'off');

    %% Across-area group 2

    axesHandles(2) = nexttile(tiled, 2);

    plotAcrossPanelLocal( ...
        axesHandles(2), ...
        group2.across.delay, ...
        transformTimescaleForDisplayLocal( ...
            group2.across.tau, timescale_y_regular_max, timescale_overflow_y), ...
        group2.across.markerArea, ...
        PlotData.classification.isAmbiguous, ...
        group2.name, ...
        PlotData.meta.selected_group_display_names, ...
        PlotData.axisLimits.delay, ...
        PlotData.axisLimits.timescale, ...
        ff_fb_color, ...
        ambiguous_color, ...
        marker_edge_line_width, ...
        zero_delay_line_color, ...
        zero_delay_line_width, ...
        font_size, ...
        axes_line_width);

    %% Within-area group 1

    axesHandles(3) = nexttile(tiled, 3);

    plotWithinPanelLocal( ...
        axesHandles(3), ...
        group1.within.x, ...
        transformTimescaleForDisplayLocal( ...
            group1.within.tau, timescale_y_regular_max, timescale_overflow_y), ...
        group1.within.markerArea, ...
        group1.name, ...
        PlotData.axisLimits.withinX, ...
        PlotData.axisLimits.timescale, ...
        ff_fb_color, ...
        marker_edge_line_width, ...
        font_size, ...
        axes_line_width);

    %% Within-area group 2

    axesHandles(4) = nexttile(tiled, 4);

    plotWithinPanelLocal( ...
        axesHandles(4), ...
        group2.within.x, ...
        transformTimescaleForDisplayLocal( ...
            group2.within.tau, timescale_y_regular_max, timescale_overflow_y), ...
        group2.within.markerArea, ...
        group2.name, ...
        PlotData.axisLimits.withinX, ...
        PlotData.axisLimits.timescale, ...
        ff_fb_color, ...
        marker_edge_line_width, ...
        font_size, ...
        axes_line_width);

% Explicitly enforce the same fixed overflow y axis after all graphics
% are created. The underlying PlotData timescales remain raw.
for ax_i = 1:numel(axesHandles)
    applyTimescaleOverflowAxisLocal( ...
        axesHandles(ax_i), ...
        timescale_y_min, ...
        timescale_y_regular_max, ...
        timescale_y_tick_step, ...
        timescale_overflow_y, ...
        timescale_y_top_padding);
end

%% Timescale division lines

timescale_division_lines = reshape( ...
    double(timescale_division_lines), ...
    1, ...
    []);

timescale_division_lines = unique( ...
    timescale_division_lines(isfinite(timescale_division_lines)));

for ax_i = 1:numel(axesHandles)

    ax = axesHandles(ax_i);
    currentXLim = xlim(ax);

    for line_i = 1:numel(timescale_division_lines)

        thisTimescale = timescale_division_lines(line_i);

        % Lines outside the displayed y range are not drawn.
        if thisTimescale < PlotData.axisLimits.timescale(1) || ...
                thisTimescale > PlotData.axisLimits.timescale(2)
            continue;
        end

        hDivisionLine = plot( ...
            ax, ...
            currentXLim, ...
            [thisTimescale thisTimescale], ...
            timescale_division_line_style, ...
            'Color', timescale_division_line_color, ...
            'LineWidth', timescale_division_line_width, ...
            'HandleVisibility', 'off');

        % Keep the division lines behind the latent circles.
        uistack(hDivisionLine, 'bottom');
    end
end
end

function plotAcrossPanelLocal( ...
    ax, ...
    delay, ...
    tau, ...
    markerArea, ...
    isAmbiguous, ...
    groupDisplayName, ...
    selectedGroupDisplayNames, ...
    delayLim, ...
    timescaleLim, ...
    ff_fb_color, ...
    ambiguous_color, ...
    marker_edge_line_width, ...
    zero_delay_line_color, ...
    zero_delay_line_width, ...
    font_size, ...
    axes_line_width)

    hold(ax, 'on');

    xlim(ax, delayLim);
    ylim(ax, timescaleLim);

    % Zero-delay reference line
    plot( ...
        ax, ...
        [0 0], ...
        timescaleLim, ...
        '--', ...
        'Color', zero_delay_line_color, ...
        'LineWidth', zero_delay_line_width, ...
        'HandleVisibility', 'off');

    validIdx = find( ...
        isfinite(delay) & ...
        isfinite(tau) & ...
        isfinite(markerArea) & ...
        markerArea > 0);

    % Draw large circles first and small circles afterward so that a small
    % circle is less likely to be completely hidden.
    if ~isempty(validIdx)
        [~, areaOrder] = sort( ...
            markerArea(validIdx), ...
            'descend');

        drawIdx = validIdx(areaOrder);

        for idx_i = 1:numel(drawIdx)

            latentIdx = drawIdx(idx_i);

            if isAmbiguous(latentIdx)
                thisColor = ambiguous_color;
            else
                thisColor = ff_fb_color;
            end

            scatter( ...
                ax, ...
                delay(latentIdx), ...
                tau(latentIdx), ...
                markerArea(latentIdx), ...
                'o', ...
                'filled', ...
                'MarkerFaceColor', thisColor, ...
                'MarkerEdgeColor', thisColor, ...
                'LineWidth', marker_edge_line_width, ...
                'HandleVisibility', 'off');
        end
    end

    xlabel( ...
        ax, ...
        sprintf( ...
            'Delay from %s to %s', ...
            selectedGroupDisplayNames{1}, ...
            selectedGroupDisplayNames{2}));

    ylabel(ax, 'GP timescale');

    title( ...
        ax, ...
        sprintf( ...
            'Across-area latents, %s', ...
            groupDisplayName), ...
        'FontWeight', 'normal');

    formatAxesLocal( ...
        ax, ...
        font_size, ...
        axes_line_width);
end

function plotWithinPanelLocal( ...
    ax, ...
    xWithin, ...
    tauWithin, ...
    markerArea, ...
    groupDisplayName, ...
    withinXLim, ...
    timescaleLim, ...
    markerColor, ...
    marker_edge_line_width, ...
    font_size, ...
    axes_line_width)

    hold(ax, 'on');

    xlim(ax, withinXLim);
    ylim(ax, timescaleLim);

    validIdx = find( ...
        isfinite(xWithin) & ...
        isfinite(tauWithin) & ...
        isfinite(markerArea) & ...
        markerArea > 0);

    % Draw large circles first and small circles afterward.
    if ~isempty(validIdx)
        [~, areaOrder] = sort( ...
            markerArea(validIdx), ...
            'descend');

        drawIdx = validIdx(areaOrder);

        for idx_i = 1:numel(drawIdx)

            latentIdx = drawIdx(idx_i);

            scatter( ...
                ax, ...
                xWithin(latentIdx), ...
                tauWithin(latentIdx), ...
                markerArea(latentIdx), ...
                'o', ...
                'filled', ...
                'MarkerFaceColor', markerColor, ...
                'MarkerEdgeColor', markerColor, ...
                'LineWidth', marker_edge_line_width, ...
                'HandleVisibility', 'off');
        end
    end

    xticks(ax, mean(withinXLim));
    xticklabels(ax, {'Within'});

    xlabel(ax, 'Within-area latents');
    ylabel(ax, 'GP timescale');

    title( ...
        ax, ...
        sprintf( ...
            'Within-area latents, %s', ...
            groupDisplayName), ...
        'FontWeight', 'normal');

    formatAxesLocal( ...
        ax, ...
        font_size, ...
        axes_line_width);
end

function formatAxesLocal( ...
    ax, ...
    font_size, ...
    axes_line_width)

    set( ...
        ax, ...
        'FontSize', font_size, ...
        'LineWidth', axes_line_width, ...
        'TickDir', 'out', ...
        'Box', 'off', ...
        'Layer', 'top');
end

function filename = findFirstFileLocal( ...
    folderPath, ...
    pattern)

    files = dir(fullfile(folderPath, pattern));

    if isempty(files)
        error( ...
            'No %s file found in %s', ...
            pattern, ...
            folderPath);
    end

    % Explicit alphabetical sorting gives deterministic behavior and is
    % consistent with taking the first matching file.
    [~, fileOrder] = sort({files.name});
    files = files(fileOrder);

    if numel(files) > 1
        warning( ...
            ['Multiple files matched "%s" in %s. ', ...
             'Using the first file: %s'], ...
            pattern, ...
            folderPath, ...
            files(1).name);
    end

    filename = fullfile( ...
        folderPath, ...
        files(1).name);
end

function saveFigureLocal( ...
    figHandle, ...
    folderPath, ...
    baseName, ...
    export_resolution)

    if isempty(figHandle) || ~isgraphics(figHandle)
        return;
    end

    if ~exist(folderPath, 'dir')
        mkdir(folderPath);
    end

    figFile = fullfile( ...
        folderPath, ...
        [baseName, '.fig']);

    pngFile = fullfile( ...
        folderPath, ...
        [baseName, '.png']);

    savefig(figHandle, figFile);

    try
        exportgraphics( ...
            figHandle, ...
            pngFile, ...
            'Resolution', export_resolution);
    catch
        saveas(figHandle, pngFile);
    end

    fprintf('Saved figure to %s\n', figFile);
    fprintf('Saved image to %s\n', pngFile);
end

function validateTimescaleOverflowSettingsLocal( ...
    y_min, ...
    regular_max, ...
    tick_step, ...
    overflow_y, ...
    top_padding)

    validateattributes(y_min, {'numeric'}, ...
        {'scalar', 'real', 'finite'}, ...
        mfilename, 'timescale_y_min');
    validateattributes(regular_max, {'numeric'}, ...
        {'scalar', 'real', 'finite', '>', y_min}, ...
        mfilename, 'timescale_y_regular_max');
    validateattributes(tick_step, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, ...
        mfilename, 'timescale_y_tick_step');
    validateattributes(overflow_y, {'numeric'}, ...
        {'scalar', 'real', 'finite', '>', regular_max}, ...
        mfilename, 'timescale_overflow_y');
    validateattributes(top_padding, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'nonnegative'}, ...
        mfilename, 'timescale_y_top_padding');

    if abs((regular_max - y_min) / tick_step - ...
            round((regular_max - y_min) / tick_step)) > 1e-10
        error([ ...
            'timescale_y_tick_step must divide the interval from ', ...
            'timescale_y_min to timescale_y_regular_max exactly.']);
    end
end

function validateUserParametersLocal( ...
    rGroups, ...
    marker_area_scale, ...
    minimum_marker_area, ...
    maximum_marker_area, ...
    within_x_center, ...
    within_x_spread, ...
    delay_xlim, ...
    timescale_ylim)

    rGroups = reshape(double(rGroups), 1, []);

    if numel(rGroups) ~= 2 || ...
            any(~isfinite(rGroups)) || ...
            any(rGroups < 1) || ...
            any(rGroups ~= round(rGroups)) || ...
            rGroups(1) == rGroups(2)

        error( ...
            'rGroups must contain two distinct positive integer group indexes.');
    end

    if ~isscalar(marker_area_scale) || ...
            ~isfinite(marker_area_scale) || ...
            marker_area_scale <= 0

        error('marker_area_scale must be a positive finite scalar.');
    end

    if ~isscalar(minimum_marker_area) || ...
            ~isfinite(minimum_marker_area) || ...
            minimum_marker_area < 0

        error( ...
            'minimum_marker_area must be a nonnegative finite scalar.');
    end

    if ~isscalar(maximum_marker_area) || ...
            isnan(maximum_marker_area) || ...
            maximum_marker_area <= 0

        error( ...
            'maximum_marker_area must be a positive scalar or Inf.');
    end

    if maximum_marker_area < minimum_marker_area
        error( ...
            ['maximum_marker_area cannot be smaller than ', ...
             'minimum_marker_area.']);
    end

    if ~isscalar(within_x_center) || ...
            ~isfinite(within_x_center)

        error('within_x_center must be a finite scalar.');
    end

    if ~isscalar(within_x_spread) || ...
            ~isfinite(within_x_spread) || ...
            within_x_spread < 0

        error('within_x_spread must be a nonnegative finite scalar.');
    end

    if ~isempty(delay_xlim)
        delay_xlim = reshape(double(delay_xlim), 1, []);

        if numel(delay_xlim) ~= 2 || ...
                any(~isfinite(delay_xlim)) || ...
                delay_xlim(2) <= delay_xlim(1)

            error( ...
                'delay_xlim must be [] or a finite increasing two-element vector.');
        end
    end

    if ~isempty(timescale_ylim)
        timescale_ylim = reshape(double(timescale_ylim), 1, []);

        if numel(timescale_ylim) ~= 2 || ...
                any(~isfinite(timescale_ylim)) || ...
                timescale_ylim(2) <= timescale_ylim(1)

            error( ...
                ['timescale_ylim must be [] or a finite increasing ', ...
                 'two-element vector.']);
        end
    end
end

function group_names = normalizeGroupNamesLocal(group_names)

    if isstring(group_names)
        group_names = cellstr(group_names(:)');
    elseif ischar(group_names)
        if size(group_names, 1) == 1
            group_names = {group_names};
        else
            group_names = reshape(cellstr(group_names), 1, []);
        end
    elseif iscell(group_names)
        group_names = reshape(group_names, 1, []);
    else
        error('group_names must be text or a cell array of text.');
    end

    if isempty(group_names)
        error('group_names cannot be empty.');
    end

    for g = 1:numel(group_names)
        value = group_names{g};

        if ~(ischar(value) || (isstring(value) && isscalar(value)))
            error('group_names{%d} must contain text.', g);
        end

        value = strtrim(char(string(value)));

        if isempty(value)
            error('group_names{%d} cannot be empty.', g);
        end

        group_names{g} = value;
    end
end

function validateGroupNameCountLocal(group_names, numGroups)

    if numel(group_names) ~= numGroups
        error([ ...
            'group_names has %d entries, but the current DLAG model ', ...
            'contains %d groups. The order of group_names must follow ', ...
            'the model-group order.'], ...
            numel(group_names), ...
            numGroups);
    end
end

function [groupDisplayNames, groupFileTags] = ...
        buildGroupLabelsLocal(group_names)

    nGroups = numel(group_names);
    groupDisplayNames = cell(1, nGroups);
    groupFileTags = cell(1, nGroups);

    for g = 1:nGroups
        groupDisplayNames{g} = sprintf( ...
            'Group %d: %s', ...
            g, ...
            group_names{g});

        areaToken = makeSafeGroupNameTagLocal(group_names{g});
        groupFileTags{g} = sprintf('G%02d_%s', g, areaToken);
    end
end

function tag = makeSafeGroupNameTagLocal(groupName)

    tag = strtrim(char(string(groupName)));
    tag = regexprep(tag, '[^A-Za-z0-9_-]+', '_');
    tag = regexprep(tag, '_+', '_');
    tag = regexprep(tag, '^_+|_+$', '');

    if isempty(tag)
        tag = 'area';
    end
end
