%% =========================================================================
% residual_response_check_systematic_shift_by_recording_time
%
% Purpose:
% Inspect whether condition-PSTH-subtracted residual responses show a
% systematic shift over recording time.
%
% This program reads the NON-SHUFFLED model_data_allruns.mat and uses:
%
%   demean_count_within_t_and_condition
%
% For one selected stim_tag/run:
% 1) Randomly select n_units_per_area cells from every requested area.
% 2) Convert every trial's unit x time-bin residual into one response per
%    cell and trial. The default is a sum across time bins. Because every
%    trial in one run has the same number of bins, using a mean would only
%    change the vertical scale, not the trial-by-trial shape.
% 3) Preserve the original global trialId as the x coordinate.
% 4) Generate two figures for each area:
%
%    A. condition_grid
%       rows    = randomly selected cells
%       columns = conditions
%       Each panel connects trials from only that condition in ascending
%       global trialId order.
%
%    B. conditions_together
%       rows    = randomly selected cells
%       columns = one
%       All conditions appear in the same panel with different colors, but
%       points are connected only within the same condition.
%
% With two requested areas, four figures are generated in total. The same
% sampled cells and the same row order are used in both display modes.
%
% Required input structure in model_data_allruns{run_idx}:
%   .stim_tag
%   .group_name
%   .group_probe                    % recommended for cell labels
%   .groupd, or
%   .demean_count_within_t_and_condition_groupd
%   .condition_fields
%   .condition_index_per_trial_full
%   .conditions_full
%   .demean_count_within_t_and_condition
%
% The main residual field is a 1 x Ntrial struct array. Each trial contains:
%   .trialId
%   .T
%   .y                              % unit x time bin
% =========================================================================

clc;
clear;

%% ----------------------- User parameters -----------------------

% This must be the NON-SHUFFLED model file.
dat_file = ['I:\np_data\RafiL001p0120_g1\catgt_RafiL001p0120_g1\' ...
    'model_data_allruns.mat'];

% Exact stim_tag of the run to inspect.
stim_tag = '_2[Gpl2_2c_2sz_400_2_200isi]';

% Residual generated by the updated processing_to_count_and_fr.m and
% model_data_prepar_with_trialshuffle.m.
data_content = 'demean_count_within_t_and_condition';

% One figure pair is generated for each requested area. Area names must
% match group_name in the selected model-data run. Use {} to plot all unique
% areas in their stored order.
area_names = {'V1', 'MT'};

% Random cell selection. The same selected cells are reused in both plot
% layouts. An area with fewer than this many cells causes an explicit error.
n_units_per_area = 10;
random_seed = 1;

% How to convert unit x time-bin residuals into one value per unit/trial:
%   'sum'  = sum across time bins (default; no temporal averaging)
%   'mean' = mean across time bins
time_bin_reduction = 'sum';

% Master saving switch and output options.
save_fig = true;
fig_out_dir = '';  % empty -> create a subfolder beside dat_file
save_png = true;
save_matlab_fig = false;  % .fig files can be large for the condition grid
png_dpi = 300;
close_figures_after_saving = true;

% Figure visibility: 'on' for interactive use, 'off' for headless saving.
figure_visibility = 'on';

% Plot appearance.
line_width = 1.0;
marker_size = 3.5;
zero_line_color = [0.55 0.55 0.55];
axis_font_size = 7;
title_font_size = 8;

% Large condition grids need wide figures. These values are pixels per
% condition column and per sampled-cell row, respectively.
grid_width_per_condition = 250;
grid_height_per_unit = 145;
overlay_figure_width = 1800;
overlay_height_per_unit = 145;

%% ----------------------- Validate user parameters -----------------------

if ~ischar(dat_file) && ~(isstring(dat_file) && isscalar(dat_file))
    error('dat_file must be one file path.');
end
dat_file = char(dat_file);

if ~isfile(dat_file)
    error('Data file does not exist: %s', dat_file);
end

[~, dat_file_name] = fileparts(dat_file);
if contains(lower(dat_file_name), 'trialshuffled')
    error(['This analysis requires non-shuffled model_data_allruns.mat, ', ...
        'but dat_file appears to be a shuffled output: %s'], dat_file);
end

if isstring(stim_tag) && isscalar(stim_tag)
    stim_tag = char(stim_tag);
end
if ~ischar(stim_tag) || isempty(stim_tag)
    error('stim_tag must be one nonempty character vector or string scalar.');
end

if isstring(data_content) && isscalar(data_content)
    data_content = char(data_content);
end
if ~ischar(data_content) || isempty(data_content)
    error('data_content must be one nonempty field name.');
end

if ~isscalar(n_units_per_area) || ~isnumeric(n_units_per_area) || ...
        ~isfinite(n_units_per_area) || n_units_per_area < 1 || ...
        n_units_per_area ~= round(n_units_per_area)
    error('n_units_per_area must be one positive integer.');
end

if ~isscalar(random_seed) || ~isnumeric(random_seed) || ...
        ~isfinite(random_seed)
    error('random_seed must be one finite numeric scalar.');
end

if isstring(time_bin_reduction) && isscalar(time_bin_reduction)
    time_bin_reduction = char(time_bin_reduction);
end
if ~ischar(time_bin_reduction) || ...
        ~ismember(lower(strtrim(time_bin_reduction)), {'sum', 'mean'})
    error('time_bin_reduction must be ''sum'' or ''mean''.');
end
time_bin_reduction = lower(strtrim(time_bin_reduction));

if ~(islogical(save_fig) || isnumeric(save_fig)) || ~isscalar(save_fig)
    error('save_fig must be one logical scalar.');
end
save_fig = logical(save_fig);

if ~(islogical(save_png) || isnumeric(save_png)) || ~isscalar(save_png)
    error('save_png must be one logical scalar.');
end
save_png = logical(save_png);

if ~(islogical(save_matlab_fig) || isnumeric(save_matlab_fig)) || ...
        ~isscalar(save_matlab_fig)
    error('save_matlab_fig must be one logical scalar.');
end
save_matlab_fig = logical(save_matlab_fig);

if ~(islogical(close_figures_after_saving) || ...
        isnumeric(close_figures_after_saving)) || ...
        ~isscalar(close_figures_after_saving)
    error('close_figures_after_saving must be one logical scalar.');
end
close_figures_after_saving = logical(close_figures_after_saving);

if ~isscalar(png_dpi) || ~isnumeric(png_dpi) || ...
        ~isfinite(png_dpi) || png_dpi <= 0
    error('png_dpi must be one positive finite scalar.');
end

if isstring(figure_visibility) && isscalar(figure_visibility)
    figure_visibility = char(figure_visibility);
end
if ~ischar(figure_visibility) || ...
        ~ismember(lower(strtrim(figure_visibility)), {'on', 'off'})
    error('figure_visibility must be ''on'' or ''off''.');
end
figure_visibility = lower(strtrim(figure_visibility));

area_names = normalize_text_list_local(area_names, 'area_names', true);

%% ----------------------- Load non-shuffled model data -----------------------

fprintf('Reading non-shuffled model data from:\n %s\n', dat_file);
S = load(dat_file, 'model_data_allruns');

if ~isfield(S, 'model_data_allruns')
    error('model_data_allruns not found in %s.', dat_file);
end
if ~iscell(S.model_data_allruns) || isempty(S.model_data_allruns)
    error('model_data_allruns must be a nonempty cell array.');
end

model_data_allruns = S.model_data_allruns;
clear S;

%% ----------------------- Select run by exact stim_tag -----------------------

all_run_tags = get_all_run_tags_local(model_data_allruns);
run_idx = find(strcmp(all_run_tags, stim_tag));

if isempty(run_idx)
    error('Requested stim_tag not found: %s', stim_tag);
end
if numel(run_idx) > 1
    error('Duplicate stim_tag found: %s', stim_tag);
end

this_run = model_data_allruns{run_idx};
clear model_data_allruns;

fprintf('Selected run index: %d\n', run_idx);
fprintf('Selected stim_tag : %s\n', this_run.stim_tag);

%% ----------------------- Validate selected run -----------------------

required_fields = { ...
    'group_name', ...
    'condition_index_per_trial_full', ...
    'conditions_full', ...
    data_content};

for k = 1:numel(required_fields)
    f = required_fields{k};
    if ~isfield(this_run, f)
        error('Required field %s is missing from the selected run.', f);
    end
end

group_names = normalize_text_list_local( ...
    this_run.group_name, 'this_run.group_name', false);
[groupd, groupd_field] = get_groupd_for_field_local(this_run, data_content);

if numel(group_names) ~= numel(groupd)
    error(['%s contains %d groups, but group_name contains %d names.'], ...
        groupd_field, numel(groupd), numel(group_names));
end

if isempty(area_names)
    area_names = unique(group_names, 'stable');
end
if numel(unique(area_names, 'stable')) ~= numel(area_names)
    error('area_names contains duplicate area names.');
end

available_area_text = strjoin(unique(group_names, 'stable'), ', ');
for a = 1:numel(area_names)
    if ~any(strcmp(group_names, area_names{a}))
        error('Requested area %s was not found. Available areas: %s', ...
            area_names{a}, available_area_text);
    end
end

%% ----------------------- Build ordered trial-response matrix -----------------------

[trial_ids, condition_index, response_by_unit, n_time_bins] = ...
    build_trial_response_matrix_local(this_run, data_content, ...
    time_bin_reduction);

n_units = size(response_by_unit, 1);
n_trials = size(response_by_unit, 2);

if sum(groupd) ~= n_units
    error('%s sums to %d units, but %s contains %d units.', ...
        groupd_field, sum(groupd), data_content, n_units);
end

n_conditions = numel(this_run.conditions_full);
if n_conditions < 1
    error('conditions_full is empty in the selected run.');
end

if any(condition_index < 1) || any(condition_index > n_conditions) || ...
        any(condition_index ~= round(condition_index))
    error('Invalid condition indices were found for retained trials.');
end

condition_labels = build_condition_labels_local(this_run, n_conditions);
condition_colors = lines(n_conditions);
group_row_ranges = make_group_row_ranges_local(groupd);

fprintf('Data field        : %s\n', data_content);
fprintf('Time reduction    : %s across %d bins\n', ...
    time_bin_reduction, n_time_bins);
fprintf('Retained trials   : %d\n', n_trials);
fprintf('Retained units    : %d\n', n_units);
fprintf('Number conditions : %d\n', n_conditions);

%% ----------------------- Reproducible random cell selection -----------------------

rng(random_seed, 'twister');

sampled = repmat(struct( ...
    'area_name', '', ...
    'model_rows', [], ...
    'unit_labels', {{}}, ...
    'ylimits', []), 1, numel(area_names));

for a = 1:numel(area_names)
    this_area = area_names{a};
    matching_groups = find(strcmp(group_names, this_area));

    area_rows = zeros(1, 0);
    for g = matching_groups
        area_rows = [area_rows, group_row_ranges{g}]; %#ok<AGROW>
    end

    if numel(area_rows) < n_units_per_area
        error(['Area %s contains only %d available units, but ', ...
            'n_units_per_area = %d.'], ...
            this_area, numel(area_rows), n_units_per_area);
    end

    random_order = randperm(numel(area_rows), n_units_per_area);
    selected_rows = sort(area_rows(random_order));

    sampled(a).area_name = this_area;
    sampled(a).model_rows = selected_rows;
    sampled(a).unit_labels = build_unit_labels_local( ...
        this_run, data_content, selected_rows, group_names, groupd, ...
        group_row_ranges);

    sampled(a).ylimits = zeros(n_units_per_area, 2);
    for r = 1:n_units_per_area
        sampled(a).ylimits(r, :) = padded_limits_including_zero_local( ...
            response_by_unit(selected_rows(r), :));
    end

    fprintf('\nArea %s\n', this_area);
    fprintf(' Sampled model rows: %s\n', mat2str(selected_rows));
    for r = 1:n_units_per_area
        fprintf('  row %2d: model row %d, %s\n', ...
            r, selected_rows(r), sampled(a).unit_labels{r});
    end
end

%% ----------------------- Prepare saving -----------------------

if isempty(fig_out_dir)
    fig_out_dir = fullfile(fileparts(dat_file), ...
        'residual_response_check_systematic_shift_by_recording_time');
elseif isstring(fig_out_dir) && isscalar(fig_out_dir)
    fig_out_dir = char(fig_out_dir);
end

if save_fig && ~isfolder(fig_out_dir)
    mkdir(fig_out_dir);
end

safe_stim_tag = make_safe_file_tag_local(stim_tag, 80);

%% ----------------------- Generate both layouts for every area -----------------------

for a = 1:numel(sampled)
    this_area = sampled(a).area_name;
    selected_rows = sampled(a).model_rows;
    unit_labels = sampled(a).unit_labels;
    row_ylimits = sampled(a).ylimits;

    %% Plot A: cells x conditions grid
    h_grid = plot_condition_grid_local( ...
        trial_ids, condition_index, response_by_unit, selected_rows, ...
        unit_labels, row_ylimits, condition_labels, condition_colors, ...
        this_area, stim_tag, time_bin_reduction, figure_visibility, ...
        line_width, marker_size, zero_line_color, ...
        axis_font_size, title_font_size, ...
        grid_width_per_condition, grid_height_per_unit);

    %% Plot B: all conditions together, one panel per cell
    h_together = plot_conditions_together_local( ...
        trial_ids, condition_index, response_by_unit, selected_rows, ...
        unit_labels, row_ylimits, condition_labels, condition_colors, ...
        this_area, stim_tag, time_bin_reduction, figure_visibility, ...
        line_width, marker_size, zero_line_color, ...
        axis_font_size, overlay_figure_width, overlay_height_per_unit);

    if save_fig
        safe_area = make_safe_file_tag_local(this_area, 40);
        common_tag = sprintf('run%02d_%s_%s_seed%d', ...
            run_idx, safe_stim_tag, safe_area, random_seed);

        save_figure_local(h_grid, fig_out_dir, ...
            sprintf('%s_condition_grid', common_tag), ...
            save_png, save_matlab_fig, png_dpi);

        save_figure_local(h_together, fig_out_dir, ...
            sprintf('%s_conditions_together', common_tag), ...
            save_png, save_matlab_fig, png_dpi);
    end

    if close_figures_after_saving
        close(h_grid);
        close(h_together);
    end
end

fprintf('\nDone. Generated %d figures (%d areas x 2 layouts).\n', ...
    numel(sampled) * 2, numel(sampled));
if save_fig
    fprintf('Figure output folder:\n %s\n', fig_out_dir);
end

%% ======================= Local functions =======================

function tags = get_all_run_tags_local(model_data_allruns)
tags = cell(numel(model_data_allruns), 1);
for i = 1:numel(model_data_allruns)
    if ~isstruct(model_data_allruns{i}) || ...
            ~isfield(model_data_allruns{i}, 'stim_tag')
        error('model_data_allruns{%d} is missing stim_tag.', i);
    end
    tags{i} = model_data_allruns{i}.stim_tag;
end
end

function values = normalize_text_list_local(values, variable_name, allow_empty)
if nargin < 3
    allow_empty = false;
end

if isempty(values)
    if allow_empty
        values = {};
        return;
    end
    error('%s must not be empty.', variable_name);
end

if ischar(values)
    values = {values};
elseif isstring(values)
    values = cellstr(values(:));
elseif iscell(values)
    values = values(:);
else
    error('%s must contain text values.', variable_name);
end

out = cell(1, numel(values));
for i = 1:numel(values)
    value = values{i};
    if isstring(value) && isscalar(value)
        value = char(value);
    end
    if ~ischar(value) || isempty(strtrim(value))
        error('%s{%d} must be one nonempty text value.', variable_name, i);
    end
    out{i} = strtrim(value);
end
values = out;
end

function [groupd, field_name] = get_groupd_for_field_local(run_entry, data_field)
specific_field = sprintf('%s_groupd', data_field);
if isfield(run_entry, specific_field)
    groupd = run_entry.(specific_field);
    field_name = specific_field;
elseif isfield(run_entry, 'groupd')
    groupd = run_entry.groupd;
    field_name = 'groupd';
else
    error('Neither %s nor groupd exists in the selected run.', specific_field);
end

groupd = double(groupd(:)');
if isempty(groupd) || any(~isfinite(groupd)) || ...
        any(groupd < 0) || any(groupd ~= round(groupd))
    error('%s must contain finite nonnegative integer group sizes.', field_name);
end
end

function [trial_ids, condition_index, response_by_unit, n_time_bins] = ...
        build_trial_response_matrix_local(run_entry, data_field, reduction)

trial_data = run_entry.(data_field);
if ~isstruct(trial_data) || isempty(trial_data) || ...
        ~isfield(trial_data, 'trialId') || ...
        ~isfield(trial_data, 'T') || ...
        ~isfield(trial_data, 'y')
    error('%s must be a nonempty trial struct array with trialId, T, and y.', ...
        data_field);
end

n_trials = numel(trial_data);
unsorted_trial_ids = zeros(1, n_trials);
for i = 1:n_trials
    unsorted_trial_ids(i) = trial_data(i).trialId;
end

if any(~isfinite(unsorted_trial_ids)) || ...
        any(unsorted_trial_ids < 1) || ...
        any(unsorted_trial_ids ~= round(unsorted_trial_ids))
    error('%s contains invalid trialId values.', data_field);
end
if numel(unique(unsorted_trial_ids)) ~= n_trials
    error('%s contains duplicate trialId values.', data_field);
end

[trial_ids, sort_order] = sort(unsorted_trial_ids, 'ascend');
trial_data = trial_data(sort_order);

first_y = trial_data(1).y;
if ~isnumeric(first_y) || ndims(first_y) > 2 || isempty(first_y)
    error('%s trial 1 contains an invalid y matrix.', data_field);
end

n_units = size(first_y, 1);
n_time_bins = size(first_y, 2);
response_by_unit = nan(n_units, n_trials);

for i = 1:n_trials
    y = trial_data(i).y;
    if ~isnumeric(y) || ~isequal(size(y), [n_units, n_time_bins])
        error(['%s has inconsistent y size at trialId %d. Expected ', ...
            '%d x %d.'], data_field, trial_data(i).trialId, ...
            n_units, n_time_bins);
    end
    if ~isscalar(trial_data(i).T) || trial_data(i).T ~= n_time_bins
        error('%s has inconsistent T at trialId %d.', ...
            data_field, trial_data(i).trialId);
    end
    if any(~isfinite(y(:)))
        error(['Nonfinite residual values were found in %s at trialId %d. ', ...
            'Use a model-data NaN strategy that provides finite values.'], ...
            data_field, trial_data(i).trialId);
    end

    switch reduction
        case 'sum'
            response_by_unit(:, i) = sum(y, 2);
        case 'mean'
            response_by_unit(:, i) = mean(y, 2);
        otherwise
            error('Unknown time-bin reduction: %s', reduction);
    end
end

full_condition_index = run_entry.condition_index_per_trial_full(:)';
if any(trial_ids > numel(full_condition_index))
    error(['At least one retained trialId exceeds the length of ', ...
        'condition_index_per_trial_full.']);
end
condition_index = full_condition_index(trial_ids);
end

function ranges = make_group_row_ranges_local(groupd)
ranges = cell(1, numel(groupd));
row_start = 1;
for g = 1:numel(groupd)
    row_end = row_start + groupd(g) - 1;
    if groupd(g) == 0
        ranges{g} = zeros(1, 0);
    else
        ranges{g} = row_start:row_end;
    end
    row_start = row_end + 1;
end
end

function labels = build_condition_labels_local(run_entry, n_conditions)
if isfield(run_entry, 'condition_fields')
    condition_fields = normalize_text_list_local( ...
        run_entry.condition_fields, 'condition_fields', true);
else
    condition_fields = {};
end

labels = cell(1, n_conditions);
for c = 1:n_conditions
    parts = cell(1, 0);
    for k = 1:numel(condition_fields)
        f = condition_fields{k};
        if isfield(run_entry.conditions_full(c), f)
            parts{end + 1} = sprintf('%s=%s', f, ...
                value_to_text_local(run_entry.conditions_full(c).(f))); %#ok<AGROW>
        end
    end

    if isempty(parts)
        labels{c} = sprintf('Condition %d', c);
    else
        labels{c} = sprintf('C%d: %s', c, strjoin(parts, ', '));
    end
end
end

function text_value = value_to_text_local(value)
if isnumeric(value)
    if isempty(value)
        text_value = '[]';
    elseif isscalar(value)
        text_value = sprintf('%.6g', value);
    else
        text_value = mat2str(value);
    end
elseif islogical(value)
        text_value = mat2str(value);
elseif ischar(value)
    text_value = value;
elseif isstring(value)
    text_value = strjoin(cellstr(value(:)), '|');
elseif iscategorical(value)
    text_value = strjoin(cellstr(string(value(:))), '|');
elseif iscell(value)
    pieces = cell(size(value));
    for i = 1:numel(value)
        pieces{i} = value_to_text_local(value{i});
    end
    text_value = strjoin(pieces(:)', '|');
else
    try
        text_value = char(string(value));
    catch
        text_value = class(value);
    end
end
end

function labels = build_unit_labels_local( ...
        run_entry, data_field, selected_rows, group_names, groupd, ranges)

labels = cell(1, numel(selected_rows));

if isfield(run_entry, 'group_probe')
    group_probe = double(run_entry.group_probe(:)');
    if numel(group_probe) ~= numel(groupd)
        error('group_probe and groupd must contain the same number of groups.');
    end
else
    group_probe = nan(size(groupd));
end

for i = 1:numel(selected_rows)
    model_row = selected_rows(i);
    group_index = find(cellfun(@(x) any(x == model_row), ranges), 1);
    if isempty(group_index)
        error('Could not map model row %d to one group.', model_row);
    end

    area_name = group_names{group_index};
    within_group_index = model_row - ranges{group_index}(1) + 1;
    probe_index = group_probe(group_index);
    found_unit_id = false;
    unit_id = NaN;

    if isfinite(probe_index)
        preceding_same_probe = find( ...
            group_probe(1:group_index-1) == probe_index);
        probe_local_offset = sum(groupd(preceding_same_probe));
        probe_local_index = probe_local_offset + within_group_index;

        field_specific_ids = sprintf('%s_probe%d_usedunit_ids', ...
            data_field, probe_index);
        common_ids = sprintf('probe%d_usedunit_ids', probe_index);

        if isfield(run_entry, field_specific_ids)
            ids = run_entry.(field_specific_ids);
        elseif isfield(run_entry, common_ids)
            ids = run_entry.(common_ids);
        else
            ids = [];
        end

        ids = ids(:);
        if probe_local_index >= 1 && probe_local_index <= numel(ids)
            unit_id = ids(probe_local_index);
            found_unit_id = isnumeric(unit_id) && isscalar(unit_id) && ...
                isfinite(unit_id);
        end
    end

    if found_unit_id
        labels{i} = sprintf('%s | prb%d unit %.0f', ...
            area_name, probe_index, unit_id);
    elseif isfinite(probe_index)
        labels{i} = sprintf('%s | prb%d model row %d', ...
            area_name, probe_index, model_row);
    else
        labels{i} = sprintf('%s | model row %d', area_name, model_row);
    end
end
end

function lim = padded_limits_including_zero_local(values)
values = values(isfinite(values));
if isempty(values)
    lim = [-1 1];
    return;
end

lo = min([values(:); 0]);
hi = max([values(:); 0]);

if hi == lo
    pad = max(1, abs(hi) * 0.1);
else
    pad = 0.08 * (hi - lo);
end
lim = [lo - pad, hi + pad];
end

function x_limits = padded_trial_limits_local(trial_ids)
lo = min(trial_ids);
hi = max(trial_ids);
if hi == lo
    x_limits = [lo - 0.5, hi + 0.5];
else
    pad = max(0.5, 0.01 * (hi - lo));
    x_limits = [lo - pad, hi + pad];
end
end

function hfig = plot_condition_grid_local( ...
        trial_ids, condition_index, response_by_unit, selected_rows, ...
        unit_labels, row_ylimits, condition_labels, condition_colors, ...
        area_name, stim_tag, reduction, figure_visibility, ...
        line_width, marker_size, zero_line_color, ...
        axis_font_size, title_font_size, ...
        width_per_condition, height_per_unit)

n_rows = numel(selected_rows);
n_conditions = numel(condition_labels);
x_limits = padded_trial_limits_local(trial_ids);

figure_width = max(1400, width_per_condition * n_conditions);
figure_height = max(900, height_per_unit * n_rows);

hfig = figure('Color', 'w', ...
    'Visible', figure_visibility, ...
    'Name', sprintf('%s residual shift: condition grid', area_name), ...
    'Position', [40 40 figure_width figure_height]);

tl = tiledlayout(n_rows, n_conditions, ...
    'TileSpacing', 'compact', 'Padding', 'compact');

for r = 1:n_rows
    model_row = selected_rows(r);
    for c = 1:n_conditions
        ax = nexttile(tl);
        take = (condition_index == c);

        hold(ax, 'on');
        if any(take)
            plot(ax, trial_ids(take), response_by_unit(model_row, take), ...
                '-o', ...
                'Color', condition_colors(c, :), ...
                'MarkerFaceColor', condition_colors(c, :), ...
                'MarkerEdgeColor', condition_colors(c, :), ...
                'LineWidth', line_width, ...
                'MarkerSize', marker_size);
        else
            text(ax, mean(x_limits), mean(row_ylimits(r, :)), ...
                'No trials', 'HorizontalAlignment', 'center', ...
                'Color', [0.5 0.5 0.5]);
        end

        yline(ax, 0, '--', 'Color', zero_line_color, 'LineWidth', 0.7);
        xlim(ax, x_limits);
        ylim(ax, row_ylimits(r, :));
        grid(ax, 'on');
        box(ax, 'on');
        ax.FontSize = axis_font_size;

        if r == 1
            title(ax, condition_labels{c}, ...
                'Interpreter', 'none', 'FontSize', title_font_size);
        end
        if c == 1
            ylabel(ax, sprintf('%s\nResponse', unit_labels{r}), ...
                'Interpreter', 'none');
        else
            ax.YTickLabel = [];
        end
        if r == n_rows
            xlabel(ax, 'Global trial ID');
        else
            ax.XTickLabel = [];
        end
    end
end

sgtitle(tl, sprintf(['%s | %s | residual response by recording time | ', ...
    'conditions separated | time-bin %s'], ...
    area_name, stim_tag, reduction), 'Interpreter', 'none');
end

function hfig = plot_conditions_together_local( ...
        trial_ids, condition_index, response_by_unit, selected_rows, ...
        unit_labels, row_ylimits, condition_labels, condition_colors, ...
        area_name, stim_tag, reduction, figure_visibility, ...
        line_width, marker_size, zero_line_color, ...
        axis_font_size, figure_width, height_per_unit)

n_rows = numel(selected_rows);
n_conditions = numel(condition_labels);
x_limits = padded_trial_limits_local(trial_ids);
figure_height = max(900, height_per_unit * n_rows);

hfig = figure('Color', 'w', ...
    'Visible', figure_visibility, ...
    'Name', sprintf('%s residual shift: conditions together', area_name), ...
    'Position', [60 40 figure_width figure_height]);

tl = tiledlayout(n_rows, 1, ...
    'TileSpacing', 'compact', 'Padding', 'compact');

legend_handles = gobjects(1, n_conditions);
first_axis = [];

for r = 1:n_rows
    model_row = selected_rows(r);
    ax = nexttile(tl);
    if r == 1
        first_axis = ax;
    end
    hold(ax, 'on');

    for c = 1:n_conditions
        take = (condition_index == c);
        if ~any(take)
            continue;
        end

        h = plot(ax, trial_ids(take), response_by_unit(model_row, take), ...
            '-o', ...
            'Color', condition_colors(c, :), ...
            'MarkerFaceColor', condition_colors(c, :), ...
            'MarkerEdgeColor', condition_colors(c, :), ...
            'LineWidth', line_width, ...
            'MarkerSize', marker_size);

        if r == 1
            legend_handles(c) = h;
        end
    end

    yline(ax, 0, '--', 'Color', zero_line_color, 'LineWidth', 0.7);
    xlim(ax, x_limits);
    ylim(ax, row_ylimits(r, :));
    grid(ax, 'on');
    box(ax, 'on');
    ax.FontSize = axis_font_size;
    ylabel(ax, sprintf('%s\nResponse', unit_labels{r}), ...
        'Interpreter', 'none');

    if r == n_rows
        xlabel(ax, 'Global trial ID');
    else
        ax.XTickLabel = [];
    end
end

valid_legend = isgraphics(legend_handles);
if any(valid_legend)
    lgd = legend(first_axis, legend_handles(valid_legend), ...
        condition_labels(valid_legend), ...
        'Interpreter', 'none', 'Location', 'eastoutside');
    try
        lgd.Layout.Tile = 'east';
    catch
        % Older MATLAB versions keep the legend beside the first axes.
    end
end

sgtitle(tl, sprintf(['%s | %s | residual response by recording time | ', ...
    'conditions together, connected separately | time-bin %s'], ...
    area_name, stim_tag, reduction), 'Interpreter', 'none');
end

function save_figure_local(hfig, output_dir, base_name, ...
        save_png, save_matlab_fig, png_dpi)

if save_png
    png_file = fullfile(output_dir, [base_name '.png']);
    try
        exportgraphics(hfig, png_file, 'Resolution', png_dpi);
    catch
        print(hfig, png_file, '-dpng', sprintf('-r%d', round(png_dpi)));
    end
    fprintf('Saved PNG: %s\n', png_file);
end

if save_matlab_fig
    fig_file = fullfile(output_dir, [base_name '.fig']);
    savefig(hfig, fig_file);
    fprintf('Saved FIG: %s\n', fig_file);
end
end

function safe_tag = make_safe_file_tag_local(text_value, max_length)
if isstring(text_value) && isscalar(text_value)
    text_value = char(text_value);
end
if ~ischar(text_value)
    text_value = char(string(text_value));
end

safe_tag = regexprep(text_value, '[^A-Za-z0-9_-]+', '_');
safe_tag = regexprep(safe_tag, '_+', '_');
safe_tag = regexprep(safe_tag, '^_+|_+$', '');

if isempty(safe_tag)
    safe_tag = 'unnamed';
end
if numel(safe_tag) > max_length
    safe_tag = safe_tag(1:max_length);
end
end
